# Import

In [17]:
!pip install -r requirements.txt

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (3.10.3)
Requirement already satisfied: whisperx in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (3.3.1)
Collecting torch==2.2.2 (from -r requirements.txt (line 4))
  Downloading torch-2.2.2-cp312-cp312-manylinux1_x86_64.whl.metadata (25 kB)
Collecting torchvision==0.17.2 (from -r requirements.txt (line 5))
  Downloading torchvision-0.17.2-cp312-cp312-manylinux1_x86_64.whl.metadata (6.6 kB)
Collecting torchaudio==2.2.2 (from -r requirements.txt (line 6))
  Downloading torchaudio-2.2.2-cp312-cp312-manylinux1_x86_64.whl.metadata (6.4 kB)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 7)) (0.25.1)
Requirement already satisfied: python-docx in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (1.2.0)
Requirement already satisfied: datetime in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 9)) (6.0)
Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 10)) (0.19.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2->-r requirements.txt (line 4)) (3.18.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2->-r requirements.txt (line 4)) (4.15.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2->-r requirements.txt (line 4)) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2->-r requirements.txt (line 4)) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2->-r requirements.txt (line 4)) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch==2.2.2->-r requirements.txt (line 4)) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 4))
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 4))
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 4))
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.2.2->-r requirements.txt (line 4))
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.2.2->-r requirements.txt (line 4))
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.2.2->-r requirements.txt (line 4))
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.2.2->-r requirements.txt (line 4))
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.2.2->-r requirements.txt (line 4))
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.2.2->-r requirements.txt (line 4))
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch==2.2.2->-r requirements.txt (line 4))
  Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.2.2->-r requirements.txt (line 4))
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision==0.17.2->-r requirements.txt (line 5)) (12.1.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->-r requirements.txt (line 4)) (12.8.93)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: faster-whisper==1.1.0 in /usr/local/lib/python3.12/dist-packages (from whisperx->-r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: ctranslate2<4.5.0 in /usr/local/lib/python3.12/dist-packages (from whisperx->-r requirements.txt (line 3)) (4.4.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from whisperx->-r requirements.txt (line 3)) (4.37.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from whisperx->-r requirements.txt (line 3)) (3.0.1)
Requirement already satisfied: setuptools>=65 in /usr/local/lib/python3.12/dist-packages (from whisperx->-r requirements.txt (line 3)) (80.9.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from whisperx->-r requirements.txt (line 3)) (3.9.2)
Collecting pyannote.audio==3.3.2 (from whisperx->-r requirements.txt (line 3))
  Downloading pyannote_audio-3.3.2-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: huggingface-hub>=0.13 in /usr/local/lib/python3.12/dist-packages (from faster-whisper==1.1.0->whisperx->-r requirements.txt (line 3)) (0.36.2)
Requirement already satisfied: tokenizers<1,>=0.13 in /usr/local/lib/python3.12/dist-packages (from faster-whisper==1.1.0->whisperx->-r requirements.txt (line 3)) (0.15.2)
Requirement already satisfied: onnxruntime<2,>=1.14 in /usr/local/lib/python3.12/dist-packages (from faster-whisper==1.1.0->whisperx->-r requirements.txt (line 3)) (1.24.2)
Requirement already satisfied: av>=11 in /usr/local/lib/python3.12/dist-packages (from faster-whisper==1.1.0->whisperx->-r requirements.txt (line 3)) (16.1.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from faster-whisper==1.1.0->whisperx->-r requirements.txt (line 3)) (4.67.1)
Requirement already satisfied: asteroid-filterbanks>=0.4 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (0.4.0)
Requirement already satisfied: einops>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (0.8.1)
Requirement already satisfied: lightning>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (2.6.1)
Requirement already satisfied: omegaconf<3.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (2.3.0)
Requirement already satisfied: pyannote.core>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (5.0.0)
Requirement already satisfied: pyannote.database>=5.0.1 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (5.1.3)
Requirement already satisfied: pyannote.metrics>=3.2 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (3.2.1)
Requirement already satisfied: pyannote.pipeline>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (3.0.1)
Requirement already satisfied: pytorch_metric_learning>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (2.9.0)
Requirement already satisfied: rich>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (14.3.3)
Requirement already satisfied: semver>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (3.0.4)
Requirement already satisfied: soundfile>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (0.13.1)
Requirement already satisfied: speechbrain>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.0.3)
Requirement already satisfied: tensorboardX>=2.6 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (2.6.4)
Requirement already satisfied: torch_audiomentations>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (0.12.0)
Requirement already satisfied: torchmetrics>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.8.2)
Requirement already satisfied: pyyaml<7,>=5.3 in /usr/local/lib/python3.12/dist-packages (from ctranslate2<4.5.0->whisperx->-r requirements.txt (line 3)) (6.0.3)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (4.9.3)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime<2,>=1.14->faster-whisper==1.1.0->whisperx->-r requirements.txt (line 3)) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime<2,>=1.14->faster-whisper==1.1.0->whisperx->-r requirements.txt (line 3)) (4.24.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.13->faster-whisper==1.1.0->whisperx->-r requirements.txt (line 3)) (1.2.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.13->faster-whisper==1.1.0->whisperx->-r requirements.txt (line 3)) (2.32.5)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx->-r requirements.txt (line 8)) (6.0.2)
Requirement already satisfied: zope.interface in /usr/local/lib/python3.12/dist-packages (from datetime->-r requirements.txt (line 9)) (8.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from datetime->-r requirements.txt (line 9)) (2025.2)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in /usr/local/lib/python3.12/dist-packages/lightning_utilities-0.14.3-py3.12.egg (from lightning>=2.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (0.14.3)
Requirement already satisfied: pytorch-lightning in /usr/local/lib/python3.12/dist-packages (from lightning>=2.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (2.6.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (3.11.16)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.19.0)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (3.11)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->whisperx->-r requirements.txt (line 3)) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->whisperx->-r requirements.txt (line 3)) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->whisperx->-r requirements.txt (line 3)) (2024.11.6)
Requirement already satisfied: sortedcontainers>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from pyannote.core>=5.0.0->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (2.4.0)
Requirement already satisfied: scipy>=1.1 in /usr/local/lib/python3.12/dist-packages (from pyannote.core>=5.0.0->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.17.1)
Requirement already satisfied: typer>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from pyannote.database>=5.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (0.24.0)
Requirement already satisfied: scikit-learn>=0.17.1 in /usr/local/lib/python3.12/dist-packages (from pyannote.metrics>=3.2->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.8.0)
Requirement already satisfied: docopt>=0.6.2 in /usr/local/lib/python3.12/dist-packages (from pyannote.metrics>=3.2->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (0.6.2)
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.12/dist-packages (from pyannote.metrics>=3.2->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (0.9.0)
Requirement already satisfied: optuna>=3.1 in /usr/local/lib/python3.12/dist-packages (from pyannote.pipeline>=3.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (4.7.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna>=3.1->pyannote.pipeline>=3.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna>=3.1->pyannote.pipeline>=3.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna>=3.1->pyannote.pipeline>=3.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (2.0.46)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna>=3.1->pyannote.pipeline>=3.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.3.10)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.0.0->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.0.0->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (0.1.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.17.1->pyannote.metrics>=3.2->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from soundfile>=0.12.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->soundfile>=0.12.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (2.23)
Requirement already satisfied: hyperpyyaml in /usr/local/lib/python3.12/dist-packages (from speechbrain>=1.0.0->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.2.3)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from speechbrain>=1.0.0->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (0.2.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna>=3.1->pyannote.pipeline>=3.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->torch==2.2.2->-r requirements.txt (line 4)) (1.3.0)
Requirement already satisfied: julius<0.3,>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from torch_audiomentations>=0.11.0->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (0.2.7)
Requirement already satisfied: torch-pitch-shift>=1.2.2 in /usr/local/lib/python3.12/dist-packages (from torch_audiomentations>=0.11.0->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.2.5)
Requirement already satisfied: primePy>=1.3 in /usr/local/lib/python3.12/dist-packages (from torch-pitch-shift>=1.2.2->torch_audiomentations>=0.11.0->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.12.1->pyannote.database>=5.0.1->pyannote.audio==3.3.2->whisperx->-r requirements.txt (line 3)) (1.5.4)

In [16]:
#!pip install transformers==4.37.2
# pip install huggingface_hub==0.20.3
# !pip install pyannote.audio==3.1.1
# pip install whisperx
# !conda install -c conda-forge pydub

Collecting transformers==4.37.2
  Downloading transformers-4.37.2-py3-none-any.whl.metadata (129 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.37.2) (3.18.0)
Collecting huggingface-hub<1.0,>=0.19.3 (from transformers==4.37.2)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.37.2) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.37.2) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.37.2) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.37.2) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.37.2) (2.32.5)
Collecting tokenizers<0.19,>=0.14 (from transformers==4.37.2)
  Downloading tokenizers-0.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.37.2) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.37.2) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.37.2) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.37.2) (1.2.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.37.2) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.37.2) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.37.2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.37.2) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.37.2) (2026.1.4)
Downloading transformers-4.37.2-py3-none-any.whl (8.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 143.3 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 840.7 MB/s eta 0:00:00
Downloading tokenizers-0.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 201.2 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.4.1
    Uninstalling huggingface_hub-1.4.1:
      Successfully uninstalled huggingface_hub-1.4.1
  Attempting uninstall: tokenizers━━━━━━━━━━━━━━ 0/3 [huggingface-hub]
    Found existing installation: tokenizers 0.22.2[32m0/3 [huggingface-hub]
    Uninstalling tokenizers-0.22.2:━━━━━━━━━ 0/3 [huggingface-hub]
      Successfully uninstalled tokenizers-0.22.2 0/3 [huggingface-hub]
  Attempting uninstall: transformers━━━━━━━━ 0/3 [huggingface-hub]
    Found existing installation: transformers 5.2.032m0/3 [huggingface-hub]
    Uninstalling transformers-5.2.0:0m╸━━━━━━━━━━━━━ 2/3 [transformers]
      Successfully uninstalled transformers-5.2.0[90m━━━━━━━━━━━━━ 2/3 [transformers]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [transformers][0m [transformers]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
whisperx 3.3.1 requires pyannote.audio==3.3.2, but you have pyannote-audio 3.1.1 which is incompatible.
Successfully installed huggingface-hub-0.36.2 tokenizers-0.15.2 transformers-4.37.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [2]:
# !pip install whisperx
# # !pip uninstall torch torchvision torchaudio
# # pip uninstall torch torchvision torchaudio
# pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2
# !pip install evaluate
# !pip install python-docx
# !pip install --upgrade torch torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
# !pip install --upgrade transformers
# !pip install --upgrade transformers
# !pip install evaluate
# !pip show torch transformers

In [4]:
# !pip list

In [1]:
import os
# from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor
os.environ["PATH"] = '/app/notebooks/ARI_temp/src/whisperx/ffmpeg-7.0.2-amd64-static:' + os.environ["PATH"]
print(os.environ['PATH'])

/app/notebooks/ARI_temp/src/whisperx/ffmpeg-7.0.2-amd64-static:/usr/local/lib/python3.12/dist-packages/torch_tensorrt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/mpi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ucx/bin:/opt/amazon/efa/bin:/opt/tensorrt/bin

In [2]:
import torch
import whisperx
import gc
# import torch 
import whisper_helper as helper
import os
# import evaluate
import time
import copy 
import numpy as np
import wave
import gc
import transformers
print(transformers.__file__)

3.9.2
/usr/local/lib/python3.12/dist-packages/transformers/__init__.py

In [3]:
import torchaudio
import torch
print("torch:", torch.__version__)
print("torchaudio:", torchaudio.__version__)

torch: 2.2.2+cu121
torchaudio: 2.2.2+cu121

In [4]:
import torch
print(torch.cuda.is_available())

True

In [5]:
gc.collect()
torch.cuda.empty_cache()

# Helper

In [6]:
##  build segments
def build_segments(reconstruction_words):
    current_speaker = reconstruction_words[0]['speaker']
    text= reconstruction_words[0]['word']
    start= reconstruction_words[0]['start']
    end = reconstruction_words[0]['end']
    dict_= {}
    dict_segments=[]
    
    for word in reconstruction_words[1:]:
        if 'speaker' not in word:
            continue 
        if word['speaker']== current_speaker:
            # text = f'{text} {segment['text']}'\
            end = word['end']
            text += f' {word['word']}'
        else:
            dict_['speaker'] = current_speaker
            dict_['start'] = start
            dict_['end'] = end
            dict_['text']= text.strip()
            # dict_['words']= words
    
            dict_segments.append(dict_)
            ## new speaker
            dict_= {}
            text = word['word']
            # words=segment['words']
            start= word['start']
            end = word['end']
            current_speaker = word['speaker']
            
    
    dict_['speaker'] = current_speaker
    dict_['start'] = start
    dict_['end'] = end
    dict_['text']= text.strip()
    dict_segments.append(dict_)
    return dict_segments

# for segment in dict_segments:
#     segment['text']= ' '.join([word['word'] for word in segment['words']])

def longest_common_substring(text1: str, text2: str) -> str:
    n, m = len(text1), len(text2)
    dp = [[0] * (m + 1) for _ in range(n + 1)]
    max_len = 0
    end_pos = 0

    for i in range(1, n + 1):
        for j in range(1, m + 1):
            if text1[i - 1] == text2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1] + 1
                if dp[i][j] > max_len:
                    max_len = dp[i][j]
                    end_pos = i
            else:
                dp[i][j] = 0

    return text1[end_pos - max_len:end_pos]

def check_alignment(reference_segments, prediction_segments, blue_thre=0.75, thres=1):
    counter=0
    for segment_speaker in prediction_segments:
        speaker_start = segment_speaker['start']
        speaker_text = segment_speaker['text'].lower().strip()
        hyp = True
        for segment_master in reference_segments['segments']:
            if segment_master['start'] >speaker_start -thres and segment_master['start'] <speaker_start+thres:
                master_text = segment_master['text'].lower().strip()
                if bleu.compute(predictions=[speaker_text], references=[master_text])['precisions'][0]>blue_thre or speaker_text in master_text:
                    counter +=1
                    hyp=False
                    break 

    try:
        return (counter/len(segments))
    except:
        print (counter, segments)

def split_into_sentences(text):
    return sent_tokenize(text)


def find_subsequence_start(main_list, sub_list):
    """
    Finds the starting index of sub_list inside main_list.
    Returns -1 if sub_list is not found.
    """
    len_sub = len(sub_list)
    len_main = len(main_list)

    # Loop through main list
    for i in range(len_main - len_sub + 1):
        # Check if slice matches
        if main_list[i:i+len_sub] == sub_list:
            return i
    return -1
def get_aligned_ts(speaker_dict, master_text,master_result):
    text= ''
    words=[]
    for segment in speaker_dict['segments']:
        text +=  f''' {segment['text']}'''
        words += segment['words']
    text = text.strip()

    ## find the longest overlap
    result = longest_common_substring(text, master_text)
    print("Longest overlapping text:", result)

    ## find the segment with the longest overlap
    max_len = float('-inf')
    best_segment = None
    for idx in range(len(speaker_dict['segments'])):
        segment = speaker_dict['segments'][idx]
        if segment['text'] in result:
            if len(segment['text'])>max_len:
                max_len = len(segment['text'])
                best_segment= idx
    if best_segment is None:
            return speaker_dict

    best_segment_speaker = speaker_dict['segments'][best_segment]  
    speaker_segment_idx = best_segment
    print (f'speaker segment: {speaker_segment_idx} : {best_segment_speaker['text']}')
    
    
    max_len = float('-inf')
    best_segment = 0
    for idx in range(len(master_result['segments'])):
        segment = master_result['segments'][idx]
        if segment['text'] in best_segment_speaker['text']:
            if len(segment['text'])>max_len:
                max_len = len(segment['text'])
                best_segment= idx
    
    best_segment_master = master_result['segments'][best_segment]  
    master_segment_idx =best_segment

    print (f'master segment: { master_segment_idx} : {best_segment_master['text']}')

    final_sequence = longest_common_substring(best_segment_master['text'],best_segment_speaker['text'])
    print("Longest overlapping sequence:", final_sequence)

    ## find Delta
    overlapping_words = final_sequence.split()
    speaker_overlapping_words = best_segment_speaker['text'].split()
    master_overlapping_words = best_segment_master['text'].split()
    idx_master= find_subsequence_start(overlapping_words, master_overlapping_words)
    idx_speaker= find_subsequence_start(overlapping_words,speaker_overlapping_words)

    speaker_overlapping_words = speaker_overlapping_words[idx_speaker:len(overlapping_words)]
    master_overlapping_words = master_overlapping_words[idx_master:len(overlapping_words)]


    if len( master_overlapping_words) ==0:
            print (f'Speaker overlapping: {speaker_overlapping_words}')
            print (f'Master overlapping: {master_overlapping_words}')
        
            return speaker_dict

    print (f'Speaker overlapping: {speaker_overlapping_words}')
    print (f'Master overlapping: {master_overlapping_words}')

    speaker_tss_words= best_segment_speaker['words'][idx_speaker:len(overlapping_words)]
    master_tss_words= best_segment_master['words'][idx_master:len(overlapping_words)]

    words_time =[]
    for speaker_, master_ in zip(speaker_tss_words, master_tss_words):
         word = speaker_['word']
         dict_ = { 'word' : word,
                  'start_master': master_ ['start'],
                   'start_speaker': speaker_['start']}

         words_time.append(dict_)
    print (words_time)

    # idx_master=0
    # idx_speaker = 0
    # words_time =[]
    # master_word= np.nan
    # speaker_word = np.nan
    # for word in overlapping_words:
    #     while master_word != word:
    #         master_word = best_segment_master['words'][idx_master]['word']
    #         idx_master+=1
            
    #     while speaker_word != word:
    #         speaker_word = best_segment_speaker['words'][idx_speaker]['word']
    #         idx_speaker+=1   
    #     dict_ = { 'word' : word,
    #                 'idx_master':  idx_master-1, 'idx_speaker':idx_speaker-1, 
    #               'start_master': best_segment_master['words'][idx_master-1]['start'],
    #                'start_speaker': best_segment_speaker['words'][idx_speaker-1]['start']}
    #     words_time.append(dict_)
    # print (
    for word in words_time:
        word['delta']= word['start_master'] - word['start_speaker']
    mean_delta = np.mean([word['delta'] for word in words_time])
    print ('Mean Delta', mean_delta)
    print ('Min Delta', min ([word['delta'] for word in words_time]))
    print ('Max Delta', max([word['delta'] for word in words_time]))

    for segment in speaker_dict['segments']:
        segment['start'] = segment['start']+mean_delta
        segment['end'] = segment['end']+mean_delta

        for word in segment['words']:
            if 'start' not in word:
                continue 
            word['start'] += mean_delta
            word['end'] += mean_delta

    return speaker_dict


import re
from collections import Counter

def remove_punctuation(text):
    return re.sub(r"[^\w\s]", "", text)


def count_items(lst):
    return dict(Counter(lst))
    
def reconstruction_sentences_func(text,words):
        stt_reconstruction = []
        segments = split_into_sentences(text)
        word_idx=0
        for segment in segments:
            sg_words = segment.split()
            n = len(sg_words)
            sg_words = words[word_idx:n+word_idx]
           
            start= None
            idx_start= 0
            while idx_start<len(sg_words):
                if 'start' in sg_words[idx_start]:
                    start = sg_words[idx_start]['start']
                    break
                idx_start +=1
        
            if not start:
                start= 'unknown'
                print (sg_words, start)
            idx_end = len(sg_words)-1
            end=None
            while idx_end>0:
                if 'end' in sg_words[idx_end]:
                    end = sg_words[idx_end]['end']
                    break
                idx_end -=1
            if not end:
                end = start

            
            speakers_ = [x['speaker'] for x in sg_words if 'speaker' in x]
            speaker_id = count_items(speakers_)
            speaker_id = max(speaker_id, key=speaker_id.get)
            dict_ = {'text': segment, 'start': start, 'speaker':speaker_id ,'end': end, 'words': sg_words}
            word_idx +=n
            stt_reconstruction.append(dict_)
        # stt_reconstruction= {'segments': stt_reconstruction}

        return stt_reconstruction

def reconstruction_equalSegments(reconstruction_segments, prediction_segments, SPEAKERS=None,visited_idx=None, diar_idx=None):

    if not visited_idx:
        visited_idx= []
    if not diar_idx:
        diar_idx=[]
    
    for idx_reconstruction in range(len(reconstruction_segments)):
        segment = reconstruction_segments[idx_reconstruction]['text'].strip().lower()
        segment = remove_punctuation(segment)
        speakers=[]
        for idx_sorted in range(len(prediction_segments)):
            speaker_segment = prediction_segments[idx_sorted]['text'].strip().lower()
            speaker_segment = remove_punctuation(speaker_segment)
            if speaker_segment == segment and idx_sorted not in visited_idx:
                
                speakers.append([prediction_segments[idx_sorted]['speaker'], idx_sorted])
        # print (speakers)
        if len(speakers)==1:
            reconstruction_segments[idx_reconstruction]['speaker'] = speakers[0][0]
            # print (idx_reconstruction, speakers[0][0])
            visited_idx.append(speakers[0][1])
    
    for idx in range(len(reconstruction_segments)):
        # print (idx,reconstruction_segments[idx]['speaker'] )
        if reconstruction_segments[idx]['speaker'] in SPEAKERS:
            diar_idx.append(idx)

    # print (diar_idx)
    print ('Reconstruction using equal segments:')
    print (f'{len(visited_idx)} segmentes from predicted were matched with reference segments.This is {100*len(visited_idx)/len(prediction_segments)} % of the predicted segments.')
    print (f'{len(diar_idx)} reference segments have been assigned. This is {100*len(diar_idx)/len(reconstruction_segments)} % of reference segments')
    return reconstruction_segments, visited_idx, diar_idx

def reconstruction_speakerSubstringInSegments(reconstruction_segments, prediction_segments, SPEAKERS=None,visited_idx= None, diar_idx=None):
    if not visited_idx:
        visited_idx= []
    if not diar_idx:
        diar_idx=[]
    
    for idx_reconstruction in range(len(reconstruction_segments)):
        if idx_reconstruction not in diar_idx:
            segment = reconstruction_segments[idx_reconstruction]['text'].strip().lower()
            segment = remove_punctuation(segment)

            speakers=[]
            for idx_sorted in range(len(prediction_segments)):
                if idx_sorted not in visited_idx:
                        speaker_segment = prediction_segments[idx_sorted]['text'].strip().lower()
                        speaker_segment = remove_punctuation(speaker_segment)

                        if speaker_segment in segment:
                            speakers.append([prediction_segments[idx_sorted]['speaker'], idx_sorted])
                
            if len(speakers)==1:
                reconstruction_segments[idx_reconstruction]['speaker'] = speakers[0][0]
                visited_idx.append(speakers[0][1])
                diar_idx.append(idx_reconstruction)
    print ('Reconstruction after speakr substring in reference segments:')
    print (f'{len(visited_idx)} segmentes from predicted were matched with reference segments.This is {100*len(visited_idx)/len(prediction_segments)} % of the predicted segments.')
    print (f'{len(diar_idx)} reference segments have been assigned. This is {100*len(diar_idx)/len(reconstruction_segments)} % of reference segments')
        
    return reconstruction_segments, visited_idx, diar_idx

def reconstruction_segmentSubstringInSpeaker(reconstruction_segments, prediction_segments, SPEAKERS=None,visited_idx= None, diar_idx=None):
    if not visited_idx:
        visited_idx= []
    if not diar_idx:
        diar_idx=[]

    ## third round using substring: segment in speaker_segment
    for idx_reconstruction in range(len(reconstruction_segments)):
        if idx_reconstruction not in diar_idx:
            segment = reconstruction_segments[idx_reconstruction]['text'].strip().lower()
            segment = remove_punctuation(segment)

            speakers=[]
            for idx_sorted in range(len(prediction_segments)):
                if idx_sorted not in visited_idx:
                        speaker_segment = prediction_segments[idx_sorted]['text'].strip().lower()
                        speaker_segment = remove_punctuation(speaker_segment)

                        if segment in speaker_segment:
                            speakers.append([prediction_segments[idx_sorted]['speaker'], idx_sorted])
                
            if len(speakers)==1:
                reconstruction_segments[idx_reconstruction]['speaker'] = speakers[0][0]
                visited_idx.append(speakers[0][1])
                diar_idx.append(idx_reconstruction)

    print ('Reconstruction after substring of reference segments in speaker segment:')
    print (f'{len(visited_idx)} segmentes from predicted were matched with reference segments.This is {100*len(visited_idx)/len(prediction_segments)} % of the predicted segments.')
    print (f'{len(diar_idx)} reference segments have been assigned. This is {100*len(diar_idx)/len(reconstruction_segments)} % of reference segments')
    return reconstruction_segments, visited_idx, diar_idx


def speaker_reconstruction_equalSegments(reconstruction_segments, prediction_segments, SPEAKERS=None,visited_idx=None, diar_idx=None):

    if not visited_idx:
        visited_idx= []
    if not diar_idx:
        diar_idx=[]
    
    for idx_reconstruction in range(len(reconstruction_segments)):
        segment = reconstruction_segments[idx_reconstruction]['text'].strip().lower()
        segment = remove_punctuation(segment)
        for idx_sorted in range(len(prediction_segments)):
            speaker_segment = prediction_segments[idx_sorted]['text'].strip().lower()
            speaker_segment = remove_punctuation(speaker_segment)
            if speaker_segment == segment and idx_sorted not in visited_idx:
                reconstruction_segments[idx_reconstruction]['speaker'] = prediction_segments[0]['speaker']
                visited_idx.append(idx_sorted)
    
    for idx in range(len(reconstruction_segments)):
        if reconstruction_segments[idx]['speaker'] in SPEAKERS:
            diar_idx.append(idx)

    # print (diar_idx)
    print ('Reconstruction using equal segments:')

    print (f'{len(visited_idx)} segmentes from predicted were matched with reference segments.This is {100*len(visited_idx)/len(prediction_segments)} % of the predicted segments.')
    print (f'{len(diar_idx)} reference segments have been assigned. This is {100*len(diar_idx)/len(reconstruction_segments)} % of reference segments')
    return reconstruction_segments, visited_idx, diar_idx


def speaker_reconstruction_longestSubstring(reconstruction_segments, prediction_segments, SPEAKERS=None,visited_idx=None, diar_idx=None):
        if not visited_idx:
            visited_idx= []
        if not diar_idx:
            diar_idx=[]
        

        for idx_reconstruction in range(len(reconstruction_segments)):
            if idx_reconstruction in diar_idx:
                continue 
            segment = reconstruction_segments[idx_reconstruction]['text'].strip().lower()
            segment = remove_punctuation(segment)
            segments_candidate= []
            for idx_sorted in range(len(prediction_segments)):
                speaker_segment = prediction_segments[idx_sorted]['text'].strip().lower()
                speaker_segment = remove_punctuation(speaker_segment)

                substring = longest_common_substring(speaker_segment, segment)
                if len(substring) >1:
                    segments_candidate.append([len(substring),idx_sorted])
         
            if segments_candidate:
                sorted_segments_candidate = sorted(segments_candidate, key=lambda x: x[0], reverse=True)
                reconstruction_segments[idx_reconstruction]['speaker'] = speaker
                visited_idx.append(sorted_segments_candidate[0][1])
                diar_idx.append(idx_reconstruction)
       # print (diar_idx)
        print ('Reconstruction using speaker substring segments:')
        print (f'{len(visited_idx)} segmentes from predicted were matched with reference segments.This is {100*len(visited_idx)/len(prediction_segments)} % of the predicted segments.')

        print (f'{len(diar_idx)} reference segments have been assigned. This is {100*len(diar_idx)/len(reconstruction_segments)} % of reference segments')
        return reconstruction_segments, visited_idx, diar_idx

def unique_common_sequences(text1, text2, min_len=2):
    """
    Find unique consecutive common word sequences between two paragraphs,
    excluding substrings of longer sequences.

    Args:
        text1 (str): First paragraph
        text2 (str): Second paragraph
        min_len (int): Minimum sequence length to consider (default=2)

    Returns:
        list of tuples: (sequence, start_idx_text1, start_idx_text2, length)
    """
    # Tokenize into words
    words1 = text1.split()
    words2 = text2.split()

    n, m = len(words1), len(words2)

    # DP table for longest common suffix
    dp = [[0] * (m + 1) for _ in range(n + 1)]
    matches = []

    for i in range(1, n + 1):
        for j in range(1, m + 1):
            if words1[i-1] == words2[j-1]:
                dp[i][j] = dp[i-1][j-1] + 1
                length = dp[i][j]

                if length >= min_len:
                    seq = words1[i-length:i]
                    matches.append((" ".join(seq), i-length, j-length, length))
            else:
                dp[i][j] = 0

    # Sort matches by sequence length (longest first)
    matches.sort(key=lambda x: x[3], reverse=True)

    # Filter out substrings of larger sequences
    unique_matches = []
    seen_sequences = set()

    for seq, i1, i2, length in matches:
        # Skip if this sequence is already contained in a longer one
        if any(seq in longer for longer in seen_sequences):
            continue
        unique_matches.append((seq, i1, i2, length))
        seen_sequences.add(seq)

    return unique_matches

def get_segment2wordsIdx(segments):
    segmentidx_2words= {}
    word_counter= 0
    for segment_idx in range(len(segments)):
        words = segments[segment_idx]['words']
        words_range = np.arange(word_counter, len(words)+word_counter, 1)
        segmentidx_2words[segment_idx] = words_range
        word_counter += len(words)
    return segmentidx_2words

    
def get_speaker_aware_transcript(sentences_speaker_mapping, f):
    previous_speaker = sentences_speaker_mapping[0]["speaker"]
    start_time = sentences_speaker_mapping[0]['start']
    start_time = time.strftime('%H:%M:%S', time.gmtime(start_time))

    end_time = sentences_speaker_mapping[0]['end']
    end_time = time.strftime('%H:%M:%S', time.gmtime(end_time))

    full_sentence = ""
    last_endTime = end_time

    for sentence_dict in sentences_speaker_mapping:
        # if 'speaker' not in sentence_dict:
        #     speaker = speaker
        #     sentence= sentence_dict['word']
            
        # else:
        speaker = sentence_dict["speaker"]
        sentence = sentence_dict["text"]
        end_time = sentence_dict['end']
        end_time = time.strftime('%H:%M:%S', time.gmtime(end_time))

        # If this speaker doesn't match the previous one, start a new paragraph
        if speaker != previous_speaker:
            f.write(f"\n\n[{start_time}-{last_endTime}] {previous_speaker}: {full_sentence}")
            previous_speaker = speaker
            full_sentence = ""
            start_time = sentence_dict['start']
            start_time = time.strftime('%H:%M:%S', time.gmtime(start_time))

        # No matter what, write the current sentence
        #f.write(sentence + " ")
        full_sentence= full_sentence + sentence + " "
        last_endTime = end_time
    
    f.write(f"\n\n[{start_time}-{last_endTime}] {speaker}: {full_sentence}")

# Configurations

In [7]:
%load_ext autoreload
%autoreload 2
import os
os.environ["TORCH_LOAD_WEIGHTS_ONLY"] = "0"

import torch
import typing,collections
from omegaconf import ListConfig, DictConfig
from omegaconf.base import ContainerMetadata


torch.serialization.add_safe_globals([
    ListConfig,
    DictConfig,
    ContainerMetadata,
    typing.Any,
    list,
    collections.defaultdict,
])

import whisperx
import gc
# import torch 
import whisper_helper as helper
import os
os.environ["PATH"] = '/app/notebooks/ARI_temp/src/whisperx/ffmpeg-7.0.2-amd64-static:' + os.environ["PATH"]
# import evaluate
import time
import copy 
import numpy as np
import wave
import gc
import transformers
print(transformers.__file__)

/usr/local/lib/python3.12/dist-packages/IPython/extensions/autoreload.py:247: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  if not hasattr(module, "__file__") or module.__file__ is None:

AttributeError: module 'torch.serialization' has no attribute 'add_safe_globals'

In [12]:
device = "cuda"
# id_ = 8 
# output_dir = "whisper-transcripts-reconstruction"
# audio_file = "test.wav"
batch_size = 16 # reduce if low on GPU mem
compute_type = "float16"
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True

In [13]:
model = whisperx.load_model("large-v2", device, compute_type=compute_type)

/opt/whisperx-venv/lib/python3.12/site-packages/lightning_fabric/utilities/cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../../opt/whisperx-venv/lib/python3.12/site-packages/whisperx/assets/pytorch_model.bin`

No language specified, language will be first be detected for each audio file (increases inference time).

In [14]:
# ## test
# audio_file_path = '/app/dir_nib483/ARI/Examples/test_script/Case#0/Audio Record/audio Wayne Marasco.wav'
# result = helper.get_speechDiar(model, audio_file_path, device, batch_size=16)

# STT + Diarization

## Composite

In [15]:
project_folder =  f'/app/dir_nib483/ARI/Examples/test_script/Case#1/Audio Record'
project_name= 'Case#1'
output_dir = os.path.join(project_folder, 'output_files')
os.makedirs(output_dir, exist_ok=True)

In [16]:
audio_dir =project_folder

In [17]:
## Create temporal directory for outputs
temporal_dir = os.path.join(project_folder, 'temp')
os.makedirs(temporal_dir, exist_ok=True)

In [18]:
import wave
from pydub import AudioSegment

def create_wav(input_file, output_file):
        sound = AudioSegment.from_file(input_file)
        sound.export(output_file, format="wav")
    
def get_wavfiles(project_dir):
    audio_files = os.listdir(project_dir)
    # new_audio_files = []
    for file_ in audio_files:
        if file_.split('.')[-1] in ['mp4','m4a']:
            input_file = os.path.join(project_dir, file_)
            output_name=  f'{file_.split('.')[0]}.wav'
            output_file = os.path.join(project_dir, output_name)
            create_wav(input_file, output_file)
            print (f'The following file was generated: {output_file}')

get_wavfiles(project_folder)

The following file was generated: /app/dir_nib483/ARI/Examples/test_script/Case#1/Audio Record/compose.wav
The following file was generated: /app/dir_nib483/ARI/Examples/test_script/Case#1/Audio Record/audio_only_16778242_Kristin_Bittinge.wav
The following file was generated: /app/dir_nib483/ARI/Examples/test_script/Case#1/Audio Record/audio_only_16781314_Marsha_Moses.wav
The following file was generated: /app/dir_nib483/ARI/Examples/test_script/Case#1/Audio Record/audio_only_16790530_Zhongcong_Xie.wav
The following file was generated: /app/dir_nib483/ARI/Examples/test_script/Case#1/Audio Record/audio_only_16797698_David_Paul.wav
The following file was generated: /app/dir_nib483/ARI/Examples/test_script/Case#1/Audio Record/audio_only_16806914_Rich_Goldstein.wav
The following file was generated: /app/dir_nib483/ARI/Examples/test_script/Case#1/Audio Record/audio_only_16807938_Allison_Bialas.wav

In [19]:
## 
compose_file = f'compose.wav'
audio_file_path = os.path.join( audio_dir,compose_file)
result = helper.get_speechDiar(model=model, 
                                audio_file_path=audio_file_path,  
                                device=device,
                                batch_size=batch_size)

transcribing ...

/opt/whisperx-venv/lib/python3.12/site-packages/pyannote/audio/utils/reproducibility.py:74: ReproducibilityWarning: TensorFloat-32 (TF32) has been disabled as it might lead to reproducibility issues and lower accuracy.
It can be re-enabled by calling
   >>> import torch
   >>> torch.backends.cuda.matmul.allow_tf32 = True
   >>> torch.backends.cudnn.allow_tf32 = True
See https://github.com/pyannote/pyannote-audio/issues/1370 for more details.

  warnings.warn(

transcription is done!
diarization...

/opt/whisperx-venv/lib/python3.12/site-packages/lightning_fabric/utilities/cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
/opt/whisperx-venv/lib/python3.12/site-packages/pyannote/audio/models/blocks/pooling.py:104: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at ../aten/src/ATen/native/ReduceOps.cpp:1823.)
  std = sequences.std(dim=-1, correction=1)

Congrats! diarization is done

In [20]:
## show some examples
for i in result['segments'][:200]:
    print (f'{i['speaker']}: {i['text']}')

SPEAKER_02:  So I'm Kristen Bittinger.
SPEAKER_02: I'm Chief Integrity Officer at Harvard Medical School.
SPEAKER_02: I'm joined by Rachel Fouchier, the Executive Coordinator at Academic and Research Integrity at Harvard Medical School.
SPEAKER_02: Fariba Humin, the Chief Compliance Officer at Boston Children's Hospital.
SPEAKER_02:  Stephen Cox, Program Manager in Research Integrity at Harvard Medical School.
SPEAKER_02: Aaron Walsh, Program Manager in Research Integrity at Harvard Medical School.
SPEAKER_02: Daniel Wainstock, our Director for Research Integrity at Harvard Medical School.
SPEAKER_02: Heather Quay, Legal Counsel at Harvard University.
SPEAKER_02: Gretchen Brodnicki, Dean for Faculty and Research Integrity and the Research Integrity Officer at Harvard Medical School.
SPEAKER_02:  Mary Walsh, our Chief Scientific Investigator at Harvard Medical School.
SPEAKER_02: Blake Calvert, Scientific Investigator at Harvard Medical School.
SPEAKER_02: Gus Cervini, Vice President for Research Administration at Boston Children's Hospital.
SPEAKER_02: I'm then going to turn it over to Dr. Moses, but I first want to thank you both for joining us today.
SPEAKER_02: And again, the panel knows that you want to make an opening statement, but I'll just let Dr. Moses introduce herself and the panel members introduce themselves first.
SPEAKER_02:  Thank you.
SPEAKER_03: Thanks, Kristen.
SPEAKER_03: Dr. Bialis, we're just going to quickly introduce ourselves, have you guys introduce yourselves, and then we can begin the conversation.
SPEAKER_03: So as you know, I'm Marcia Moses.
SPEAKER_03: I'm the director of the Vascular Biology Program at Boston Children's Hospital, and I'm on the faculty at HMS.
SPEAKER_01:  Hi, I'm David Paul.
SPEAKER_01: I'm a professor of neurobiology in the Department of Neurobiology on the Quadrangle.
SPEAKER_04: Hi, I'm Tung-Tung Hsieh.
SPEAKER_04: I'm the professor of anesthesia, and I'm working at the Mass General Hospital.
SPEAKER_00: Hi, thank you.
SPEAKER_00: So I'm Allison Bialas, and my lawyer, Richard Goldstein, is also on the call.
SPEAKER_01: Hello, everyone.
SPEAKER_01: Hello.
SPEAKER_03:  Um, so I understand you're right.
SPEAKER_03: You want to make make a statement and we're happy to hear that.
SPEAKER_03: So it's all yours.
SPEAKER_00: Okay, thank you.
SPEAKER_00: So first of all, I just want to thank you all for taking time to meet with me today.
SPEAKER_00: And for all the time you're having to spend on reviewing my case.
SPEAKER_00: For my statement today, I won't spend time going through each allegation.
SPEAKER_00: I have already written a lot.
SPEAKER_00:  I prepared a lengthy stipulation covering the errors, the errors I knew about in all four of the publications.
SPEAKER_00: I'm not aware of any other errors in those publications.
SPEAKER_00: I submitted an admission, additional statements to the inquiry committee, and I've met with staff on numerous occasions.
SPEAKER_00: I've also submitted documents to Dr. Stevens detailing the locations of all the data and analysis I could find, along with several options for work that could be done to correct the paper.
SPEAKER_00:  I worked closely with Dr. Carroll for several months to find data, review the data and rerun experiments.
SPEAKER_00: And I answered any questions you had associated with my work.
SPEAKER_00: Hopefully you all had access to all of that.
SPEAKER_00: I reviewed these items for this interview and I will do my best to answer questions you have about them.
SPEAKER_00: This has been a very long, very hard two and a half years.
SPEAKER_00: The last thing I wanted to do was to have to come before you today.
SPEAKER_00:  For me, finding the words to express how truly sorry I am feels impossible, and saying anything to defend myself feels unfair to Dr. Stephens and Dr. Carroll.
SPEAKER_00: But given all the time you have spent dealing with this, I wanted you to have a chance to meet me and to get an introduction to who I am and a sense of my state of mind during the time when I was working in the Stephens lab and in the later years in the Carroll lab.
SPEAKER_00: Then if you have questions about specific allegations,
SPEAKER_00:  I'll try to answer them.
SPEAKER_00: So first of all, I want to start by telling you that my education has always been one of the most important things in my life.
SPEAKER_00: Before I came to Harvard, I had many scholastic achievements, of which I was very proud.
SPEAKER_00: I was valedictorian of my high school class.
SPEAKER_00: I graduated from Cornell with a 4.0.
SPEAKER_00: I had never been anything other than a great student who loved learning and solving problems.
SPEAKER_00:  I'm sorry, this is what drew me to academic research.
SPEAKER_00: I came to graduate school directly after college with undergraduate experience in a Drosophila neuroscience lab and summer internships in immunology labs and at a biotech company.
SPEAKER_00: I had never worked on the kind of multi-year project where it was necessary to combine data collected over a long period into a coherent story.
SPEAKER_00: I had never published a paper.
SPEAKER_00:  I admit that I made these errors and mistakes, which I spelled out in the stipulation.
SPEAKER_00: I wish that I had caught these errors.
SPEAKER_00: There may be other errors that I'm not aware of.
SPEAKER_00: Should my superiors and co-authors have caught these errors, maybe.
SPEAKER_00: It's not for me to judge, that's your job.
SPEAKER_00: Many of the errors occurred when I was a grad student in a brand new, very small lab.
SPEAKER_00: When I started,
SPEAKER_00:  The Stevens Lab did not have set protocols in terms of data management and record keeping, and I was inexperienced with these kinds of things.
SPEAKER_00: It was the kind of scenario where I didn't even know all the things that I didn't know.
SPEAKER_00: There's a lot more than I thought required to correctly assemble a manuscript.
SPEAKER_00: Dr. Stevens and I met regularly, but our discussions usually centered around the fun stuff, what experiments were needed to move projects forward.
SPEAKER_00:  Dr. Stephens and I changed the goals of my project, the flow of the data, and the most important experiments for me to focus on very frequently, at times weekly or even daily, to try to come up with the most compelling way to tell the story of my project.
SPEAKER_00: I had dozens of figure outlines, some of which had placeholder figures, some with more complete figures, and I think in some cases,
SPEAKER_00:  That may have been how I got confused with the ends and had some of the groups having N equals six and some only having N equals three.
SPEAKER_00: Errors can propagate when you've been through a process, when you've never been through a process before and you don't realize what documents you generate along the way will ultimately feed into your final product.
SPEAKER_00: I think some consideration has to be given for my very junior status at the time and the lab environment I was in.
SPEAKER_00: I was in training.
SPEAKER_00: I was not an experienced scientist.
SPEAKER_00:  but I was a very enthusiastic and perhaps too enthusiastic student.
SPEAKER_00: I never said no to any opportunity to learn something new or to help someone out, and I quickly became overcommitted.
SPEAKER_00: Also, the lab grew relatively quickly.
SPEAKER_00: Despite my inexperience, I became a senior member of the lab within a few months of starting there in 2008, when I was still a first year graduate student.
SPEAKER_00: As the years went by, especially around the time when I was preparing my thesis and the nature neuroscience paper,
SPEAKER_00:  I rarely had quiet time when I was preparing, or I rarely had quiet time to sit at my desk, think about my project, and review my work.
SPEAKER_00: I felt as though I was constantly being interrupted by someone who needed me for something.
SPEAKER_00: For that reason, I ended up writing most of my thesis at home after lab, working late into the night, a time when no one is really at their best.
SPEAKER_00: On top of that, I often had issues accessing data and programs through the VPN
SPEAKER_00:  and would have to go back into lab for that.
SPEAKER_00: So basically my analysis, writing, and figure making were more often than not occurring in fits and spurts.
SPEAKER_00: I always tried my best, but the cards were stacked against me in some ways because of who I am, all the things I chose to take on, and my inability to drown out the noise and focus on the most important parts of being a graduate student.
SPEAKER_00: When working on my thesis and the Nature Neuroscience paper,
SPEAKER_00:  I really tried to be and thought that I was accurate and correct.
SPEAKER_00: I didn't knowingly let errors slip into the papers, but they did.
SPEAKER_00: As I was finishing my thesis and writing my Nature Neuroscience paper, Beth asked me to help with a collaborative project that eventually became the 2016 Nature paper, or the C4 paper, I'll call it sometimes.
SPEAKER_00: I continued working on this project in the Carroll Lab,
SPEAKER_00:  as I started to pursue the separate project that became my 2017 Nature paper.
SPEAKER_00: I mention this just because based on my explanation of the errors in the C4 paper in my stipulation, the inquiry report did not include any kind of misconduct in the C4 paper.
SPEAKER_00: And these data were collected in the Carroll Lab as well.
SPEAKER_00: I freely admit I made errors in my portion of that paper.
SPEAKER_00:  Despite that, my explanation seemed sufficient to show that this mistake was an honest error.
SPEAKER_00: There are other examples of errors in my stipulation that were also not included in the inquiry report as allegations of misconduct.
SPEAKER_00: The point I'm trying to make is that mistakes alone are not evidence of misconduct, even if there are a lot of them.
SPEAKER_00: I don't think, excuse me,
SPEAKER_00:  I don't think you should view the mistakes in the thesis and the nature neuroscience paper as a prelude to the misconduct in the lupus paper because the earlier mistakes occurred when I was in a different place and a very different state of mind.
SPEAKER_00: Starting in the Carroll lab was a very different place than starting in the Stevens lab because it was a well-established lab with standard practices in place.
SPEAKER_00:  One of the common practices was to send Dr. Carroll progress reports each week and to present at lab meeting each week.
SPEAKER_00: Dr. Carroll never expressed any concerns about my work.
SPEAKER_00: However, I was the only neuroscientist in the lab and I was doing many techniques that no one else was doing.
SPEAKER_00: Because of this, I had to be pretty independent.
SPEAKER_00: I relied on my experience in the Stevens Lab, which at the time I thought, you know, was adequate training.
SPEAKER_00:  However, even though I was now working in the Carroll Lab, I kept getting pulled into things with the Stevens Lab.
SPEAKER_00: I was still maintaining a mouse colony there.
SPEAKER_00: I was writing grant progress reports.
SPEAKER_00: I was reviewing papers, continuing experiments, and advising some students.
SPEAKER_00: At times, the stress over maintaining my relationships with my former and current advisor was all-consuming for me because I cared very, very much about not letting anyone down.
SPEAKER_00:  I let myself get overwhelmed, both physically and emotionally, and at a certain point, it just became too much.
SPEAKER_00: After years of increasing pressures and responsibilities, some of which were self-inflicted, I reached a point while in the Carroll Lab, and I've admitted this.
SPEAKER_00: When I was working on the lupus paper, I cut some corners and I made some assumptions that I know were not acceptable.
SPEAKER_00: My initial enthusiasm for science, which I experienced when I was in the Stevens Lab,
SPEAKER_00:  and which I hoped would continue during my postdoc, was replaced by irritability and anxiety.
SPEAKER_00: At many times while I was in the Carroll Lab, I felt so overwhelmed that I just stopped caring about the quality of my work.
SPEAKER_00: Looking back on it, this was new to me.
SPEAKER_00: Unlike the positive excitement I felt when I was in the Stevens Lab, where I tried to do my best, after I had been a postdoc for a couple of years, I just started making impulsive and reckless decisions.
SPEAKER_00:  For example, when I was in the CARE lab, I completely neglected to record anything in my lab notebook to document behavioral characterization I did.
SPEAKER_00: I didn't save the raw data, and I exported the data in such a disorganized way that it was almost guaranteed to cause mix-ups.
SPEAKER_00: I never did anything like that when I was under Dr. Stevens' supervision.
SPEAKER_00: I admit I committed reckless misconduct when it came to my 2017 paper, but I want you to understand
SPEAKER_00:  that my earlier mistakes were of a different kind and quality.
SPEAKER_00: It doesn't make sense to assume that because I committed misconduct on the 2017 paper, that all earlier errors are also misconduct.
SPEAKER_00: I was in a different stage of my training when I was writing the 2017 paper.
SPEAKER_00: I was in a different lab and working on a paper with many collaborators rather than just doing everything myself.
SPEAKER_00: The research issues were different, the projects were separate, and they happened years apart.
SPEAKER_00:  Most importantly, I was in a totally different frame of mind.
SPEAKER_00: I felt I was on the verge of a great career in academia.
SPEAKER_00: I had positive feedback from many of my colleagues all along the way, including Dr. Stevens and Dr. Carroll, that I had what it took to be a PI.
SPEAKER_00: And it's very hard to admit that they were wrong about me and that I was wrong about myself.
SPEAKER_00: And over the past couple of years during this process,
SPEAKER_00:  I've done a lot of soul searching to try to have a better grasp of what happened so I can make sure that it never happens again.
SPEAKER_00: And with the help of medical professionals, I've realized some things about myself that weren't apparent to me when I was working on my graduate and postdoc projects that kind of set me up to fail from early on.
SPEAKER_00: Others may have seen it, but I didn't.
SPEAKER_00: I guess it's stating the obvious to say that I am poorly suited to the type of environment I found myself in.
SPEAKER_00:  During my training, I can be a very enthusiastic and energetic person in bursts.
SPEAKER_00: Every idea sounds super exciting, and I just want to do it all.
SPEAKER_00: With short-term goals, even on a tight deadline, I can usually deliver, and sometimes at a high level of success.
SPEAKER_00: I think I was doing okay, just okay, when I was in the Stevens Lab.
SPEAKER_00: But with longer projects, both personally and professionally,
SPEAKER_00:  I now recognize that my high energy and enthusiasm is not sustained.
SPEAKER_00: I run out of steam and I lose my focus and motivation.
SPEAKER_00: I become overwhelmed when commitments start to pile up.
SPEAKER_00: I make mistakes and I fail to deliver at the same level.
SPEAKER_00: This was especially true in the Carroll lab.
SPEAKER_00: When I felt the stress of the commitments I carried over from the Stevens lab and new pressures from the Carroll lab converging.
SPEAKER_00: I love science.
SPEAKER_00:  I want to be successful, and now that I recognize and I'm addressing my issues with an appropriate support system, I think I still have a lot to offer, and it just won't be as a PI in academic science.
SPEAKER_00: I am very sorry for how this all turned out.
SPEAKER_00: I disappointed a lot of people, and the good reputation I had is gone.
SPEAKER_00: My career as an academic scientist is over.
SPEAKER_00: Paper retractions were deemed necessary, and valuable research resources have been diverted.
SPEAKER_00:  I feel so terrible about all of this, and I will never forgive myself for it.
SPEAKER_00: Dr. Carroll and Dr. Stephens may read this statement, and I don't quite know what to say to them, except that I'm so sorry, and I hope that someday they can understand.
SPEAKER_00: However, these negative outcomes do not change the fact that I never knowingly or intentionally put false or fabricated data in any paper.
SPEAKER_00: I want to be very clear about that.
SPEAKER_00:  When it came to the lupus paper, should I have checked with Dr. Carroll and asked for more help from him and my co-authors?
SPEAKER_00: Absolutely.
SPEAKER_00: If I had made an effort to involve them more and been more open about my struggles, my errors could have been avoided.
SPEAKER_00: I realized that when it came to the Nature Neuroscience paper and my thesis, I would have benefited from asking Dr. Stevens to go over it in painstaking detail.
SPEAKER_00: Should I have insisted that she do this with me?
SPEAKER_00:  Yes, looking back, I'm sure it would have helped, but at the time I really didn't see the problems with my work.
SPEAKER_00: In her testimony to the inquiry committee, Dr. Stephens said she never saw any red flags, and a lot of people read my Nature Neuroscience paper.
SPEAKER_00: None of them saw any problems either, and neither did I. Research misconduct is meant to discipline those who don't care about the truth.
SPEAKER_00: It's not meant to identify those who do care and fail.
SPEAKER_00:  I know and deeply regret that I crossed a line with respect to the 2017 paper.
SPEAKER_00: I ran out of steam and ended up making impulsive, reckless decisions to try to keep up with my commitments.
SPEAKER_00: However, when it came to my thesis, the Nature Neuroscience paper, and the C4 paper, I thought I was as careful and diligent as I could be.
SPEAKER_00: I realize now that my efforts were not sufficient.
SPEAKER_00: No matter how well or poorly I did my job,
SPEAKER_00:  For the projects I worked on in the Stevens Lab and with the C4 paper, I always cared about trying to do my best.
SPEAKER_00: Going through this process has been a wake-up call for me in many ways.
SPEAKER_00: And all I can do is take what I've learned from this process, start over, and do better.
SPEAKER_00: Thank you for your attention.
SPEAKER_00: So now, I guess,
SPEAKER_00:  if you guys have any questions on anything.
SPEAKER_01: I'm curious to hear more about how you interacted with Dr. Stevens, whether
SPEAKER_01:  it was common to have Dr. Stephens look at the raw data.
SPEAKER_01: What sort of procedures did you employ for the review of that kind of material?
SPEAKER_00: So in terms of reviewing the raw data, that didn't really happen.
SPEAKER_00: Dr. Stephens and I would meet and go over the graphs of my work.
SPEAKER_00:  and plan, you know, what other experiments were needed.
SPEAKER_00: But we didn't ever really go over the raw data.
SPEAKER_00: And as she mentioned in her statement, you know, we never had an exit interview even when I left the lab, because we were kind of still working together.
SPEAKER_00: So there was never even a discussion of, you know, where is everything located?
SPEAKER_00: And there was never a discussion that I should, for example, when I'm putting together the manuscript,
SPEAKER_00:  have all the data organized by figure and maybe for other people that was, you know, common sense.
SPEAKER_00: But for me, it's just wasn't the way that, you know, I thought about things.
SPEAKER_00: I just had never been through the process and nobody ever asked to look at that.
SPEAKER_00: So as long as I felt in my head, I knew where things were.
SPEAKER_00: I thought that's all that mattered.
SPEAKER_00: And I thought I did.
SPEAKER_00: I thought I knew where everything was and that I was on top of everything, but clearly I was not.
SPEAKER_01:  So go ahead, doctor.
SPEAKER_04: Dr. Paul, you can finish first.
SPEAKER_01: No, that's fine.

In [21]:
## show some examples
for i in result['segments'][:200]:
    print (f'{i['speaker']}: {i['text']}')

SPEAKER_02:  So I'm Kristen Bittinger.
SPEAKER_02: I'm Chief Integrity Officer at Harvard Medical School.
SPEAKER_02: I'm joined by Rachel Fouchier, the Executive Coordinator at Academic and Research Integrity at Harvard Medical School.
SPEAKER_02: Fariba Humin, the Chief Compliance Officer at Boston Children's Hospital.
SPEAKER_02:  Stephen Cox, Program Manager in Research Integrity at Harvard Medical School.
SPEAKER_02: Aaron Walsh, Program Manager in Research Integrity at Harvard Medical School.
SPEAKER_02: Daniel Wainstock, our Director for Research Integrity at Harvard Medical School.
SPEAKER_02: Heather Quay, Legal Counsel at Harvard University.
SPEAKER_02: Gretchen Brodnicki, Dean for Faculty and Research Integrity and the Research Integrity Officer at Harvard Medical School.
SPEAKER_02:  Mary Walsh, our Chief Scientific Investigator at Harvard Medical School.
SPEAKER_02: Blake Calvert, Scientific Investigator at Harvard Medical School.
SPEAKER_02: Gus Cervini, Vice President for Research Administration at Boston Children's Hospital.
SPEAKER_02: I'm then going to turn it over to Dr. Moses, but I first want to thank you both for joining us today.
SPEAKER_02: And again, the panel knows that you want to make an opening statement, but I'll just let Dr. Moses introduce herself and the panel members introduce themselves first.
SPEAKER_02:  Thank you.
SPEAKER_03: Thanks, Kristen.
SPEAKER_03: Dr. Bialis, we're just going to quickly introduce ourselves, have you guys introduce yourselves, and then we can begin the conversation.
SPEAKER_03: So as you know, I'm Marcia Moses.
SPEAKER_03: I'm the director of the Vascular Biology Program at Boston Children's Hospital, and I'm on the faculty at HMS.
SPEAKER_01:  Hi, I'm David Paul.
SPEAKER_01: I'm a professor of neurobiology in the Department of Neurobiology on the Quadrangle.
SPEAKER_04: Hi, I'm Tung-Tung Hsieh.
SPEAKER_04: I'm the professor of anesthesia, and I'm working at the Mass General Hospital.
SPEAKER_00: Hi, thank you.
SPEAKER_00: So I'm Allison Bialas, and my lawyer, Richard Goldstein, is also on the call.
SPEAKER_01: Hello, everyone.
SPEAKER_01: Hello.
SPEAKER_03:  Um, so I understand you're right.
SPEAKER_03: You want to make make a statement and we're happy to hear that.
SPEAKER_03: So it's all yours.
SPEAKER_00: Okay, thank you.
SPEAKER_00: So first of all, I just want to thank you all for taking time to meet with me today.
SPEAKER_00: And for all the time you're having to spend on reviewing my case.
SPEAKER_00: For my statement today, I won't spend time going through each allegation.
SPEAKER_00: I have already written a lot.
SPEAKER_00:  I prepared a lengthy stipulation covering the errors, the errors I knew about in all four of the publications.
SPEAKER_00: I'm not aware of any other errors in those publications.
SPEAKER_00: I submitted an admission, additional statements to the inquiry committee, and I've met with staff on numerous occasions.
SPEAKER_00: I've also submitted documents to Dr. Stevens detailing the locations of all the data and analysis I could find, along with several options for work that could be done to correct the paper.
SPEAKER_00:  I worked closely with Dr. Carroll for several months to find data, review the data and rerun experiments.
SPEAKER_00: And I answered any questions you had associated with my work.
SPEAKER_00: Hopefully you all had access to all of that.
SPEAKER_00: I reviewed these items for this interview and I will do my best to answer questions you have about them.
SPEAKER_00: This has been a very long, very hard two and a half years.
SPEAKER_00: The last thing I wanted to do was to have to come before you today.
SPEAKER_00:  For me, finding the words to express how truly sorry I am feels impossible, and saying anything to defend myself feels unfair to Dr. Stephens and Dr. Carroll.
SPEAKER_00: But given all the time you have spent dealing with this, I wanted you to have a chance to meet me and to get an introduction to who I am and a sense of my state of mind during the time when I was working in the Stephens lab and in the later years in the Carroll lab.
SPEAKER_00: Then if you have questions about specific allegations,
SPEAKER_00:  I'll try to answer them.
SPEAKER_00: So first of all, I want to start by telling you that my education has always been one of the most important things in my life.
SPEAKER_00: Before I came to Harvard, I had many scholastic achievements, of which I was very proud.
SPEAKER_00: I was valedictorian of my high school class.
SPEAKER_00: I graduated from Cornell with a 4.0.
SPEAKER_00: I had never been anything other than a great student who loved learning and solving problems.
SPEAKER_00:  I'm sorry, this is what drew me to academic research.
SPEAKER_00: I came to graduate school directly after college with undergraduate experience in a Drosophila neuroscience lab and summer internships in immunology labs and at a biotech company.
SPEAKER_00: I had never worked on the kind of multi-year project where it was necessary to combine data collected over a long period into a coherent story.
SPEAKER_00: I had never published a paper.
SPEAKER_00:  I admit that I made these errors and mistakes, which I spelled out in the stipulation.
SPEAKER_00: I wish that I had caught these errors.
SPEAKER_00: There may be other errors that I'm not aware of.
SPEAKER_00: Should my superiors and co-authors have caught these errors, maybe.
SPEAKER_00: It's not for me to judge, that's your job.
SPEAKER_00: Many of the errors occurred when I was a grad student in a brand new, very small lab.
SPEAKER_00: When I started,
SPEAKER_00:  The Stevens Lab did not have set protocols in terms of data management and record keeping, and I was inexperienced with these kinds of things.
SPEAKER_00: It was the kind of scenario where I didn't even know all the things that I didn't know.
SPEAKER_00: There's a lot more than I thought required to correctly assemble a manuscript.
SPEAKER_00: Dr. Stevens and I met regularly, but our discussions usually centered around the fun stuff, what experiments were needed to move projects forward.
SPEAKER_00:  Dr. Stephens and I changed the goals of my project, the flow of the data, and the most important experiments for me to focus on very frequently, at times weekly or even daily, to try to come up with the most compelling way to tell the story of my project.
SPEAKER_00: I had dozens of figure outlines, some of which had placeholder figures, some with more complete figures, and I think in some cases,
SPEAKER_00:  That may have been how I got confused with the ends and had some of the groups having N equals six and some only having N equals three.
SPEAKER_00: Errors can propagate when you've been through a process, when you've never been through a process before and you don't realize what documents you generate along the way will ultimately feed into your final product.
SPEAKER_00: I think some consideration has to be given for my very junior status at the time and the lab environment I was in.
SPEAKER_00: I was in training.
SPEAKER_00: I was not an experienced scientist.
SPEAKER_00:  but I was a very enthusiastic and perhaps too enthusiastic student.
SPEAKER_00: I never said no to any opportunity to learn something new or to help someone out, and I quickly became overcommitted.
SPEAKER_00: Also, the lab grew relatively quickly.
SPEAKER_00: Despite my inexperience, I became a senior member of the lab within a few months of starting there in 2008, when I was still a first year graduate student.
SPEAKER_00: As the years went by, especially around the time when I was preparing my thesis and the nature neuroscience paper,
SPEAKER_00:  I rarely had quiet time when I was preparing, or I rarely had quiet time to sit at my desk, think about my project, and review my work.
SPEAKER_00: I felt as though I was constantly being interrupted by someone who needed me for something.
SPEAKER_00: For that reason, I ended up writing most of my thesis at home after lab, working late into the night, a time when no one is really at their best.
SPEAKER_00: On top of that, I often had issues accessing data and programs through the VPN
SPEAKER_00:  and would have to go back into lab for that.
SPEAKER_00: So basically my analysis, writing, and figure making were more often than not occurring in fits and spurts.
SPEAKER_00: I always tried my best, but the cards were stacked against me in some ways because of who I am, all the things I chose to take on, and my inability to drown out the noise and focus on the most important parts of being a graduate student.
SPEAKER_00: When working on my thesis and the Nature Neuroscience paper,
SPEAKER_00:  I really tried to be and thought that I was accurate and correct.
SPEAKER_00: I didn't knowingly let errors slip into the papers, but they did.
SPEAKER_00: As I was finishing my thesis and writing my Nature Neuroscience paper, Beth asked me to help with a collaborative project that eventually became the 2016 Nature paper, or the C4 paper, I'll call it sometimes.
SPEAKER_00: I continued working on this project in the Carroll Lab,
SPEAKER_00:  as I started to pursue the separate project that became my 2017 Nature paper.
SPEAKER_00: I mention this just because based on my explanation of the errors in the C4 paper in my stipulation, the inquiry report did not include any kind of misconduct in the C4 paper.
SPEAKER_00: And these data were collected in the Carroll Lab as well.
SPEAKER_00: I freely admit I made errors in my portion of that paper.
SPEAKER_00:  Despite that, my explanation seemed sufficient to show that this mistake was an honest error.
SPEAKER_00: There are other examples of errors in my stipulation that were also not included in the inquiry report as allegations of misconduct.
SPEAKER_00: The point I'm trying to make is that mistakes alone are not evidence of misconduct, even if there are a lot of them.
SPEAKER_00: I don't think, excuse me,
SPEAKER_00:  I don't think you should view the mistakes in the thesis and the nature neuroscience paper as a prelude to the misconduct in the lupus paper because the earlier mistakes occurred when I was in a different place and a very different state of mind.
SPEAKER_00: Starting in the Carroll lab was a very different place than starting in the Stevens lab because it was a well-established lab with standard practices in place.
SPEAKER_00:  One of the common practices was to send Dr. Carroll progress reports each week and to present at lab meeting each week.
SPEAKER_00: Dr. Carroll never expressed any concerns about my work.
SPEAKER_00: However, I was the only neuroscientist in the lab and I was doing many techniques that no one else was doing.
SPEAKER_00: Because of this, I had to be pretty independent.
SPEAKER_00: I relied on my experience in the Stevens Lab, which at the time I thought, you know, was adequate training.
SPEAKER_00:  However, even though I was now working in the Carroll Lab, I kept getting pulled into things with the Stevens Lab.
SPEAKER_00: I was still maintaining a mouse colony there.
SPEAKER_00: I was writing grant progress reports.
SPEAKER_00: I was reviewing papers, continuing experiments, and advising some students.
SPEAKER_00: At times, the stress over maintaining my relationships with my former and current advisor was all-consuming for me because I cared very, very much about not letting anyone down.
SPEAKER_00:  I let myself get overwhelmed, both physically and emotionally, and at a certain point, it just became too much.
SPEAKER_00: After years of increasing pressures and responsibilities, some of which were self-inflicted, I reached a point while in the Carroll Lab, and I've admitted this.
SPEAKER_00: When I was working on the lupus paper, I cut some corners and I made some assumptions that I know were not acceptable.
SPEAKER_00: My initial enthusiasm for science, which I experienced when I was in the Stevens Lab,
SPEAKER_00:  and which I hoped would continue during my postdoc, was replaced by irritability and anxiety.
SPEAKER_00: At many times while I was in the Carroll Lab, I felt so overwhelmed that I just stopped caring about the quality of my work.
SPEAKER_00: Looking back on it, this was new to me.
SPEAKER_00: Unlike the positive excitement I felt when I was in the Stevens Lab, where I tried to do my best, after I had been a postdoc for a couple of years, I just started making impulsive and reckless decisions.
SPEAKER_00:  For example, when I was in the CARE lab, I completely neglected to record anything in my lab notebook to document behavioral characterization I did.
SPEAKER_00: I didn't save the raw data, and I exported the data in such a disorganized way that it was almost guaranteed to cause mix-ups.
SPEAKER_00: I never did anything like that when I was under Dr. Stevens' supervision.
SPEAKER_00: I admit I committed reckless misconduct when it came to my 2017 paper, but I want you to understand
SPEAKER_00:  that my earlier mistakes were of a different kind and quality.
SPEAKER_00: It doesn't make sense to assume that because I committed misconduct on the 2017 paper, that all earlier errors are also misconduct.
SPEAKER_00: I was in a different stage of my training when I was writing the 2017 paper.
SPEAKER_00: I was in a different lab and working on a paper with many collaborators rather than just doing everything myself.
SPEAKER_00: The research issues were different, the projects were separate, and they happened years apart.
SPEAKER_00:  Most importantly, I was in a totally different frame of mind.
SPEAKER_00: I felt I was on the verge of a great career in academia.
SPEAKER_00: I had positive feedback from many of my colleagues all along the way, including Dr. Stevens and Dr. Carroll, that I had what it took to be a PI.
SPEAKER_00: And it's very hard to admit that they were wrong about me and that I was wrong about myself.
SPEAKER_00: And over the past couple of years during this process,
SPEAKER_00:  I've done a lot of soul searching to try to have a better grasp of what happened so I can make sure that it never happens again.
SPEAKER_00: And with the help of medical professionals, I've realized some things about myself that weren't apparent to me when I was working on my graduate and postdoc projects that kind of set me up to fail from early on.
SPEAKER_00: Others may have seen it, but I didn't.
SPEAKER_00: I guess it's stating the obvious to say that I am poorly suited to the type of environment I found myself in.
SPEAKER_00:  During my training, I can be a very enthusiastic and energetic person in bursts.
SPEAKER_00: Every idea sounds super exciting, and I just want to do it all.
SPEAKER_00: With short-term goals, even on a tight deadline, I can usually deliver, and sometimes at a high level of success.
SPEAKER_00: I think I was doing okay, just okay, when I was in the Stevens Lab.
SPEAKER_00: But with longer projects, both personally and professionally,
SPEAKER_00:  I now recognize that my high energy and enthusiasm is not sustained.
SPEAKER_00: I run out of steam and I lose my focus and motivation.
SPEAKER_00: I become overwhelmed when commitments start to pile up.
SPEAKER_00: I make mistakes and I fail to deliver at the same level.
SPEAKER_00: This was especially true in the Carroll lab.
SPEAKER_00: When I felt the stress of the commitments I carried over from the Stevens lab and new pressures from the Carroll lab converging.
SPEAKER_00: I love science.
SPEAKER_00:  I want to be successful, and now that I recognize and I'm addressing my issues with an appropriate support system, I think I still have a lot to offer, and it just won't be as a PI in academic science.
SPEAKER_00: I am very sorry for how this all turned out.
SPEAKER_00: I disappointed a lot of people, and the good reputation I had is gone.
SPEAKER_00: My career as an academic scientist is over.
SPEAKER_00: Paper retractions were deemed necessary, and valuable research resources have been diverted.
SPEAKER_00:  I feel so terrible about all of this, and I will never forgive myself for it.
SPEAKER_00: Dr. Carroll and Dr. Stephens may read this statement, and I don't quite know what to say to them, except that I'm so sorry, and I hope that someday they can understand.
SPEAKER_00: However, these negative outcomes do not change the fact that I never knowingly or intentionally put false or fabricated data in any paper.
SPEAKER_00: I want to be very clear about that.
SPEAKER_00:  When it came to the lupus paper, should I have checked with Dr. Carroll and asked for more help from him and my co-authors?
SPEAKER_00: Absolutely.
SPEAKER_00: If I had made an effort to involve them more and been more open about my struggles, my errors could have been avoided.
SPEAKER_00: I realized that when it came to the Nature Neuroscience paper and my thesis, I would have benefited from asking Dr. Stevens to go over it in painstaking detail.
SPEAKER_00: Should I have insisted that she do this with me?
SPEAKER_00:  Yes, looking back, I'm sure it would have helped, but at the time I really didn't see the problems with my work.
SPEAKER_00: In her testimony to the inquiry committee, Dr. Stephens said she never saw any red flags, and a lot of people read my Nature Neuroscience paper.
SPEAKER_00: None of them saw any problems either, and neither did I. Research misconduct is meant to discipline those who don't care about the truth.
SPEAKER_00: It's not meant to identify those who do care and fail.
SPEAKER_00:  I know and deeply regret that I crossed a line with respect to the 2017 paper.
SPEAKER_00: I ran out of steam and ended up making impulsive, reckless decisions to try to keep up with my commitments.
SPEAKER_00: However, when it came to my thesis, the Nature Neuroscience paper, and the C4 paper, I thought I was as careful and diligent as I could be.
SPEAKER_00: I realize now that my efforts were not sufficient.
SPEAKER_00: No matter how well or poorly I did my job,
SPEAKER_00:  For the projects I worked on in the Stevens Lab and with the C4 paper, I always cared about trying to do my best.
SPEAKER_00: Going through this process has been a wake-up call for me in many ways.
SPEAKER_00: And all I can do is take what I've learned from this process, start over, and do better.
SPEAKER_00: Thank you for your attention.
SPEAKER_00: So now, I guess,
SPEAKER_00:  if you guys have any questions on anything.
SPEAKER_01: I'm curious to hear more about how you interacted with Dr. Stevens, whether
SPEAKER_01:  it was common to have Dr. Stephens look at the raw data.
SPEAKER_01: What sort of procedures did you employ for the review of that kind of material?
SPEAKER_00: So in terms of reviewing the raw data, that didn't really happen.
SPEAKER_00: Dr. Stephens and I would meet and go over the graphs of my work.
SPEAKER_00:  and plan, you know, what other experiments were needed.
SPEAKER_00: But we didn't ever really go over the raw data.
SPEAKER_00: And as she mentioned in her statement, you know, we never had an exit interview even when I left the lab, because we were kind of still working together.
SPEAKER_00: So there was never even a discussion of, you know, where is everything located?
SPEAKER_00: And there was never a discussion that I should, for example, when I'm putting together the manuscript,
SPEAKER_00:  have all the data organized by figure and maybe for other people that was, you know, common sense.
SPEAKER_00: But for me, it's just wasn't the way that, you know, I thought about things.
SPEAKER_00: I just had never been through the process and nobody ever asked to look at that.
SPEAKER_00: So as long as I felt in my head, I knew where things were.
SPEAKER_00: I thought that's all that mattered.
SPEAKER_00: And I thought I did.
SPEAKER_00: I thought I knew where everything was and that I was on top of everything, but clearly I was not.
SPEAKER_01:  So go ahead, doctor.
SPEAKER_04: Dr. Paul, you can finish first.
SPEAKER_01: No, that's fine.

In [22]:
## fix sgment with missing components 
for segment in result['segments']:
    last_start= segment['start']
    last_end = segment['end']
    if 'speaker' not in segment:
        segment['speaker'] = 'SPEAKER_10'
        
    for word in segment['words']:
        if 'speaker' not in word:
            word['speaker'] = segment['speaker']
            
        if 'end' in word:
            last_end = word['end']
        else:
            word['end'] = last_end

        if 'start' in word:
            last_start = word['start']
        else:
            word['start'] = last_start

In [23]:
# Export whisperx diarization
import copy

output_file_name = os.path.join(temporal_dir, f'whisperx_{project_name}.text')
result_edited = copy.deepcopy(result)
result_edited = helper.fix_result_format(result_edited)

# ### fix diarization
result_edited  = helper.fix_diar(result_edited)

with open( output_file_name, "w", encoding="utf-8-sig") as f:
    helper.get_speaker_aware_transcript(result_edited, f)

In [24]:
master_result =copy.deepcopy(result)
# result_reconstruction = result.copy()

In [25]:
torch.cuda.empty_cache()

In [26]:
gc.collect()

128

In [27]:
output_file_name

'/app/dir_nib483/ARI/Examples/test_script/Case#1/Audio Record/temp/whisperx_Case#1.text'

## Individual Audio

In [28]:
audio_files = os.listdir(audio_dir)
audio_files = [i for i in audio_files if '.wav' in i ]
## remove master
compose_name = compose_file.split('.')[0]
audio_files = [ i for i in audio_files if i.split('.')[0] != compose_name]
audio_files.sort()
audio_files,len(audio_files)

(['audio_only_16778242_Kristin_Bittinge.wav',
  'audio_only_16781314_Marsha_Moses.wav',
  'audio_only_16790530_Zhongcong_Xie.wav',
  'audio_only_16797698_David_Paul.wav',
  'audio_only_16806914_Rich_Goldstein.wav',
  'audio_only_16807938_Allison_Bialas.wav'],
 6)

In [29]:

# def merge_audio_files(audio_files, output_file):
#     with wave.open(audio_files[0], 'rb') as w:
#         params = w.getparams()
#         frames = w.readframes(w.getnframes())

#     # Append frames from the rest of the files
#     for file in audio_files[1:]:
#         with wave.open(file, 'rb') as w:
#             frames += w.readframes(w.getnframes())
    
#     # Write to output
#     with wave.open(output_file, 'wb') as out:
#         out.setparams(params)
#         out.writeframes(frames)

# audio_dir = f'/app/dir_nib483/ARI/Examples/Example {id_}/Audio Record'
# audio_files = os.listdir(audio_dir)
# audio_files = [i for i in audio_files if '.wav' in i ]
# names = [ i.split('_')[-1].replace('.wav','') for i in audio_files]
# names.sort()
# names  = list(set(names))


# audio_files_person= {}
# for name in names:
#     audio_files_person[name]=[]
#     for file_ in audio_files:
#         if name in file_:
#             file_path = os.path.join(audio_dir, file_)
#             audio_files_person[name].append(file_path)
#     audio_files_person[name].sort()


# display(audio_files_person)
# for person in audio_files_person:
#     audio_files = audio_files_person[person]
#     output_file = os.path.join(audio_dir,f'{person}.wav')
#     merge_audio_files(audio_files, output_file)
#     print (f'{person} file has been saved at {output_file}')
#     # Open first file to get parameters
# names

In [30]:
## 
speaker_stt={}
# audio_files = os.listdir(audio_dir)
# audio_files = [i for i in audio_files if '.wav' in i ]
# audio_files = [i for i in audio_files if '_' not in i ]
for audio_file in audio_files:
        audio_file_path = os.path.join(audio_dir, audio_file)
        result = helper.get_speechDiar(model=model, 
                                        audio_file_path=audio_file_path,  
                                        device=device,
                                        batch_size=batch_size)
        
        gc.collect()

        torch.cuda.empty_cache()
        speaker_name = audio_file.replace('audio_only_','')
        speaker_name = speaker_name.replace('audio','')
        speaker_name = speaker_name.replace('_',' ')
        speaker_name = speaker_name.strip()

        speaker_name = speaker_name.replace('.wav','')
        speaker_name = speaker_name.title()
        speaker_stt[speaker_name] = result.copy()

transcribing ...
transcription is done!
diarization...

/opt/whisperx-venv/lib/python3.12/site-packages/lightning_fabric/utilities/cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
/opt/whisperx-venv/lib/python3.12/site-packages/pyannote/audio/models/blocks/pooling.py:104: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at ../aten/src/ATen/native/ReduceOps.cpp:1823.)
  std = sequences.std(dim=-1, correction=1)

Congrats! diarization is done
transcribing ...
transcription is done!
diarization...

/opt/whisperx-venv/lib/python3.12/site-packages/lightning_fabric/utilities/cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
/opt/whisperx-venv/lib/python3.12/site-packages/pyannote/audio/models/blocks/pooling.py:104: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at ../aten/src/ATen/native/ReduceOps.cpp:1823.)
  std = sequences.std(dim=-1, correction=1)

Congrats! diarization is done
transcribing ...
transcription is done!
Failed to align segment (" Thanks for watching!"): backtrack failed, resorting to original...
diarization...

/opt/whisperx-venv/lib/python3.12/site-packages/lightning_fabric/utilities/cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
/opt/whisperx-venv/lib/python3.12/site-packages/pyannote/audio/models/blocks/pooling.py:104: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at ../aten/src/ATen/native/ReduceOps.cpp:1823.)
  std = sequences.std(dim=-1, correction=1)

Congrats! diarization is done
transcribing ...
transcription is done!
Failed to align segment (" Subs by www.zeoranger.co.uk"): backtrack failed, resorting to original...
diarization...

/opt/whisperx-venv/lib/python3.12/site-packages/lightning_fabric/utilities/cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
/opt/whisperx-venv/lib/python3.12/site-packages/pyannote/audio/models/blocks/pooling.py:104: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at ../aten/src/ATen/native/ReduceOps.cpp:1823.)
  std = sequences.std(dim=-1, correction=1)

Congrats! diarization is done
transcribing ...
transcription is done!
Failed to align segment (" Thank you for watching."): backtrack failed, resorting to original...
diarization...

/opt/whisperx-venv/lib/python3.12/site-packages/lightning_fabric/utilities/cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
/opt/whisperx-venv/lib/python3.12/site-packages/pyannote/audio/models/blocks/pooling.py:104: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at ../aten/src/ATen/native/ReduceOps.cpp:1823.)
  std = sequences.std(dim=-1, correction=1)

Congrats! diarization is done
transcribing ...
transcription is done!
diarization...

/opt/whisperx-venv/lib/python3.12/site-packages/lightning_fabric/utilities/cloud_io.py:73: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
/opt/whisperx-venv/lib/python3.12/site-packages/pyannote/audio/models/blocks/pooling.py:104: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at ../aten/src/ATen/native/ReduceOps.cpp:1823.)
  std = sequences.std(dim=-1, correction=1)

Congrats! diarization is done

In [31]:
## clean empty speakers
for speaker in list(speaker_stt.keys()):
    if len(speaker_stt[speaker]['segments']) == 0:
        print (f'{speaker} speaker was deleted. No speech was found')
        del speaker_stt[speaker]

In [32]:
speaker_stt.keys(), len(speaker_stt.keys())

(dict_keys(['16778242 Kristin Bittinge', '16781314 Marsha Moses', '16790530 Zhongcong Xie', '16797698 David Paul', '16806914 Rich Goldstein', '16807938 Allison Bialas']),
 6)

In [33]:
import copy 
backup=  copy.deepcopy(speaker_stt)
# speaker_stt = copy.deepcopy(backup)

In [34]:
## change speaker_names to segments/words
for speaker in speaker_stt:
    print (speaker)
    dict_ = speaker_stt[speaker].copy()
    new_segments=[]
    for segment in dict_['segments']:  
        new_list_words=[]
        for word_dict in segment['words']:
            word_dict['speaker'] = speaker
            new_list_words.append(word_dict)
        segment['words']= new_list_words
        segment['speaker'] = speaker
        new_segments.append(segment)
    dict_['segments'] = new_segments
    speaker_stt[speaker]= dict_

16778242 Kristin Bittinge
16781314 Marsha Moses
16790530 Zhongcong Xie
16797698 David Paul
16806914 Rich Goldstein
16807938 Allison Bialas

In [35]:
SPEAKERS = list(speaker_stt.keys())
SPEAKERS

['16778242 Kristin Bittinge',
 '16781314 Marsha Moses',
 '16790530 Zhongcong Xie',
 '16797698 David Paul',
 '16806914 Rich Goldstein',
 '16807938 Allison Bialas']

In [36]:
## show some examples
for i in speaker_stt['16781314 Marsha Moses']['segments'][:200]:
    print (f'{i['speaker']}: {i['text']}')

16781314 Marsha Moses:  Thanks, Kristen.
16781314 Marsha Moses: Dr. Bialis, we're just going to quickly introduce ourselves, have you guys introduce yourselves, and then we can begin the conversation.
16781314 Marsha Moses: So as you know, I'm Marcia Moses.
16781314 Marsha Moses: I'm the director of the Vascular Biology Program at Boston Children's Hospital, and I'm on the faculty at HMS.
16781314 Marsha Moses:  Hello.
16781314 Marsha Moses: So this is D'Andrea Wright.
16781314 Marsha Moses: You want to make a statement, and we're happy to hear that.
16781314 Marsha Moses: So it's all yours.
16781314 Marsha Moses:  Thank you.
16781314 Marsha Moses:  Hi, Dr. Bialis.
16781314 Marsha Moses: Let me first ask a question about your time in the Stevens Lab.
16781314 Marsha Moses: So you said that you and Dr. Stevens never looked at raw data together.
16781314 Marsha Moses: Is it that you never proffered it or that you were never asked?
16781314 Marsha Moses:  But when you were initially in the lab, it was a tiny lab, right?
16781314 Marsha Moses:  Now, you just mentioned that when you got to the CARA lab, that it was, I think, easier words, a very well-established lab, from the Stevens lab, when you were in the Stevens lab, and that you had to submit weekly updates.
16781314 Marsha Moses: And then you talked about, you know, by the time you were working on the lupus paper,
16781314 Marsha Moses:  you kind of had stopped caring for a variety of reasons.
16781314 Marsha Moses: But you were still writing those weekly updates on that data during the time?
16781314 Marsha Moses:  And those reports were were data.
16781314 Marsha Moses:  Thank you.
16781314 Marsha Moses:  Bye.
16781314 Marsha Moses:  Go ahead, go ahead.
16781314 Marsha Moses:  Thank you.
16781314 Marsha Moses: So Allison, can you just walk us through how you wrote the Nature Neuroscience paper?
16781314 Marsha Moses:  Yes, thank you.
16781314 Marsha Moses:  Silence.
16781314 Marsha Moses:  you.
16781314 Marsha Moses:  So Dr. Biala says you were writing your papers.
16781314 Marsha Moses: Who was reviewing them and making suggestions and editing them along with you for you?
16781314 Marsha Moses:  You know.
16781314 Marsha Moses:  Thanks.
16781314 Marsha Moses:  David, do you have any more questions?
16781314 Marsha Moses: And Dr. Z?
16781314 Marsha Moses: And I'm good as well.
16781314 Marsha Moses: So is there anything else, Allison, that you'd like us to know before we part?
16781314 Marsha Moses:  Anything else that you'd like us to know?
16781314 Marsha Moses: Thank you.

In [37]:
# Test Code
# import sys
# sys.path.insert(0, "/app/notebooks/ARI_temp/src/prod/src")
# import reconstruction_utils
# results, LOG = reconstruction_utils.reconstruction(master_result = master_result, speaker_stt= speaker_stt)

# # import importlib

# # # Make some changes to the my_module.py file in your editor

# # # To reload the module and see the changes reflected:
# # importlib.reload(reconstruction_utils)
# output_fileName = 'reconstruction-{project_name}.txt'
# with open( output_fileName, "w", encoding="utf-8-sig") as f:
#                reconstruction_utils.get_speaker_aware_transcript(results, f)

# import worddoc_utils
# docx_path = 'f.docx'
# worddoc_utils.create_word_document_transcriptColored(docx_path,output_fileName)

In [38]:
# # Test Code
# import sys
# sys.path.insert(0, "/app/notebooks/ARI_temp/src/prod/src2")
# import reconstruction_utils
# results, LOG = reconstruction_utils.reconstruction_v2(master_result = master_result, speaker_stt= speaker_stt)

# # import importlib

# # # Make some changes to the my_module.py file in your editor

# # # To reload the module and see the changes reflected:
# # importlib.reload(reconstruction_utils)
# output_fileName = 'reconstruction-{project_name}.txt'
# with open( output_fileName, "w", encoding="utf-8-sig") as f:
#                reconstruction_utils.get_speaker_aware_transcript(results, f)

# import worddoc_utils
# docx_path = 'f.docx'
# worddoc_utils.create_word_document_transcriptColored(docx_path,output_fileName)

In [39]:
# ## report missing segments (speaker segments that were not assigned)
# output_fileName_withMissing = os.path.join(output_dir,f'reconstruction-{project_name}-wMissing-{project_name}.txt')
# df_m = missingsegments_helper.get_missing_segments(pred_result = results, speaker_stt = speaker_stt, output_fileName_withMissing= output_fileName_withMissing )


# ## create a word file for edited transcript with missing segments
# docx_path = f'reconstruction--wMissing-{project_name}.docx'
# worddoc_utils.create_word_document_transcriptColored(docx_path,output_fileName_withMissing)
# print (f'The transcript with speaker-missing segments was saved at {docx_path}')    

# LOG['Total_n_missingSegments [from individual files]'] = df_m.shape[0]
# ## create a docx with the table of missing segments
# worddoc_utils.df_to_docx_table(df = df_m, filepath ='MissingSegments-{project_name}.docx')
# for speaker in speaker_stt:
#     df = df_m[df_m['speaker']==speaker]
#     LOG[f'Total_n_missingSegments_{speaker}'] = df.shape[0]
#     worddoc_utils.df_to_docx_table(df = df, filepath =f'MissingSegments-{project_name}-{speaker}.docx')

In [40]:
speaker_stt.keys()

dict_keys(['16778242 Kristin Bittinge', '16781314 Marsha Moses', '16790530 Zhongcong Xie', '16797698 David Paul', '16806914 Rich Goldstein', '16807938 Allison Bialas'])

In [41]:
values = master_result['segments']
for segment in values:
    print (f'{segment['start']}- {segment['end']} {segment['speaker']}: {segment['text']}')

3.48- 4.681 SPEAKER_02:  So I'm Kristen Bittinger.
4.741- 7.322 SPEAKER_02: I'm Chief Integrity Officer at Harvard Medical School.
7.342- 14.726 SPEAKER_02: I'm joined by Rachel Fouchier, the Executive Coordinator at Academic and Research Integrity at Harvard Medical School.
14.746- 20.61 SPEAKER_02: Fariba Humin, the Chief Compliance Officer at Boston Children's Hospital.
21.519- 25.922 SPEAKER_02:  Stephen Cox, Program Manager in Research Integrity at Harvard Medical School.
25.942- 30.806 SPEAKER_02: Aaron Walsh, Program Manager in Research Integrity at Harvard Medical School.
32.027- 36.17 SPEAKER_02: Daniel Wainstock, our Director for Research Integrity at Harvard Medical School.
37.591- 40.693 SPEAKER_02: Heather Quay, Legal Counsel at Harvard University.
42.074- 48.119 SPEAKER_02: Gretchen Brodnicki, Dean for Faculty and Research Integrity and the Research Integrity Officer at Harvard Medical School.
49.265- 53.347 SPEAKER_02:  Mary Walsh, our Chief Scientific Investigator at Harvard Medical School.
54.247- 57.609 SPEAKER_02: Blake Calvert, Scientific Investigator at Harvard Medical School.
58.989- 63.691 SPEAKER_02: Gus Cervini, Vice President for Research Administration at Boston Children's Hospital.
65.292- 71.455 SPEAKER_02: I'm then going to turn it over to Dr. Moses, but I first want to thank you both for joining us today.
71.975- 78.918 SPEAKER_02: And again, the panel knows that you want to make an opening statement, but I'll just let Dr. Moses introduce herself and the panel members introduce themselves first.
79.347- 79.707 SPEAKER_02:  Thank you.
81.148- 81.969 SPEAKER_03: Thanks, Kristen.
83.63- 94.436 SPEAKER_03: Dr. Bialis, we're just going to quickly introduce ourselves, have you guys introduce yourselves, and then we can begin the conversation.
94.536- 96.498 SPEAKER_03: So as you know, I'm Marcia Moses.
96.518- 101.601 SPEAKER_03: I'm the director of the Vascular Biology Program at Boston Children's Hospital, and I'm on the faculty at HMS.
104.427- 106.248 SPEAKER_01:  Hi, I'm David Paul.
106.328- 111.39 SPEAKER_01: I'm a professor of neurobiology in the Department of Neurobiology on the Quadrangle.
113.611- 115.131 SPEAKER_04: Hi, I'm Tung-Tung Hsieh.
115.231- 120.273 SPEAKER_04: I'm the professor of anesthesia, and I'm working at the Mass General Hospital.
120.293- 122.814 SPEAKER_00: Hi, thank you.
124.455- 130.817 SPEAKER_00: So I'm Allison Bialas, and my lawyer, Richard Goldstein, is also on the call.
131.417- 131.978 SPEAKER_01: Hello, everyone.
131.998- 132.998 SPEAKER_01: Hello.
135.177- 138.459 SPEAKER_03:  Um, so I understand you're right.
138.579- 142.101 SPEAKER_03: You want to make make a statement and we're happy to hear that.
142.141- 142.961 SPEAKER_03: So it's all yours.
143.942- 144.542 SPEAKER_00: Okay, thank you.
146.503- 150.986 SPEAKER_00: So first of all, I just want to thank you all for taking time to meet with me today.
151.786- 155.528 SPEAKER_00: And for all the time you're having to spend on reviewing my case.
157.029- 160.671 SPEAKER_00: For my statement today, I won't spend time going through each allegation.
161.351- 162.772 SPEAKER_00: I have already written a lot.
163.647- 169.89 SPEAKER_00:  I prepared a lengthy stipulation covering the errors, the errors I knew about in all four of the publications.
170.53- 173.451 SPEAKER_00: I'm not aware of any other errors in those publications.
174.612- 180.675 SPEAKER_00: I submitted an admission, additional statements to the inquiry committee, and I've met with staff on numerous occasions.
181.875- 192.24 SPEAKER_00: I've also submitted documents to Dr. Stevens detailing the locations of all the data and analysis I could find, along with several options for work that could be done to correct the paper.
193.813- 199.796 SPEAKER_00:  I worked closely with Dr. Carroll for several months to find data, review the data and rerun experiments.
200.356- 203.697 SPEAKER_00: And I answered any questions you had associated with my work.
205.158- 207.739 SPEAKER_00: Hopefully you all had access to all of that.
208.919- 214.021 SPEAKER_00: I reviewed these items for this interview and I will do my best to answer questions you have about them.
215.162- 218.703 SPEAKER_00: This has been a very long, very hard two and a half years.
219.624- 222.425 SPEAKER_00: The last thing I wanted to do was to have to come before you today.
223.658- 233.003 SPEAKER_00:  For me, finding the words to express how truly sorry I am feels impossible, and saying anything to defend myself feels unfair to Dr. Stephens and Dr. Carroll.
233.724- 249.292 SPEAKER_00: But given all the time you have spent dealing with this, I wanted you to have a chance to meet me and to get an introduction to who I am and a sense of my state of mind during the time when I was working in the Stephens lab and in the later years in the Carroll lab.
250.273- 252.634 SPEAKER_00: Then if you have questions about specific allegations,
253.162- 254.022 SPEAKER_00:  I'll try to answer them.
255.463- 261.965 SPEAKER_00: So first of all, I want to start by telling you that my education has always been one of the most important things in my life.
262.945- 267.227 SPEAKER_00: Before I came to Harvard, I had many scholastic achievements, of which I was very proud.
268.627- 270.488 SPEAKER_00: I was valedictorian of my high school class.
270.668- 272.789 SPEAKER_00: I graduated from Cornell with a 4.0.
274.729- 279.751 SPEAKER_00: I had never been anything other than a great student who loved learning and solving problems.
283.0- 286.062 SPEAKER_00:  I'm sorry, this is what drew me to academic research.
287.243- 299.41 SPEAKER_00: I came to graduate school directly after college with undergraduate experience in a Drosophila neuroscience lab and summer internships in immunology labs and at a biotech company.
300.531- 309.236 SPEAKER_00: I had never worked on the kind of multi-year project where it was necessary to combine data collected over a long period into a coherent story.
309.256- 311.157 SPEAKER_00: I had never published a paper.
312.427- 316.249 SPEAKER_00:  I admit that I made these errors and mistakes, which I spelled out in the stipulation.
317.13- 319.051 SPEAKER_00: I wish that I had caught these errors.
320.072- 322.353 SPEAKER_00: There may be other errors that I'm not aware of.
323.514- 327.356 SPEAKER_00: Should my superiors and co-authors have caught these errors, maybe.
328.577- 331.139 SPEAKER_00: It's not for me to judge, that's your job.
332.56- 337.583 SPEAKER_00: Many of the errors occurred when I was a grad student in a brand new, very small lab.
338.583- 339.224 SPEAKER_00: When I started,
339.7- 348.045 SPEAKER_00:  The Stevens Lab did not have set protocols in terms of data management and record keeping, and I was inexperienced with these kinds of things.
349.366- 353.749 SPEAKER_00: It was the kind of scenario where I didn't even know all the things that I didn't know.
354.989- 358.612 SPEAKER_00: There's a lot more than I thought required to correctly assemble a manuscript.
360.793- 369.118 SPEAKER_00: Dr. Stevens and I met regularly, but our discussions usually centered around the fun stuff, what experiments were needed to move projects forward.
370.092- 384.499 SPEAKER_00:  Dr. Stephens and I changed the goals of my project, the flow of the data, and the most important experiments for me to focus on very frequently, at times weekly or even daily, to try to come up with the most compelling way to tell the story of my project.
385.259- 394.364 SPEAKER_00: I had dozens of figure outlines, some of which had placeholder figures, some with more complete figures, and I think in some cases,
394.926- 401.711 SPEAKER_00:  That may have been how I got confused with the ends and had some of the groups having N equals six and some only having N equals three.
402.792- 413.321 SPEAKER_00: Errors can propagate when you've been through a process, when you've never been through a process before and you don't realize what documents you generate along the way will ultimately feed into your final product.
414.422- 420.627 SPEAKER_00: I think some consideration has to be given for my very junior status at the time and the lab environment I was in.
421.347- 422.148 SPEAKER_00: I was in training.
422.728- 424.57 SPEAKER_00: I was not an experienced scientist.
425.942- 430.044 SPEAKER_00:  but I was a very enthusiastic and perhaps too enthusiastic student.
431.185- 436.788 SPEAKER_00: I never said no to any opportunity to learn something new or to help someone out, and I quickly became overcommitted.
438.089- 440.07 SPEAKER_00: Also, the lab grew relatively quickly.
440.851- 448.735 SPEAKER_00: Despite my inexperience, I became a senior member of the lab within a few months of starting there in 2008, when I was still a first year graduate student.
449.796- 454.959 SPEAKER_00: As the years went by, especially around the time when I was preparing my thesis and the nature neuroscience paper,
455.682- 464.366 SPEAKER_00:  I rarely had quiet time when I was preparing, or I rarely had quiet time to sit at my desk, think about my project, and review my work.
465.146- 469.028 SPEAKER_00: I felt as though I was constantly being interrupted by someone who needed me for something.
469.969- 479.793 SPEAKER_00: For that reason, I ended up writing most of my thesis at home after lab, working late into the night, a time when no one is really at their best.
480.974- 485.216 SPEAKER_00: On top of that, I often had issues accessing data and programs through the VPN
485.737- 487.859 SPEAKER_00:  and would have to go back into lab for that.
488.259- 494.283 SPEAKER_00: So basically my analysis, writing, and figure making were more often than not occurring in fits and spurts.
495.864- 510.014 SPEAKER_00: I always tried my best, but the cards were stacked against me in some ways because of who I am, all the things I chose to take on, and my inability to drown out the noise and focus on the most important parts of being a graduate student.
511.735- 514.137 SPEAKER_00: When working on my thesis and the Nature Neuroscience paper,
514.93- 518.892 SPEAKER_00:  I really tried to be and thought that I was accurate and correct.
519.893- 522.995 SPEAKER_00: I didn't knowingly let errors slip into the papers, but they did.
525.196- 539.605 SPEAKER_00: As I was finishing my thesis and writing my Nature Neuroscience paper, Beth asked me to help with a collaborative project that eventually became the 2016 Nature paper, or the C4 paper, I'll call it sometimes.
540.726- 543.027 SPEAKER_00: I continued working on this project in the Carroll Lab,
543.435- 549.578 SPEAKER_00:  as I started to pursue the separate project that became my 2017 Nature paper.
549.598- 561.224 SPEAKER_00: I mention this just because based on my explanation of the errors in the C4 paper in my stipulation, the inquiry report did not include any kind of misconduct in the C4 paper.
561.885- 564.086 SPEAKER_00: And these data were collected in the Carroll Lab as well.
565.026- 567.968 SPEAKER_00: I freely admit I made errors in my portion of that paper.
568.452- 573.454 SPEAKER_00:  Despite that, my explanation seemed sufficient to show that this mistake was an honest error.
574.454- 580.796 SPEAKER_00: There are other examples of errors in my stipulation that were also not included in the inquiry report as allegations of misconduct.
581.656- 587.698 SPEAKER_00: The point I'm trying to make is that mistakes alone are not evidence of misconduct, even if there are a lot of them.
592.899- 594.98 SPEAKER_00: I don't think, excuse me,
600.453- 614.865 SPEAKER_00:  I don't think you should view the mistakes in the thesis and the nature neuroscience paper as a prelude to the misconduct in the lupus paper because the earlier mistakes occurred when I was in a different place and a very different state of mind.
617.067- 625.734 SPEAKER_00: Starting in the Carroll lab was a very different place than starting in the Stevens lab because it was a well-established lab with standard practices in place.
627.117- 633.401 SPEAKER_00:  One of the common practices was to send Dr. Carroll progress reports each week and to present at lab meeting each week.
634.502- 637.124 SPEAKER_00: Dr. Carroll never expressed any concerns about my work.
637.885- 643.448 SPEAKER_00: However, I was the only neuroscientist in the lab and I was doing many techniques that no one else was doing.
644.729- 646.671 SPEAKER_00: Because of this, I had to be pretty independent.
647.511- 652.875 SPEAKER_00: I relied on my experience in the Stevens Lab, which at the time I thought, you know, was adequate training.
653.882- 659.444 SPEAKER_00:  However, even though I was now working in the Carroll Lab, I kept getting pulled into things with the Stevens Lab.
659.964- 661.784 SPEAKER_00: I was still maintaining a mouse colony there.
661.804- 663.745 SPEAKER_00: I was writing grant progress reports.
663.905- 668.326 SPEAKER_00: I was reviewing papers, continuing experiments, and advising some students.
669.307- 680.17 SPEAKER_00: At times, the stress over maintaining my relationships with my former and current advisor was all-consuming for me because I cared very, very much about not letting anyone down.
681.773- 687.215 SPEAKER_00:  I let myself get overwhelmed, both physically and emotionally, and at a certain point, it just became too much.
688.896- 696.979 SPEAKER_00: After years of increasing pressures and responsibilities, some of which were self-inflicted, I reached a point while in the Carroll Lab, and I've admitted this.
698.539- 704.341 SPEAKER_00: When I was working on the lupus paper, I cut some corners and I made some assumptions that I know were not acceptable.
705.182- 709.043 SPEAKER_00: My initial enthusiasm for science, which I experienced when I was in the Stevens Lab,
709.82- 715.885 SPEAKER_00:  and which I hoped would continue during my postdoc, was replaced by irritability and anxiety.
716.425- 722.07 SPEAKER_00: At many times while I was in the Carroll Lab, I felt so overwhelmed that I just stopped caring about the quality of my work.
723.411- 725.593 SPEAKER_00: Looking back on it, this was new to me.
726.934- 736.862 SPEAKER_00: Unlike the positive excitement I felt when I was in the Stevens Lab, where I tried to do my best, after I had been a postdoc for a couple of years, I just started making impulsive and reckless decisions.
737.734- 745.119 SPEAKER_00:  For example, when I was in the CARE lab, I completely neglected to record anything in my lab notebook to document behavioral characterization I did.
745.759- 753.024 SPEAKER_00: I didn't save the raw data, and I exported the data in such a disorganized way that it was almost guaranteed to cause mix-ups.
753.724- 757.406 SPEAKER_00: I never did anything like that when I was under Dr. Stevens' supervision.
758.827- 764.511 SPEAKER_00: I admit I committed reckless misconduct when it came to my 2017 paper, but I want you to understand
765.262- 768.205 SPEAKER_00:  that my earlier mistakes were of a different kind and quality.
768.845- 776.271 SPEAKER_00: It doesn't make sense to assume that because I committed misconduct on the 2017 paper, that all earlier errors are also misconduct.
777.172- 780.695 SPEAKER_00: I was in a different stage of my training when I was writing the 2017 paper.
781.236- 787.341 SPEAKER_00: I was in a different lab and working on a paper with many collaborators rather than just doing everything myself.
788.081- 792.165 SPEAKER_00: The research issues were different, the projects were separate, and they happened years apart.
793.452- 796.053 SPEAKER_00:  Most importantly, I was in a totally different frame of mind.
797.053- 800.553 SPEAKER_00: I felt I was on the verge of a great career in academia.
801.154- 808.535 SPEAKER_00: I had positive feedback from many of my colleagues all along the way, including Dr. Stevens and Dr. Carroll, that I had what it took to be a PI.
809.355- 814.276 SPEAKER_00: And it's very hard to admit that they were wrong about me and that I was wrong about myself.
816.477- 821.898 SPEAKER_00: And over the past couple of years during this process,
822.818- 829.84 SPEAKER_00:  I've done a lot of soul searching to try to have a better grasp of what happened so I can make sure that it never happens again.
830.941- 843.345 SPEAKER_00: And with the help of medical professionals, I've realized some things about myself that weren't apparent to me when I was working on my graduate and postdoc projects that kind of set me up to fail from early on.
844.485- 846.226 SPEAKER_00: Others may have seen it, but I didn't.
847.146- 852.288 SPEAKER_00: I guess it's stating the obvious to say that I am poorly suited to the type of environment I found myself in.
853.308- 858.772 SPEAKER_00:  During my training, I can be a very enthusiastic and energetic person in bursts.
859.013- 862.535 SPEAKER_00: Every idea sounds super exciting, and I just want to do it all.
863.476- 869.501 SPEAKER_00: With short-term goals, even on a tight deadline, I can usually deliver, and sometimes at a high level of success.
870.742- 875.206 SPEAKER_00: I think I was doing okay, just okay, when I was in the Stevens Lab.
876.407- 879.089 SPEAKER_00: But with longer projects, both personally and professionally,
879.869- 883.27 SPEAKER_00:  I now recognize that my high energy and enthusiasm is not sustained.
884.09- 886.531 SPEAKER_00: I run out of steam and I lose my focus and motivation.
887.371- 889.712 SPEAKER_00: I become overwhelmed when commitments start to pile up.
889.792- 892.933 SPEAKER_00: I make mistakes and I fail to deliver at the same level.
894.213- 896.474 SPEAKER_00: This was especially true in the Carroll lab.
897.234- 903.056 SPEAKER_00: When I felt the stress of the commitments I carried over from the Stevens lab and new pressures from the Carroll lab converging.
906.817- 907.537 SPEAKER_00: I love science.
908.391- 919.895 SPEAKER_00:  I want to be successful, and now that I recognize and I'm addressing my issues with an appropriate support system, I think I still have a lot to offer, and it just won't be as a PI in academic science.
921.715- 924.336 SPEAKER_00: I am very sorry for how this all turned out.
925.916- 929.417 SPEAKER_00: I disappointed a lot of people, and the good reputation I had is gone.
930.198- 932.338 SPEAKER_00: My career as an academic scientist is over.
932.938- 937.78 SPEAKER_00: Paper retractions were deemed necessary, and valuable research resources have been diverted.
939.487- 943.79 SPEAKER_00:  I feel so terrible about all of this, and I will never forgive myself for it.
945.391- 955.097 SPEAKER_00: Dr. Carroll and Dr. Stephens may read this statement, and I don't quite know what to say to them, except that I'm so sorry, and I hope that someday they can understand.
956.398- 964.663 SPEAKER_00: However, these negative outcomes do not change the fact that I never knowingly or intentionally put false or fabricated data in any paper.
965.464- 966.885 SPEAKER_00: I want to be very clear about that.
967.937- 974.201 SPEAKER_00:  When it came to the lupus paper, should I have checked with Dr. Carroll and asked for more help from him and my co-authors?
974.942- 975.502 SPEAKER_00: Absolutely.
976.763- 984.329 SPEAKER_00: If I had made an effort to involve them more and been more open about my struggles, my errors could have been avoided.
985.369- 994.776 SPEAKER_00: I realized that when it came to the Nature Neuroscience paper and my thesis, I would have benefited from asking Dr. Stevens to go over it in painstaking detail.
995.577- 997.478 SPEAKER_00: Should I have insisted that she do this with me?
997.94- 1003.362 SPEAKER_00:  Yes, looking back, I'm sure it would have helped, but at the time I really didn't see the problems with my work.

# Reconstruction

## Reconstruction 2

In [42]:
LOG= {}

In [43]:
###  get recontruction dictionary
reconstruction_segments = copy.deepcopy(master_result['segments'])

### Step 1: Word Assignment

In [44]:
master_text = ''
master_words=[]
for idx_reconstruction in range(len(reconstruction_segments)):
      text= reconstruction_segments[idx_reconstruction]['text']
      words = reconstruction_segments[idx_reconstruction]['words']
      master_text += f' {text}'
      master_words = master_words + words


## find speakers with matching sequences, and use it to find who said each word.
wordidx_2speaker={}
for speaker in SPEAKERS:
    speaker_text =''
    speaker_words=[]
    prediction_segments = speaker_stt[speaker]['segments']
    for idx_sorted in range(len(prediction_segments)):
            text = prediction_segments[idx_sorted]['text']
            words = prediction_segments[idx_sorted]['words']
            if len(words) == len(text.split()):
                speaker_text += f' {text}'
                speaker_words = speaker_words + words

    matches = unique_common_sequences(remove_punctuation(master_text.lower()), remove_punctuation(speaker_text.lower()), min_len=3)
    for match in matches:
        match_text, match_refIdx, match_predIdx, match_n = match
        for idx in np.arange(match_refIdx, match_n+match_refIdx,1):
            if idx not in wordidx_2speaker:
                wordidx_2speaker[idx]=[]
            wordidx_2speaker[idx].append([speaker, match_n])

In [45]:
for idx in range(len(master_words)):
    master_words[idx]['idx']= idx

In [46]:
def sort_dict_by_key(d):
    return dict(sorted(d.items(), key=lambda item: item[0]))
wordidx_2speaker = sort_dict_by_key(wordidx_2speaker)

In [47]:
wordidx_2speaker[0]

[['16778242 Kristin Bittinge', 16]]

In [48]:
## clean pure speakers and speakers with the highest overlap

def get_highest_match(speaker_matches):
    """
    Returns [speaker, match_n] with the highest match_n.
    If there is a tie for highest, returns None.
    """
    if not speaker_matches:
        return None

    # Find max match_n
    max_value = max(speaker_matches, key=lambda x: x[1])[1]

    # Count how many have that max value
    highest = [item for item in speaker_matches if item[1] == max_value]

    if len(highest) == 1:
        return highest[0]
    else:
        return None
        
wordidx_2speaker_clean ={}
for idx in wordidx_2speaker:
    speakers = wordidx_2speaker[idx]
    if len(speakers) == 1:
        wordidx_2speaker_clean[idx] = speakers[0][0]
    
    else:
        if idx!=0 and idx-1 in wordidx_2speaker_clean:
            old_speaker =  wordidx_2speaker_clean[idx-1]

            ## get the len of the old common sequence
            for speaker in wordidx_2speaker[idx-1]:
                if old_speaker == speaker[0]:
                    old_score= speaker[1]
                    
            ## get the len of the current sequence
            updated_speakers=[]
            for speaker in speakers:
                speaker_name = speaker[0]
                speaker_score = speaker[1]
                if speaker_name==old_speaker:
                    speaker_score = speaker_score+old_score
                updated_speakers.append([speaker_name, speaker_score])
            
            
            potential_next= get_highest_match(updated_speakers)
            if potential_next:
                for speaker in speakers:
                    speaker_name = speaker[0]
                    speaker_score = speaker[1]
                    if speaker_name== old_speaker and speaker_score>potential_next[1]:
                            wordidx_2speaker_clean[idx] = speaker_name
                            break

                    
            # if next_:
            #     wordidx_2speaker_clean[idx] = next_[0]
            wordidx_2speaker[idx] = updated_speakers

In [49]:
LOG['n_total_words'] = len(master_words)
LOG['n_total_segments'] = len(reconstruction_segments)
LOG['n_mapped_words'] = len(wordidx_2speaker_clean)
len(wordidx_2speaker_clean), len(wordidx_2speaker), len(master_words)

(7078, 7141, 7322)

In [50]:
## ALLOCATE SPEAKER NAMES TO WORDS
for word_idx in wordidx_2speaker_clean:
    master_words[word_idx]['speaker'] = wordidx_2speaker_clean[word_idx]

### Step 2: 1st Segment Assignment

In [51]:
segmentidx_2words= get_segment2wordsIdx(reconstruction_segments)
segmentidx_2words[1]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
## allocate speaker to words in reconstruction_segments
for segment_idx in range(len(reconstruction_segments)):
    words_global_idxs= segmentidx_2words[segment_idx] 
    words_insegment = reconstruction_segments[segment_idx]['words']
    for idx in range(len(words_insegment)):
        words_global_idx =  words_global_idxs[idx]
        speaker = master_words[ words_global_idx]['speaker']
        words_insegment[idx]['speaker']= speaker
    reconstruction_segments[segment_idx]['words'] = words_insegment

In [53]:
## check purity
for segment_idx in range(len(reconstruction_segments)):
    speaker_id =[word['speaker'] for word in reconstruction_segments[segment_idx]['words']]
    speaker_id = count_items(speaker_id)
    if len(speaker_id)!=1:
        print (speaker_id, segment_idx)

{'16778242 Kristin Bittinge': 16, 'SPEAKER_02': 1} 2
{'16778242 Kristin Bittinge': 7, 'SPEAKER_02': 1} 10
{'16778242 Kristin Bittinge': 10, 'SPEAKER_02': 1} 11
{'16778242 Kristin Bittinge': 24, 'SPEAKER_02': 4} 13
{'SPEAKER_00': 1, '16807938 Allison Bialas': 2} 23
{'SPEAKER_03': 5, 'SPEAKER_00': 1} 27
{'SPEAKER_03': 4, '16781314 Marsha Moses': 9} 28
{'SPEAKER_00': 1, '16807938 Allison Bialas': 2} 30
{'16807938 Allison Bialas': 18, 'SPEAKER_00': 1} 35
{'16807938 Allison Bialas': 9, 'SPEAKER_00': 1} 36
{'16807938 Allison Bialas': 10, 'SPEAKER_00': 1} 40
{'16807938 Allison Bialas': 24, 'SPEAKER_00': 4} 45
{'16807938 Allison Bialas': 57, 'SPEAKER_00': 1} 46
{'16807938 Allison Bialas': 22, 'SPEAKER_00': 1} 68
{'16807938 Allison Bialas': 20, 'SPEAKER_00': 3} 73
{'16807938 Allison Bialas': 27, 'SPEAKER_00': 2} 79
{'16807938 Allison Bialas': 23, 'SPEAKER_00': 5} 81
{'16807938 Allison Bialas': 23, 'SPEAKER_00': 4} 102
{'16807938 Allison Bialas': 24, 'SPEAKER_00': 1} 118
{'16807938 Allison Bialas': 37, 'SPEAKER_00': 2} 120
{'16807938 Allison Bialas': 23, 'SPEAKER_00': 1} 122
{'16807938 Allison Bialas': 25, 'SPEAKER_00': 4} 132
{'16807938 Allison Bialas': 10, 'SPEAKER_00': 2} 155
{'16797698 David Paul': 12, 'SPEAKER_01': 1} 180
{'SPEAKER_00': 1, '16807938 Allison Bialas': 11} 183
{'16807938 Allison Bialas': 7, 'SPEAKER_00': 2} 185
{'16807938 Allison Bialas': 27, 'SPEAKER_00': 2} 187
{'SPEAKER_01': 1, '16797698 David Paul': 3} 197
{'16790530 Zhongcong Xie': 21, 'SPEAKER_04': 3} 202
{'16807938 Allison Bialas': 8, 'SPEAKER_00': 1} 207
{'16807938 Allison Bialas': 28, 'SPEAKER_00': 3} 211
{'16790530 Zhongcong Xie': 7, 'SPEAKER_04': 6, '16807938 Allison Bialas': 1} 217
{'16790530 Zhongcong Xie': 19, 'SPEAKER_04': 1} 218
{'16790530 Zhongcong Xie': 16, 'SPEAKER_04': 5} 219
{'SPEAKER_00': 2, '16807938 Allison Bialas': 7} 220
{'SPEAKER_04': 1, '16790530 Zhongcong Xie': 2} 223
{'SPEAKER_00': 2, '16807938 Allison Bialas': 4} 231
{'16807938 Allison Bialas': 14, 'SPEAKER_00': 2} 235
{'SPEAKER_04': 1, '16790530 Zhongcong Xie': 5} 236
{'16807938 Allison Bialas': 25, 'SPEAKER_00': 4} 244
{'16807938 Allison Bialas': 11, 'SPEAKER_00': 2} 245
{'SPEAKER_00': 1, '16807938 Allison Bialas': 13} 246
{'SPEAKER_00': 6, '16807938 Allison Bialas': 26} 261
{'16781314 Marsha Moses': 11, 'SPEAKER_03': 1} 268
{'16781314 Marsha Moses': 25, 'SPEAKER_03': 10} 269
{'16807938 Allison Bialas': 32, 'SPEAKER_00': 2} 281
{'16781314 Marsha Moses': 4, 'SPEAKER_03': 1} 283
{'SPEAKER_00': 2, '16807938 Allison Bialas': 12} 286
{'SPEAKER_03': 1, '16797698 David Paul': 1} 294
{'16797698 David Paul': 30, 'SPEAKER_01': 1} 296
{'SPEAKER_04': 4, '16790530 Zhongcong Xie': 18} 316
{'16790530 Zhongcong Xie': 20, 'SPEAKER_04': 1} 318
{'16807938 Allison Bialas': 5, 'SPEAKER_00': 6} 321
{'16807938 Allison Bialas': 12, 'SPEAKER_00': 1} 323
{'16807938 Allison Bialas': 15, 'SPEAKER_00': 2} 331
{'16807938 Allison Bialas': 14, 'SPEAKER_00': 1} 332
{'16790530 Zhongcong Xie': 18, 'SPEAKER_04': 3} 337
{'SPEAKER_03': 1, '16781314 Marsha Moses': 14} 345
{'16807938 Allison Bialas': 11, 'SPEAKER_00': 2} 353
{'SPEAKER_00': 8, '16807938 Allison Bialas': 30} 355
{'SPEAKER_00': 3, '16807938 Allison Bialas': 23} 357
{'16807938 Allison Bialas': 1, 'SPEAKER_00': 1} 358
{'16807938 Allison Bialas': 12, 'SPEAKER_00': 1} 359
{'16807938 Allison Bialas': 12, 'SPEAKER_00': 1} 360
{'16807938 Allison Bialas': 7, 'SPEAKER_00': 2} 361
{'SPEAKER_04': 1, '16790530 Zhongcong Xie': 4} 365
{'16807938 Allison Bialas': 27, 'SPEAKER_00': 2} 377
{'16790530 Zhongcong Xie': 28, 'SPEAKER_04': 1} 379
{'16807938 Allison Bialas': 24, 'SPEAKER_00': 1} 389
{'SPEAKER_04': 2, '16790530 Zhongcong Xie': 12} 390
{'16790530 Zhongcong Xie': 32, 'SPEAKER_04': 1} 391
{'16807938 Allison Bialas': 21, 'SPEAKER_00': 1} 392
{'16807938 Allison Bialas': 19, 'SPEAKER_00': 4} 394
{'16781314 Marsha Moses': 21, 'SPEAKER_03': 1} 402
{'16807938 Allison Bialas': 33, 'SPEAKER_00': 1} 403
{'16807938 Allison Bialas': 15, 'SPEAKER_00': 1} 407
{'SPEAKER_00': 2, '16807938 Allison Bialas': 9} 409
{'16807938 Allison Bialas': 19, 'SPEAKER_00': 1} 427
{'16790530 Zhongcong Xie': 18, 'SPEAKER_04': 1} 428
{'SPEAKER_00': 2, '16807938 Allison Bialas': 14} 431
{'16807938 Allison Bialas': 8, 'SPEAKER_00': 4} 432
{'16790530 Zhongcong Xie': 6, 'SPEAKER_04': 1} 434
{'16807938 Allison Bialas': 40, 'SPEAKER_00': 1} 445
{'SPEAKER_04': 2, '16790530 Zhongcong Xie': 9} 451
{'SPEAKER_00': 6, '16807938 Allison Bialas': 10} 456
{'16807938 Allison Bialas': 23, 'SPEAKER_00': 8} 461
{'16807938 Allison Bialas': 10, 'SPEAKER_00': 2} 462
{'SPEAKER_04': 2, '16790530 Zhongcong Xie': 3} 474
{'16807938 Allison Bialas': 43, 'SPEAKER_00': 3} 480
{'SPEAKER_00': 2, '16807938 Allison Bialas': 1} 492

In [54]:
## create new segments for segments that contain more than one speaker from the list of speakers
def split_by_speaker(segment: dict) -> dict:
    """
    Splits a segment dictionary into separate dictionaries per speaker.
    Fixes the 'text' field accordingly.
    Returns a dictionary keyed by speaker name.
    """
    speakers = {}

    for word in segment["words"]:
        speaker = word["speaker"]

        if speaker not in speakers:
            speakers[speaker] = {
                "start": word["start"],
                "end": word["end"],
                "text": "",
                "words": [],
                "speaker": speaker,
            }

        # Append word
        speakers[speaker]["words"].append(word)
        speakers[speaker]["end"] = word["end"]

    # Fix text field for each speaker
    for speaker_data in speakers.values():
        cleaned_words = [
            w["word"].replace("**", "")  # remove markdown artifacts
            for w in speaker_data["words"]
        ]
        speaker_data["text"] = " ".join(cleaned_words)

    return sorted(speakers.values(), key=lambda x: x["start"])


temp_reconstruction_segments=[]
counter_fixed=0
for segment_idx in range(len(reconstruction_segments)):
    speaker_id =[word['speaker'] for word in reconstruction_segments[segment_idx]['words']]
    speaker_id = count_items(speaker_id)
    if len(speaker_id)==1:
        temp_reconstruction_segments.append(reconstruction_segments[segment_idx])
        continue 

    count=0
    for speaker in speaker_id:
        if speaker in SPEAKERS:
            count+=1
    if  count==1:
        temp_reconstruction_segments.append(reconstruction_segments[segment_idx])
    else:
         # print(f'{segment_idx} is fixed')
         ## split segments
         counter_fixed +=1
         new_segments = split_by_speaker(reconstruction_segments[segment_idx])
         print (segment_idx)
         for segment in new_segments:
             temp_reconstruction_segments.append(segment)
print (f'{counter_fixed} Segments were fixed')

27
217
2 Segments were fixed

In [55]:
reconstruction_segments = temp_reconstruction_segments

In [56]:
reconstruction_segments[110]

{'start': 659.964,
 'end': 661.784,
 'text': 'I was still maintaining a mouse colony there.',
 'words': [{'word': 'I',
   'start': 659.964,
   'end': 660.024,
   'score': 0.726,
   'speaker': '16807938 Allison Bialas',
   'idx': 1727},
  {'word': 'was',
   'start': 660.044,
   'end': 660.144,
   'score': 0.955,
   'speaker': '16807938 Allison Bialas',
   'idx': 1728},
  {'word': 'still',
   'start': 660.184,
   'end': 660.364,
   'score': 0.74,
   'speaker': '16807938 Allison Bialas',
   'idx': 1729},
  {'word': 'maintaining',
   'start': 660.384,
   'end': 660.824,
   'score': 0.732,
   'speaker': '16807938 Allison Bialas',
   'idx': 1730},
  {'word': 'a',
   'start': 660.844,
   'end': 660.884,
   'score': 0.541,
   'speaker': '16807938 Allison Bialas',
   'idx': 1731},
  {'word': 'mouse',
   'start': 660.924,
   'end': 661.164,
   'score': 0.936,
   'speaker': '16807938 Allison Bialas',
   'idx': 1732},
  {'word': 'colony',
   'start': 661.184,
   'end': 661.564,
   'score': 0.889,
   'speaker': '16807938 Allison Bialas',
   'idx': 1733},
  {'word': 'there.',
   'start': 661.604,
   'end': 661.784,
   'score': 0.81,
   'speaker': '16807938 Allison Bialas',
   'idx': 1734}],
 'speaker': 'SPEAKER_00'}

In [57]:
### assignment of speakers to segments:

## sanity check
for segment in reconstruction_segments:
    words = segment['words']
    speakers= []
    for word in words:
        speakers.append(word['speaker'])
    counter= count_items(speakers)
    speakers_allocated=0
    for speaker in counter:
        if counter in SPEAKERS:
            speakers_allocated+=1
    if speakers_allocated >1:
        print (f'error with count {segment}')
        break

for segment in reconstruction_segments:
    speaker_id = [  word['speaker'] for word in segment['words']]
    speaker_id = count_items(speaker_id)
    speaker_id = max(speaker_id, key=speaker_id.get)
    segment['speaker']= speaker_id

In [58]:
counter=0
missing_segments= []
for idx_segment in range(len(reconstruction_segments)):
    if reconstruction_segments[idx_segment]['speaker'] not in SPEAKERS:
        counter+=1
        missing_segments.append([idx_segment,reconstruction_segments[idx_segment]])
for segment in missing_segments:
    print (f'{segment[1]['speaker']}: {segment[1]['text']}')
len(missing_segments)

SPEAKER_04: Hi, I'm Tung-Tung Hsieh.
SPEAKER_01: Hello, everyone.
SPEAKER_01: Hello.
SPEAKER_03: Um, so understand you're right.
SPEAKER_00: I
SPEAKER_04: OK.
SPEAKER_04: where my post off in the
SPEAKER_04: Okay.
SPEAKER_03: Thank you.
SPEAKER_00: In in the Carol lab, they're actually Yeah, in the Carol.
SPEAKER_00: Um, hmm.
SPEAKER_03:  Thank you.
SPEAKER_00: Yes.
SPEAKER_00: Yes.
SPEAKER_00: In the Prism raw.
SPEAKER_00: Excel.
SPEAKER_00:  Yeah.
SPEAKER_00: I wish, you know.
SPEAKER_04: Thank you.
SPEAKER_03: OK.
SPEAKER_00: Just wanna reiterate,
SPEAKER_00: And so thank you.
SPEAKER_00: Thank you.
SPEAKER_00: OK.
SPEAKER_02: Thank you.

25

In [59]:
LOG['n_total_assigned_segments_round1'] =len(reconstruction_segments)-len(missing_segments)
LOG['%_assigned_segments_round1'] =(len(reconstruction_segments)-len(missing_segments))/len(reconstruction_segments)
display(LOG)

{'n_total_words': 7322,
 'n_total_segments': 505,
 'n_mapped_words': 7078,
 'n_total_assigned_segments_round1': 483,
 '%_assigned_segments_round1': 0.9507874015748031}

### Step 3: 2nd Segment Assignment

In [60]:
## find missing segments - first round - method 1: if the segment was said by someone.
missing_segment_speakers= {}
for idx_segment in range(len(missing_segments)):
    segment = remove_punctuation(missing_segments[idx_segment][1]['text']).lower()
    speakers=[]
    for speaker in SPEAKERS:
        speaker_text =''
        prediction_segments = speaker_stt[speaker]['segments']
        for idx_sorted in range(len(prediction_segments)):
                text = prediction_segments[idx_sorted]['text']
                speaker_text += f' {text}'
        speaker_text = remove_punctuation(speaker_text).lower()
        if segment in speaker_text:
            speakers.append(speaker)

    missing_segment_speakers[missing_segments[idx_segment][0]] = speakers

## fill missing segments
for idx_segment in range(len(reconstruction_segments)):
    if reconstruction_segments[idx_segment]['speaker'] not in SPEAKERS:
        if len(missing_segment_speakers[idx_segment])==1:
            reconstruction_segments[idx_segment]['speaker'] = missing_segment_speakers[idx_segment][0]

In [61]:
for segment in reconstruction_segments[:10]:
    print (f'{segment['speaker']}: {segment['text']}')

16778242 Kristin Bittinge:  So I'm Kristen Bittinger.
16778242 Kristin Bittinge: I'm Chief Integrity Officer at Harvard Medical School.
16778242 Kristin Bittinge: I'm joined by Rachel Fouchier, the Executive Coordinator at Academic and Research Integrity at Harvard Medical School.
16778242 Kristin Bittinge: Fariba Humin, the Chief Compliance Officer at Boston Children's Hospital.
16778242 Kristin Bittinge:  Stephen Cox, Program Manager in Research Integrity at Harvard Medical School.
16778242 Kristin Bittinge: Aaron Walsh, Program Manager in Research Integrity at Harvard Medical School.
16778242 Kristin Bittinge: Daniel Wainstock, our Director for Research Integrity at Harvard Medical School.
16778242 Kristin Bittinge: Heather Quay, Legal Counsel at Harvard University.
16778242 Kristin Bittinge: Gretchen Brodnicki, Dean for Faculty and Research Integrity and the Research Integrity Officer at Harvard Medical School.
16778242 Kristin Bittinge:  Mary Walsh, our Chief Scientific Investigator at Harvard Medical School.

In [62]:
missing_segments= []
for idx_segment in range(len(reconstruction_segments)):
    if reconstruction_segments[idx_segment]['speaker'] not in SPEAKERS:
        counter+=1
        missing_segments.append([idx_segment,reconstruction_segments[idx_segment]])
for segment in missing_segments:
    print (f'{segment[1]['speaker']}: {segment[1]['text']}')
len(missing_segments)

SPEAKER_04: Hi, I'm Tung-Tung Hsieh.
SPEAKER_01: Hello.
SPEAKER_03: Um, so understand you're right.
SPEAKER_00: I
SPEAKER_04: OK.
SPEAKER_04: where my post off in the
SPEAKER_04: Okay.
SPEAKER_03: Thank you.
SPEAKER_00: In in the Carol lab, they're actually Yeah, in the Carol.
SPEAKER_00: Um, hmm.
SPEAKER_03:  Thank you.
SPEAKER_00: Yes.
SPEAKER_00: Yes.
SPEAKER_00: Excel.
SPEAKER_00:  Yeah.
SPEAKER_00: I wish, you know.
SPEAKER_04: Thank you.
SPEAKER_03: OK.
SPEAKER_00: Just wanna reiterate,
SPEAKER_00: And so thank you.
SPEAKER_00: Thank you.
SPEAKER_00: OK.
SPEAKER_02: Thank you.

23

In [63]:
LOG['n_total_assigned_segments_round2'] =len(reconstruction_segments)-len(missing_segments)
LOG['%_assigned_segments_round2'] =(len(reconstruction_segments)-len(missing_segments))/len(reconstruction_segments)
LOG

{'n_total_words': 7322,
 'n_total_segments': 505,
 'n_mapped_words': 7078,
 'n_total_assigned_segments_round1': 483,
 '%_assigned_segments_round1': 0.9507874015748031,
 'n_total_assigned_segments_round2': 485,
 '%_assigned_segments_round2': 0.9547244094488189}

### Step 4: Whisper lookup - pure

In [64]:
##second round - method 2: using the whisper diarization to know who is each person id, and use person id to allocate.

## find speaker IDS of each speaker:
speakers_2whisperSpeakerIDs= {}
for  orig, new in zip(master_result['segments'], reconstruction_segments):
    speaker = new['speaker']
    orig_speaker = orig['speaker']
    if speaker in SPEAKERS:
        if speaker not in speakers_2whisperSpeakerIDs:
            speakers_2whisperSpeakerIDs[speaker] =[]
        speakers_2whisperSpeakerIDs[speaker].append(orig_speaker)

speaker_id_counts_all={}
for speaker in speakers_2whisperSpeakerIDs:
    speaker_id_counts = count_items(speakers_2whisperSpeakerIDs[speaker])
    display(speaker, speaker_id_counts)
    speaker_id_counts_all[speaker] = speaker_id_counts
    speaker_id = max(speaker_id_counts, key=speaker_id_counts.get)
    speakers_2whisperSpeakerIDs[speaker] = speaker_id
display(speakers_2whisperSpeakerIDs)

'16778242 Kristin Bittinge'

{'SPEAKER_02': 17, 'SPEAKER_00': 1}

'16781314 Marsha Moses'

{'SPEAKER_03': 9, 'SPEAKER_00': 14, 'SPEAKER_04': 2}

'16797698 David Paul'

{'SPEAKER_01': 7, 'SPEAKER_00': 4, 'SPEAKER_04': 5}

'16790530 Zhongcong Xie'

{'SPEAKER_04': 15, 'SPEAKER_01': 2, 'SPEAKER_00': 30, 'SPEAKER_03': 4}

'16807938 Allison Bialas'

{'SPEAKER_00': 328,
 'SPEAKER_01': 4,
 'SPEAKER_04': 28,
 'SPEAKER_03': 12,
 'SPEAKER_02': 1}

'16806914 Rich Goldstein'

{'SPEAKER_01': 1}

{'16778242 Kristin Bittinge': 'SPEAKER_02',
 '16781314 Marsha Moses': 'SPEAKER_00',
 '16797698 David Paul': 'SPEAKER_01',
 '16790530 Zhongcong Xie': 'SPEAKER_00',
 '16807938 Allison Bialas': 'SPEAKER_00',
 '16806914 Rich Goldstein': 'SPEAKER_01'}

In [65]:
## clean duplicates assigments
whisperSpeakerIDs_2speakers = {}
for speaker in speakers_2whisperSpeakerIDs:
    if speakers_2whisperSpeakerIDs[speaker] not in whisperSpeakerIDs_2speakers:
        whisperSpeakerIDs_2speakers[speakers_2whisperSpeakerIDs[speaker]] = []
    whisperSpeakerIDs_2speakers[speakers_2whisperSpeakerIDs[speaker]].append(speaker)
speakers = list(whisperSpeakerIDs_2speakers.keys())
for speaker in speakers:
    if  len(whisperSpeakerIDs_2speakers[speaker]) !=1:
       del whisperSpeakerIDs_2speakers[speaker]
    else:
        whisperSpeakerIDs_2speakers[speaker] = whisperSpeakerIDs_2speakers[speaker][0]
display(whisperSpeakerIDs_2speakers)

{'SPEAKER_02': '16778242 Kristin Bittinge'}

In [66]:
# get uniques --- one person only
whisperSpeakerIDs_2speakers_raw ={}
for speaker in speaker_id_counts_all:
    for ID in speaker_id_counts_all[speaker]:
        if ID not in whisperSpeakerIDs_2speakers_raw :
            whisperSpeakerIDs_2speakers_raw [ID] = []
        whisperSpeakerIDs_2speakers_raw[ID].append(speaker)
display(whisperSpeakerIDs_2speakers_raw )


# for key_ in whisperSpeakerIDs_2speakers:
#     del whisperSpeakerIDs_2speakers_raw [key_]

whisperSpeakerIDs_2speakers_raw_keys  = list(whisperSpeakerIDs_2speakers_raw.keys())
for key_ in whisperSpeakerIDs_2speakers_raw_keys:
    speakers= whisperSpeakerIDs_2speakers_raw[key_]
    if len(speakers) != 1:
        del whisperSpeakerIDs_2speakers_raw[key_]
    else:
        whisperSpeakerIDs_2speakers_raw[key_]=whisperSpeakerIDs_2speakers_raw[key_][0]
    # text= f'{speakers[0]}'
    # for speaker in speakers[1:]:
    #     text= f'{text}, {speaker}'
    # whisperSpeakerIDs_2speakers_raw[key_] = text
whisperSpeakerIDs_2speakers_raw

{'SPEAKER_02': ['16778242 Kristin Bittinge', '16807938 Allison Bialas'],
 'SPEAKER_00': ['16778242 Kristin Bittinge',
  '16781314 Marsha Moses',
  '16797698 David Paul',
  '16790530 Zhongcong Xie',
  '16807938 Allison Bialas'],
 'SPEAKER_03': ['16781314 Marsha Moses',
  '16790530 Zhongcong Xie',
  '16807938 Allison Bialas'],
 'SPEAKER_04': ['16781314 Marsha Moses',
  '16797698 David Paul',
  '16790530 Zhongcong Xie',
  '16807938 Allison Bialas'],
 'SPEAKER_01': ['16797698 David Paul',
  '16790530 Zhongcong Xie',
  '16807938 Allison Bialas',
  '16806914 Rich Goldstein']}

{}

In [67]:
## fill --- using speaker IDs that were assigned to one person only.

for idx_segment in range(len(reconstruction_segments)):
        speaker =  reconstruction_segments[idx_segment]['speaker']
        if speaker not in SPEAKERS:
            if speaker in whisperSpeakerIDs_2speakers_raw:
                reconstruction_segments[idx_segment]['speaker'] = whisperSpeakerIDs_2speakers_raw[speaker]
                reconstruction_segments[idx_segment]['words'][0]['word'] = f'*{reconstruction_segments[idx_segment]['words'][0]['word']}'
                reconstruction_segments[idx_segment]['words'][-1]['word'] = f'{reconstruction_segments[idx_segment]['words'][-1]['word']}*'

In [68]:
len(reconstruction_segments)

508

In [69]:
missing_segments= []
for idx_segment in range(len(reconstruction_segments)):
    if reconstruction_segments[idx_segment]['speaker'] not in SPEAKERS:
        counter+=1
        missing_segments.append([idx_segment,reconstruction_segments[idx_segment]])
for segment in missing_segments:
    print (f'{segment[1]['speaker']}: {segment[1]['text']}')
len(missing_segments)

SPEAKER_04: Hi, I'm Tung-Tung Hsieh.
SPEAKER_01: Hello.
SPEAKER_03: Um, so understand you're right.
SPEAKER_00: I
SPEAKER_04: OK.
SPEAKER_04: where my post off in the
SPEAKER_04: Okay.
SPEAKER_03: Thank you.
SPEAKER_00: In in the Carol lab, they're actually Yeah, in the Carol.
SPEAKER_00: Um, hmm.
SPEAKER_03:  Thank you.
SPEAKER_00: Yes.
SPEAKER_00: Yes.
SPEAKER_00: Excel.
SPEAKER_00:  Yeah.
SPEAKER_00: I wish, you know.
SPEAKER_04: Thank you.
SPEAKER_03: OK.
SPEAKER_00: Just wanna reiterate,
SPEAKER_00: And so thank you.
SPEAKER_00: Thank you.
SPEAKER_00: OK.
SPEAKER_02: Thank you.

23

In [70]:
LOG['n_total_assigned_segments_round3'] =len(reconstruction_segments)-len(missing_segments)
LOG['%_assigned_segments_round3'] =(len(reconstruction_segments)-len(missing_segments))/len(reconstruction_segments)
LOG

{'n_total_words': 7322,
 'n_total_segments': 505,
 'n_mapped_words': 7078,
 'n_total_assigned_segments_round1': 483,
 '%_assigned_segments_round1': 0.9507874015748031,
 'n_total_assigned_segments_round2': 485,
 '%_assigned_segments_round2': 0.9547244094488189,
 'n_total_assigned_segments_round3': 485,
 '%_assigned_segments_round3': 0.9547244094488189}

### Step 5: Whisper all

In [71]:
whisperSpeakerIDs_2speakers

{'SPEAKER_02': '16778242 Kristin Bittinge'}

In [72]:
## fill --- using speaker IDs that mostlikely belong to the person

display(whisperSpeakerIDs_2speakers)
for idx_segment in range(len(reconstruction_segments)):
        speaker =  reconstruction_segments[idx_segment]['speaker']
        if speaker in whisperSpeakerIDs_2speakers:
            reconstruction_segments[idx_segment]['speaker'] = whisperSpeakerIDs_2speakers[speaker]
            reconstruction_segments[idx_segment]['words'][0]['word'] = f'**{reconstruction_segments[idx_segment]['words'][0]['word']}'
            reconstruction_segments[idx_segment]['words'][-1]['word'] = f'{reconstruction_segments[idx_segment]['words'][-1]['word']}**'

missing_segments= []
for idx_segment in range(len(reconstruction_segments)):
    if reconstruction_segments[idx_segment]['speaker'] not in SPEAKERS:
        missing_segments.append([idx_segment,reconstruction_segments[idx_segment]])
for segment in missing_segments:
    print (f'{segment[0]} --{segment[1]['speaker']}: {segment[1]['text']}')
len(missing_segments)

{'SPEAKER_02': '16778242 Kristin Bittinge'}

21 --SPEAKER_04: Hi, I'm Tung-Tung Hsieh.
26 --SPEAKER_01: Hello.
27 --SPEAKER_03: Um, so understand you're right.
28 --SPEAKER_00: I
202 --SPEAKER_04: OK.
219 --SPEAKER_04: where my post off in the
225 --SPEAKER_04: Okay.
297 --SPEAKER_03: Thank you.
324 --SPEAKER_00: In in the Carol lab, they're actually Yeah, in the Carol.
341 --SPEAKER_00: Um, hmm.
347 --SPEAKER_03:  Thank you.
421 --SPEAKER_00: Yes.
438 --SPEAKER_00: Yes.
457 --SPEAKER_00: Excel.
458 --SPEAKER_00:  Yeah.
469 --SPEAKER_00: I wish, you know.
476 --SPEAKER_04: Thank you.
479 --SPEAKER_03: OK.
495 --SPEAKER_00: Just wanna reiterate,
500 --SPEAKER_00: And so thank you.
501 --SPEAKER_00: Thank you.
506 --SPEAKER_00: OK.

22

In [73]:
LOG['n_total_assigned_segments_round4'] =len(reconstruction_segments)-len(missing_segments)
LOG['%_assigned_segments_round4'] =(len(reconstruction_segments)-len(missing_segments))/len(reconstruction_segments)
LOG

{'n_total_words': 7322,
 'n_total_segments': 505,
 'n_mapped_words': 7078,
 'n_total_assigned_segments_round1': 483,
 '%_assigned_segments_round1': 0.9507874015748031,
 'n_total_assigned_segments_round2': 485,
 '%_assigned_segments_round2': 0.9547244094488189,
 'n_total_assigned_segments_round3': 485,
 '%_assigned_segments_round3': 0.9547244094488189,
 'n_total_assigned_segments_round4': 486,
 '%_assigned_segments_round4': 0.9566929133858267}

In [74]:
LOG['missing_segments'] = len(missing_segments)

In [75]:
SPEAKERS_realName = {}
for speaker in SPEAKERS:
    name  = speaker.replace('only_','').split('_')[-1]
    SPEAKERS_realName[speaker] =name
# # SPEAKERS_realName['Debalina_Sarkar']  = 'Debalina Sarkar'
# # SPEAKERS_realName['mark_varvares'] = 'Mark Varvares'
# # SPEAKERS_realName['Wayne_Marasco']  = 'Wayne Marasco'
# # SPEAKERS_realName['Ken_Tanabe']  = 'Ken Tanabe'

SPEAKERS_realName

{'16778242 Kristin Bittinge': '16778242 Kristin Bittinge',
 '16781314 Marsha Moses': '16781314 Marsha Moses',
 '16790530 Zhongcong Xie': '16790530 Zhongcong Xie',
 '16797698 David Paul': '16797698 David Paul',
 '16806914 Rich Goldstein': '16806914 Rich Goldstein',
 '16807938 Allison Bialas': '16807938 Allison Bialas'}

In [76]:
reconstruction_words = []
for segment in reconstruction_segments:
    speaker = segment['speaker']
    for word in segment['words']:
        if speaker in SPEAKERS_realName:
            speaker = SPEAKERS_realName[speaker]
        word['speaker']= speaker
    reconstruction_words = reconstruction_words + segment['words']

In [77]:
result=  build_segments(reconstruction_words)
for segment in result[:30]:
    print (f'{segment['start']} - {segment['end']}  {segment['speaker']}: {segment['text']}')
    print ('')

3.48 - 79.707  16778242 Kristin Bittinge: So I'm Kristen Bittinger. I'm Chief Integrity Officer at Harvard Medical School. I'm joined by Rachel Fouchier, the Executive Coordinator at Academic and Research Integrity at Harvard Medical School. Fariba Humin, the Chief Compliance Officer at Boston Children's Hospital. Stephen Cox, Program Manager in Research Integrity at Harvard Medical School. Aaron Walsh, Program Manager in Research Integrity at Harvard Medical School. Daniel Wainstock, our Director for Research Integrity at Harvard Medical School. Heather Quay, Legal Counsel at Harvard University. Gretchen Brodnicki, Dean for Faculty and Research Integrity and the Research Integrity Officer at Harvard Medical School. Mary Walsh, our Chief Scientific Investigator at Harvard Medical School. Blake Calvert, Scientific Investigator at Harvard Medical School. Gus Cervini, Vice President for Research Administration at Boston Children's Hospital. I'm then going to turn it over to Dr. Moses, but I first want to thank you both for joining us today. And again, the panel knows that you want to make an opening statement, but I'll just let Dr. Moses introduce herself and the panel members introduce themselves first. Thank you.

81.148 - 101.601  16781314 Marsha Moses: Thanks, Kristen. Dr. Bialis, we're just going to quickly introduce ourselves, have you guys introduce yourselves, and then we can begin the conversation. So as you know, I'm Marcia Moses. I'm the director of the Vascular Biology Program at Boston Children's Hospital, and I'm on the faculty at HMS.

104.427 - 111.39  16797698 David Paul: Hi, I'm David Paul. I'm a professor of neurobiology in the Department of Neurobiology on the Quadrangle.

113.611 - 115.131  SPEAKER_04: Hi, I'm Tung-Tung Hsieh.

115.231 - 120.273  16790530 Zhongcong Xie: I'm the professor of anesthesia, and I'm working at the Mass General Hospital.

120.293 - 130.817  16807938 Allison Bialas: Hi, thank you. So I'm Allison Bialas, and my lawyer, Richard Goldstein, is also on the call.

131.417 - 131.978  16806914 Rich Goldstein: Hello, everyone.

131.998 - 132.998  SPEAKER_01: Hello.

135.177 - 138.459  SPEAKER_03: Um, so understand you're right.

137.238 - 137.258  SPEAKER_00: I

138.579 - 142.961  16781314 Marsha Moses: You want to make make a statement and we're happy to hear that. So it's all yours.

143.942 - 1086.166  16807938 Allison Bialas: Okay, thank you. So first of all, I just want to thank you all for taking time to meet with me today. And for all the time you're having to spend on reviewing my case. For my statement today, I won't spend time going through each allegation. I have already written a lot. I prepared a lengthy stipulation covering the errors, the errors I knew about in all four of the publications. I'm not aware of any other errors in those publications. I submitted an admission, additional statements to the inquiry committee, and I've met with staff on numerous occasions. I've also submitted documents to Dr. Stevens detailing the locations of all the data and analysis I could find, along with several options for work that could be done to correct the paper. I worked closely with Dr. Carroll for several months to find data, review the data and rerun experiments. And I answered any questions you had associated with my work. Hopefully you all had access to all of that. I reviewed these items for this interview and I will do my best to answer questions you have about them. This has been a very long, very hard two and a half years. The last thing I wanted to do was to have to come before you today. For me, finding the words to express how truly sorry I am feels impossible, and saying anything to defend myself feels unfair to Dr. Stephens and Dr. Carroll. But given all the time you have spent dealing with this, I wanted you to have a chance to meet me and to get an introduction to who I am and a sense of my state of mind during the time when I was working in the Stephens lab and in the later years in the Carroll lab. Then if you have questions about specific allegations, I'll try to answer them. So first of all, I want to start by telling you that my education has always been one of the most important things in my life. Before I came to Harvard, I had many scholastic achievements, of which I was very proud. I was valedictorian of my high school class. I graduated from Cornell with a 4.0. I had never been anything other than a great student who loved learning and solving problems. I'm sorry, this is what drew me to academic research. I came to graduate school directly after college with undergraduate experience in a Drosophila neuroscience lab and summer internships in immunology labs and at a biotech company. I had never worked on the kind of multi-year project where it was necessary to combine data collected over a long period into a coherent story. I had never published a paper. I admit that I made these errors and mistakes, which I spelled out in the stipulation. I wish that I had caught these errors. There may be other errors that I'm not aware of. Should my superiors and co-authors have caught these errors, maybe. It's not for me to judge, that's your job. Many of the errors occurred when I was a grad student in a brand new, very small lab. When I started, The Stevens Lab did not have set protocols in terms of data management and record keeping, and I was inexperienced with these kinds of things. It was the kind of scenario where I didn't even know all the things that I didn't know. There's a lot more than I thought required to correctly assemble a manuscript. Dr. Stevens and I met regularly, but our discussions usually centered around the fun stuff, what experiments were needed to move projects forward. Dr. Stephens and I changed the goals of my project, the flow of the data, and the most important experiments for me to focus on very frequently, at times weekly or even daily, to try to come up with the most compelling way to tell the story of my project. I had dozens of figure outlines, some of which had placeholder figures, some with more complete figures, and I think in some cases, That may have been how I got confused with the ends and had some of the groups having N equals six and some only having N equals three. Errors can propagate when you've been through a process, when you've never been through a process before and you don't realize what documents you generate along the way will ultimately feed into your final product. I think some consideration has to be given for my very junior status at the time and the lab environment I was in. I was in training. I was not an experienced scientist. but I was a very enthusiastic and perhaps too enthusiastic student. I never said no to any opportunity to learn something new or to help someone out, and I quickly became overcommitted. Also, the lab grew relatively quickly. Despite my inexperience, I became a senior member of the lab within a few months of starting there in 2008, when I was still a first year graduate student. As the years went by, especially around the time when I was preparing my thesis and the nature neuroscience paper, I rarely had quiet time when I was preparing, or I rarely had quiet time to sit at my desk, think about my project, and review my work. I felt as though I was constantly being interrupted by someone who needed me for something. For that reason, I ended up writing most of my thesis at home after lab, working late into the night, a time when no one is really at their best. On top of that, I often had issues accessing data and programs through the VPN and would have to go back into lab for that. So basically my analysis, writing, and figure making were more often than not occurring in fits and spurts. I always tried my best, but the cards were stacked against me in some ways because of who I am, all the things I chose to take on, and my inability to drown out the noise and focus on the most important parts of being a graduate student. When working on my thesis and the Nature Neuroscience paper, I really tried to be and thought that I was accurate and correct. I didn't knowingly let errors slip into the papers, but they did. As I was finishing my thesis and writing my Nature Neuroscience paper, Beth asked me to help with a collaborative project that eventually became the 2016 Nature paper, or the C4 paper, I'll call it sometimes. I continued working on this project in the Carroll Lab, as I started to pursue the separate project that became my 2017 Nature paper. I mention this just because based on my explanation of the errors in the C4 paper in my stipulation, the inquiry report did not include any kind of misconduct in the C4 paper. And these data were collected in the Carroll Lab as well. I freely admit I made errors in my portion of that paper. Despite that, my explanation seemed sufficient to show that this mistake was an honest error. There are other examples of errors in my stipulation that were also not included in the inquiry report as allegations of misconduct. The point I'm trying to make is that mistakes alone are not evidence of misconduct, even if there are a lot of them. I don't think, excuse me, I don't think you should view the mistakes in the thesis and the nature neuroscience paper as a prelude to the misconduct in the lupus paper because the earlier mistakes occurred when I was in a different place and a very different state of mind. Starting in the Carroll lab was a very different place than starting in the Stevens lab because it was a well-established lab with standard practices in place. One of the common practices was to send Dr. Carroll progress reports each week and to present at lab meeting each week. Dr. Carroll never expressed any concerns about my work. However, I was the only neuroscientist in the lab and I was doing many techniques that no one else was doing. Because of this, I had to be pretty independent. I relied on my experience in the Stevens Lab, which at the time I thought, you know, was adequate training. However, even though I was now working in the Carroll Lab, I kept getting pulled into things with the Stevens Lab. I was still maintaining a mouse colony there. I was writing grant progress reports. I was reviewing papers, continuing experiments, and advising some students. At times, the stress over maintaining my relationships with my former and current advisor was all-consuming for me because I cared very, very much about not letting anyone down. I let myself get overwhelmed, both physically and emotionally, and at a certain point, it just became too much. After years of increasing pressures and responsibilities, some of which were self-inflicted, I reached a point while in the Carroll Lab, and I've admitted this. When I was working on the lupus paper, I cut some corners and I made some assumptions that I know were not acceptable. My initial enthusiasm for science, which I experienced when I was in the Stevens Lab, and which I hoped would continue during my postdoc, was replaced by irritability and anxiety. At many times while I was in the Carroll Lab, I felt so overwhelmed that I just stopped caring about the quality of my work. Looking back on it, this was new to me. Unlike the positive excitement I felt when I was in the Stevens Lab, where I tried to do my best, after I had been a postdoc for a couple of years, I just started making impulsive and reckless decisions. For example, when I was in the CARE lab, I completely neglected to record anything in my lab notebook to document behavioral characterization I did. I didn't save the raw data, and I exported the data in such a disorganized way that it was almost guaranteed to cause mix-ups. I never did anything like that when I was under Dr. Stevens' supervision. I admit I committed reckless misconduct when it came to my 2017 paper, but I want you to understand that my earlier mistakes were of a different kind and quality. It doesn't make sense to assume that because I committed misconduct on the 2017 paper, that all earlier errors are also misconduct. I was in a different stage of my training when I was writing the 2017 paper. I was in a different lab and working on a paper with many collaborators rather than just doing everything myself. The research issues were different, the projects were separate, and they happened years apart. Most importantly, I was in a totally different frame of mind. I felt I was on the verge of a great career in academia. I had positive feedback from many of my colleagues all along the way, including Dr. Stevens and Dr. Carroll, that I had what it took to be a PI. And it's very hard to admit that they were wrong about me and that I was wrong about myself. And over the past couple of years during this process, I've done a lot of soul searching to try to have a better grasp of what happened so I can make sure that it never happens again. And with the help of medical professionals, I've realized some things about myself that weren't apparent to me when I was working on my graduate and postdoc projects that kind of set me up to fail from early on. Others may have seen it, but I didn't. I guess it's stating the obvious to say that I am poorly suited to the type of environment I found myself in. During my training, I can be a very enthusiastic and energetic person in bursts. Every idea sounds super exciting, and I just want to do it all. With short-term goals, even on a tight deadline, I can usually deliver, and sometimes at a high level of success. I think I was doing okay, just okay, when I was in the Stevens Lab. But with longer projects, both personally and professionally, I now recognize that my high energy and enthusiasm is not sustained. I run out of steam and I lose my focus and motivation. I become overwhelmed when commitments start to pile up. I make mistakes and I fail to deliver at the same level. This was especially true in the Carroll lab. When I felt the stress of the commitments I carried over from the Stevens lab and new pressures from the Carroll lab converging. I love science. I want to be successful, and now that I recognize and I'm addressing my issues with an appropriate support system, I think I still have a lot to offer, and it just won't be as a PI in academic science. I am very sorry for how this all turned out. I disappointed a lot of people, and the good reputation I had is gone. My career as an academic scientist is over. Paper retractions were deemed necessary, and valuable research resources have been diverted. I feel so terrible about all of this, and I will never forgive myself for it. Dr. Carroll and Dr. Stephens may read this statement, and I don't quite know what to say to them, except that I'm so sorry, and I hope that someday they can understand. However, these negative outcomes do not change the fact that I never knowingly or intentionally put false or fabricated data in any paper. I want to be very clear about that. When it came to the lupus paper, should I have checked with Dr. Carroll and asked for more help from him and my co-authors? Absolutely. If I had made an effort to involve them more and been more open about my struggles, my errors could have been avoided. I realized that when it came to the Nature Neuroscience paper and my thesis, I would have benefited from asking Dr. Stevens to go over it in painstaking detail. Should I have insisted that she do this with me? Yes, looking back, I'm sure it would have helped, but at the time I really didn't see the problems with my work. In her testimony to the inquiry committee, Dr. Stephens said she never saw any red flags, and a lot of people read my Nature Neuroscience paper. None of them saw any problems either, and neither did I. Research misconduct is meant to discipline those who don't care about the truth. It's not meant to identify those who do care and fail. I know and deeply regret that I crossed a line with respect to the 2017 paper. I ran out of steam and ended up making impulsive, reckless decisions to try to keep up with my commitments. However, when it came to my thesis, the Nature Neuroscience paper, and the C4 paper, I thought I was as careful and diligent as I could be. I realize now that my efforts were not sufficient. No matter how well or poorly I did my job, For the projects I worked on in the Stevens Lab and with the C4 paper, I always cared about trying to do my best. Going through this process has been a wake-up call for me in many ways. And all I can do is take what I've learned from this process, start over, and do better. Thank you for your attention. So now, I guess, if you guys have any questions on anything.

1093.834 - 1115.824  16797698 David Paul: I'm curious to hear more about how you interacted with Dr. Stevens, whether it was common to have Dr. Stephens look at the raw data. What sort of procedures did you employ for the review of that kind of material?

1117.785 - 1187.84  16807938 Allison Bialas: So in terms of reviewing the raw data, that didn't really happen. Dr. Stephens and I would meet and go over the graphs of my work. and plan, you know, what other experiments were needed. But we didn't ever really go over the raw data. And as she mentioned in her statement, you know, we never had an exit interview even when I left the lab, because we were kind of still working together. So there was never even a discussion of, you know, where is everything located? And there was never a discussion that I should, for example, when I'm putting together the manuscript, have all the data organized by figure and maybe for other people that was, you know, common sense. But for me, it's just wasn't the way that, you know, I thought about things. I just had never been through the process and nobody ever asked to look at that. So as long as I felt in my head, I knew where things were. I thought that's all that mattered. And I thought I did. I thought I knew where everything was and that I was on top of everything, but clearly I was not.

1190.251 - 1193.492  16797698 David Paul: So go ahead, doctor.

1194.512 - 1197.653  16790530 Zhongcong Xie: Dr. Paul, you can finish first.

1198.593 - 1201.653  16797698 David Paul: No, that's fine. Go ahead.

1201.833 - 1201.933  SPEAKER_04: OK.

1201.953 - 1222.8  16790530 Zhongcong Xie: Well, so thank you for your time, I want to say, because for the past many times, we hear a story from one side. But I'm glad today we have time and opportunity to hear a story from your side. So I have two questions for now. First, you said you are repeating some experiment with Dr. Stevens. And how did it go?

1224.14 - 1265.6  16807938 Allison Bialas: So I'm actually not repeating experiments with Dr. Stevens. She didn't want me to be involved in repeating any of the experiments. I have, you know, gotten emails from her and from a technician in her lab, Arno. who I had worked with previously. So he emailed me along the way to ask questions about, you know, how I did some of the experiments and to make sure he was trying to replicate my efforts. But I really haven't gotten any concrete notification from Beth in terms of what figures have repeated and which ones haven't. Yeah.

1267.069 - 1279.298  16790530 Zhongcong Xie: Good, thank you. So my second question is kind of like Dr. David post question. So for example, I'll give you my example. So fellow and show me their data

1274.895 - 1280.299  SPEAKER_04: where my post off in the

1280.339 - 1280.679  16807938 Allison Bialas: prism.

1281.82 - 1295.971  16790530 Zhongcong Xie: And I will also not to see the raw data in the prism, not in the not in the notebook. So I just wondering, you and Dr. Best even have any chance she can go over your pre graph prism data.

1297.42 - 1302.641  16807938 Allison Bialas: No, we never looked at prism graphs together either. We just looked at PowerPoints basically.

1304.921 - 1305.201  SPEAKER_04: Okay.


In [78]:

# output_fileName = os.path.join(output_dir,f'reconstruction-{project_name}.txt')
output_fileName = os.path.join(f'reconstruction-{project_name}.txt')

with open( output_fileName, "w", encoding="utf-8-sig") as f:
                get_speaker_aware_transcript(result, f)

## Filling Missing- Adjustments

In [79]:
current_reconstruction = copy.deepcopy(reconstruction_words)

In [80]:
## get new ids:
for idx in range(len(current_reconstruction)):
    word = current_reconstruction[idx]
    word['idx'] = idx

## sanity check of Index
ids=[]
for idx in range(1, len(current_reconstruction)):
    current_idx = int(current_reconstruction[idx]['idx'])
    prev_idx = int(current_reconstruction[idx-1]['idx'])
    if prev_idx+1 != current_idx:
        print ('Error in ordering')

In [81]:
## get assigned words
assigned_words =[]
for word in current_reconstruction:
    if word['speaker'] in SPEAKERS:
        assigned_words.append(word['idx'])

In [82]:
master_text = ''
master_words= current_reconstruction
for idx_reconstruction in range(len(current_reconstruction)):
      word = current_reconstruction[idx_reconstruction]
      text = current_reconstruction[idx_reconstruction]['word']
      master_text += f' {text}'

## find speakers with matching sequences, and use it to find who said each word.
wordidx_2speaker={}
for speaker in SPEAKERS:
    speaker_text =''
    speaker_words=[]
    prediction_segments = speaker_stt[speaker]['segments']
    for idx_sorted in range(len(prediction_segments)):
            text = prediction_segments[idx_sorted]['text']
            words = prediction_segments[idx_sorted]['words']
            if len(words) == len(text.split()):
                speaker_text += f' {text}'
                speaker_words = speaker_words + words

    matches = unique_common_sequences(remove_punctuation(master_text.lower()), remove_punctuation(speaker_text.lower()), min_len=3)
    for match in matches:
        match_text, match_refIdx, match_predIdx, match_n = match
        for idx in np.arange(match_refIdx, match_n+match_refIdx,1):
            if idx in assigned_words:
                continue
            if idx not in wordidx_2speaker:
                wordidx_2speaker[idx]=[]
            wordidx_2speaker[idx].append([speaker, match_n])

In [83]:
## sort idx
wordidx_2speaker = sort_dict_by_key(wordidx_2speaker)

In [84]:
len(wordidx_2speaker)

13

In [85]:
## clean speakers with duplicates
wordidx_2speaker_clean ={}
for idx in wordidx_2speaker:
    speakers = wordidx_2speaker[idx]
    if len(speakers) == 1:
        wordidx_2speaker_clean[idx] = speakers[0][0]
    else:
        if idx!=0 and idx-1 in wordidx_2speaker_clean:
            old_speaker =  wordidx_2speaker_clean[idx-1]

            ## get the len of the old common sequence
            for speaker in wordidx_2speaker[idx-1]:
                if old_speaker == speaker[0]:
                    old_score= speaker[1]
                    
            ## get the len of the current sequence
            updated_speakers=[]
            for speaker in speakers:
                speaker_name = speaker[0]
                speaker_score = speaker[1]
                if speaker_name==old_speaker:
                    speaker_score = speaker_score+old_score
                updated_speakers.append([speaker_name, speaker_score])
            
            
            potential_next= get_highest_match(updated_speakers)

            for speaker in speakers:
                speaker_name = speaker[0]
                speaker_score = speaker[1]
                if speaker_name== old_speaker and speaker_score>potential_next[1]:
                        wordidx_2speaker_clean[idx] = speaker_name
                        break

                    
            # if next_:
            #     wordidx_2speaker_clean[idx] = next_[0]
            wordidx_2speaker[idx] = updated_speakers

In [86]:
wordidx_2speaker_clean

{3378: '16807938 Allison Bialas',
 3379: '16807938 Allison Bialas',
 4428: '16797698 David Paul',
 4872: '16807938 Allison Bialas',
 4878: '16807938 Allison Bialas',
 4879: '16807938 Allison Bialas',
 4880: '16807938 Allison Bialas',
 4881: '16807938 Allison Bialas',
 7201: '16807938 Allison Bialas'}

In [87]:
for word_idx in wordidx_2speaker_clean:
    if current_reconstruction[word_idx]['speaker'] in SPEAKERS:
        print (f'{word_idx} is already assigned. Error')
    else:
         current_reconstruction[word_idx]['speaker'] =  wordidx_2speaker_clean[word_idx]

In [88]:
result=  build_segments(current_reconstruction)
for segment in result[:100]:
    print (f'{segment['start']} - {segment['end']}  {segment['speaker']}: {segment['text']}')
    print ('')

3.48 - 79.707  16778242 Kristin Bittinge: So I'm Kristen Bittinger. I'm Chief Integrity Officer at Harvard Medical School. I'm joined by Rachel Fouchier, the Executive Coordinator at Academic and Research Integrity at Harvard Medical School. Fariba Humin, the Chief Compliance Officer at Boston Children's Hospital. Stephen Cox, Program Manager in Research Integrity at Harvard Medical School. Aaron Walsh, Program Manager in Research Integrity at Harvard Medical School. Daniel Wainstock, our Director for Research Integrity at Harvard Medical School. Heather Quay, Legal Counsel at Harvard University. Gretchen Brodnicki, Dean for Faculty and Research Integrity and the Research Integrity Officer at Harvard Medical School. Mary Walsh, our Chief Scientific Investigator at Harvard Medical School. Blake Calvert, Scientific Investigator at Harvard Medical School. Gus Cervini, Vice President for Research Administration at Boston Children's Hospital. I'm then going to turn it over to Dr. Moses, but I first want to thank you both for joining us today. And again, the panel knows that you want to make an opening statement, but I'll just let Dr. Moses introduce herself and the panel members introduce themselves first. Thank you.

81.148 - 101.601  16781314 Marsha Moses: Thanks, Kristen. Dr. Bialis, we're just going to quickly introduce ourselves, have you guys introduce yourselves, and then we can begin the conversation. So as you know, I'm Marcia Moses. I'm the director of the Vascular Biology Program at Boston Children's Hospital, and I'm on the faculty at HMS.

104.427 - 111.39  16797698 David Paul: Hi, I'm David Paul. I'm a professor of neurobiology in the Department of Neurobiology on the Quadrangle.

113.611 - 115.131  SPEAKER_04: Hi, I'm Tung-Tung Hsieh.

115.231 - 120.273  16790530 Zhongcong Xie: I'm the professor of anesthesia, and I'm working at the Mass General Hospital.

120.293 - 130.817  16807938 Allison Bialas: Hi, thank you. So I'm Allison Bialas, and my lawyer, Richard Goldstein, is also on the call.

131.417 - 131.978  16806914 Rich Goldstein: Hello, everyone.

131.998 - 132.998  SPEAKER_01: Hello.

135.177 - 138.459  SPEAKER_03: Um, so understand you're right.

137.238 - 137.258  SPEAKER_00: I

138.579 - 142.961  16781314 Marsha Moses: You want to make make a statement and we're happy to hear that. So it's all yours.

143.942 - 1086.166  16807938 Allison Bialas: Okay, thank you. So first of all, I just want to thank you all for taking time to meet with me today. And for all the time you're having to spend on reviewing my case. For my statement today, I won't spend time going through each allegation. I have already written a lot. I prepared a lengthy stipulation covering the errors, the errors I knew about in all four of the publications. I'm not aware of any other errors in those publications. I submitted an admission, additional statements to the inquiry committee, and I've met with staff on numerous occasions. I've also submitted documents to Dr. Stevens detailing the locations of all the data and analysis I could find, along with several options for work that could be done to correct the paper. I worked closely with Dr. Carroll for several months to find data, review the data and rerun experiments. And I answered any questions you had associated with my work. Hopefully you all had access to all of that. I reviewed these items for this interview and I will do my best to answer questions you have about them. This has been a very long, very hard two and a half years. The last thing I wanted to do was to have to come before you today. For me, finding the words to express how truly sorry I am feels impossible, and saying anything to defend myself feels unfair to Dr. Stephens and Dr. Carroll. But given all the time you have spent dealing with this, I wanted you to have a chance to meet me and to get an introduction to who I am and a sense of my state of mind during the time when I was working in the Stephens lab and in the later years in the Carroll lab. Then if you have questions about specific allegations, I'll try to answer them. So first of all, I want to start by telling you that my education has always been one of the most important things in my life. Before I came to Harvard, I had many scholastic achievements, of which I was very proud. I was valedictorian of my high school class. I graduated from Cornell with a 4.0. I had never been anything other than a great student who loved learning and solving problems. I'm sorry, this is what drew me to academic research. I came to graduate school directly after college with undergraduate experience in a Drosophila neuroscience lab and summer internships in immunology labs and at a biotech company. I had never worked on the kind of multi-year project where it was necessary to combine data collected over a long period into a coherent story. I had never published a paper. I admit that I made these errors and mistakes, which I spelled out in the stipulation. I wish that I had caught these errors. There may be other errors that I'm not aware of. Should my superiors and co-authors have caught these errors, maybe. It's not for me to judge, that's your job. Many of the errors occurred when I was a grad student in a brand new, very small lab. When I started, The Stevens Lab did not have set protocols in terms of data management and record keeping, and I was inexperienced with these kinds of things. It was the kind of scenario where I didn't even know all the things that I didn't know. There's a lot more than I thought required to correctly assemble a manuscript. Dr. Stevens and I met regularly, but our discussions usually centered around the fun stuff, what experiments were needed to move projects forward. Dr. Stephens and I changed the goals of my project, the flow of the data, and the most important experiments for me to focus on very frequently, at times weekly or even daily, to try to come up with the most compelling way to tell the story of my project. I had dozens of figure outlines, some of which had placeholder figures, some with more complete figures, and I think in some cases, That may have been how I got confused with the ends and had some of the groups having N equals six and some only having N equals three. Errors can propagate when you've been through a process, when you've never been through a process before and you don't realize what documents you generate along the way will ultimately feed into your final product. I think some consideration has to be given for my very junior status at the time and the lab environment I was in. I was in training. I was not an experienced scientist. but I was a very enthusiastic and perhaps too enthusiastic student. I never said no to any opportunity to learn something new or to help someone out, and I quickly became overcommitted. Also, the lab grew relatively quickly. Despite my inexperience, I became a senior member of the lab within a few months of starting there in 2008, when I was still a first year graduate student. As the years went by, especially around the time when I was preparing my thesis and the nature neuroscience paper, I rarely had quiet time when I was preparing, or I rarely had quiet time to sit at my desk, think about my project, and review my work. I felt as though I was constantly being interrupted by someone who needed me for something. For that reason, I ended up writing most of my thesis at home after lab, working late into the night, a time when no one is really at their best. On top of that, I often had issues accessing data and programs through the VPN and would have to go back into lab for that. So basically my analysis, writing, and figure making were more often than not occurring in fits and spurts. I always tried my best, but the cards were stacked against me in some ways because of who I am, all the things I chose to take on, and my inability to drown out the noise and focus on the most important parts of being a graduate student. When working on my thesis and the Nature Neuroscience paper, I really tried to be and thought that I was accurate and correct. I didn't knowingly let errors slip into the papers, but they did. As I was finishing my thesis and writing my Nature Neuroscience paper, Beth asked me to help with a collaborative project that eventually became the 2016 Nature paper, or the C4 paper, I'll call it sometimes. I continued working on this project in the Carroll Lab, as I started to pursue the separate project that became my 2017 Nature paper. I mention this just because based on my explanation of the errors in the C4 paper in my stipulation, the inquiry report did not include any kind of misconduct in the C4 paper. And these data were collected in the Carroll Lab as well. I freely admit I made errors in my portion of that paper. Despite that, my explanation seemed sufficient to show that this mistake was an honest error. There are other examples of errors in my stipulation that were also not included in the inquiry report as allegations of misconduct. The point I'm trying to make is that mistakes alone are not evidence of misconduct, even if there are a lot of them. I don't think, excuse me, I don't think you should view the mistakes in the thesis and the nature neuroscience paper as a prelude to the misconduct in the lupus paper because the earlier mistakes occurred when I was in a different place and a very different state of mind. Starting in the Carroll lab was a very different place than starting in the Stevens lab because it was a well-established lab with standard practices in place. One of the common practices was to send Dr. Carroll progress reports each week and to present at lab meeting each week. Dr. Carroll never expressed any concerns about my work. However, I was the only neuroscientist in the lab and I was doing many techniques that no one else was doing. Because of this, I had to be pretty independent. I relied on my experience in the Stevens Lab, which at the time I thought, you know, was adequate training. However, even though I was now working in the Carroll Lab, I kept getting pulled into things with the Stevens Lab. I was still maintaining a mouse colony there. I was writing grant progress reports. I was reviewing papers, continuing experiments, and advising some students. At times, the stress over maintaining my relationships with my former and current advisor was all-consuming for me because I cared very, very much about not letting anyone down. I let myself get overwhelmed, both physically and emotionally, and at a certain point, it just became too much. After years of increasing pressures and responsibilities, some of which were self-inflicted, I reached a point while in the Carroll Lab, and I've admitted this. When I was working on the lupus paper, I cut some corners and I made some assumptions that I know were not acceptable. My initial enthusiasm for science, which I experienced when I was in the Stevens Lab, and which I hoped would continue during my postdoc, was replaced by irritability and anxiety. At many times while I was in the Carroll Lab, I felt so overwhelmed that I just stopped caring about the quality of my work. Looking back on it, this was new to me. Unlike the positive excitement I felt when I was in the Stevens Lab, where I tried to do my best, after I had been a postdoc for a couple of years, I just started making impulsive and reckless decisions. For example, when I was in the CARE lab, I completely neglected to record anything in my lab notebook to document behavioral characterization I did. I didn't save the raw data, and I exported the data in such a disorganized way that it was almost guaranteed to cause mix-ups. I never did anything like that when I was under Dr. Stevens' supervision. I admit I committed reckless misconduct when it came to my 2017 paper, but I want you to understand that my earlier mistakes were of a different kind and quality. It doesn't make sense to assume that because I committed misconduct on the 2017 paper, that all earlier errors are also misconduct. I was in a different stage of my training when I was writing the 2017 paper. I was in a different lab and working on a paper with many collaborators rather than just doing everything myself. The research issues were different, the projects were separate, and they happened years apart. Most importantly, I was in a totally different frame of mind. I felt I was on the verge of a great career in academia. I had positive feedback from many of my colleagues all along the way, including Dr. Stevens and Dr. Carroll, that I had what it took to be a PI. And it's very hard to admit that they were wrong about me and that I was wrong about myself. And over the past couple of years during this process, I've done a lot of soul searching to try to have a better grasp of what happened so I can make sure that it never happens again. And with the help of medical professionals, I've realized some things about myself that weren't apparent to me when I was working on my graduate and postdoc projects that kind of set me up to fail from early on. Others may have seen it, but I didn't. I guess it's stating the obvious to say that I am poorly suited to the type of environment I found myself in. During my training, I can be a very enthusiastic and energetic person in bursts. Every idea sounds super exciting, and I just want to do it all. With short-term goals, even on a tight deadline, I can usually deliver, and sometimes at a high level of success. I think I was doing okay, just okay, when I was in the Stevens Lab. But with longer projects, both personally and professionally, I now recognize that my high energy and enthusiasm is not sustained. I run out of steam and I lose my focus and motivation. I become overwhelmed when commitments start to pile up. I make mistakes and I fail to deliver at the same level. This was especially true in the Carroll lab. When I felt the stress of the commitments I carried over from the Stevens lab and new pressures from the Carroll lab converging. I love science. I want to be successful, and now that I recognize and I'm addressing my issues with an appropriate support system, I think I still have a lot to offer, and it just won't be as a PI in academic science. I am very sorry for how this all turned out. I disappointed a lot of people, and the good reputation I had is gone. My career as an academic scientist is over. Paper retractions were deemed necessary, and valuable research resources have been diverted. I feel so terrible about all of this, and I will never forgive myself for it. Dr. Carroll and Dr. Stephens may read this statement, and I don't quite know what to say to them, except that I'm so sorry, and I hope that someday they can understand. However, these negative outcomes do not change the fact that I never knowingly or intentionally put false or fabricated data in any paper. I want to be very clear about that. When it came to the lupus paper, should I have checked with Dr. Carroll and asked for more help from him and my co-authors? Absolutely. If I had made an effort to involve them more and been more open about my struggles, my errors could have been avoided. I realized that when it came to the Nature Neuroscience paper and my thesis, I would have benefited from asking Dr. Stevens to go over it in painstaking detail. Should I have insisted that she do this with me? Yes, looking back, I'm sure it would have helped, but at the time I really didn't see the problems with my work. In her testimony to the inquiry committee, Dr. Stephens said she never saw any red flags, and a lot of people read my Nature Neuroscience paper. None of them saw any problems either, and neither did I. Research misconduct is meant to discipline those who don't care about the truth. It's not meant to identify those who do care and fail. I know and deeply regret that I crossed a line with respect to the 2017 paper. I ran out of steam and ended up making impulsive, reckless decisions to try to keep up with my commitments. However, when it came to my thesis, the Nature Neuroscience paper, and the C4 paper, I thought I was as careful and diligent as I could be. I realize now that my efforts were not sufficient. No matter how well or poorly I did my job, For the projects I worked on in the Stevens Lab and with the C4 paper, I always cared about trying to do my best. Going through this process has been a wake-up call for me in many ways. And all I can do is take what I've learned from this process, start over, and do better. Thank you for your attention. So now, I guess, if you guys have any questions on anything.

1093.834 - 1115.824  16797698 David Paul: I'm curious to hear more about how you interacted with Dr. Stevens, whether it was common to have Dr. Stephens look at the raw data. What sort of procedures did you employ for the review of that kind of material?

1117.785 - 1187.84  16807938 Allison Bialas: So in terms of reviewing the raw data, that didn't really happen. Dr. Stephens and I would meet and go over the graphs of my work. and plan, you know, what other experiments were needed. But we didn't ever really go over the raw data. And as she mentioned in her statement, you know, we never had an exit interview even when I left the lab, because we were kind of still working together. So there was never even a discussion of, you know, where is everything located? And there was never a discussion that I should, for example, when I'm putting together the manuscript, have all the data organized by figure and maybe for other people that was, you know, common sense. But for me, it's just wasn't the way that, you know, I thought about things. I just had never been through the process and nobody ever asked to look at that. So as long as I felt in my head, I knew where things were. I thought that's all that mattered. And I thought I did. I thought I knew where everything was and that I was on top of everything, but clearly I was not.

1190.251 - 1193.492  16797698 David Paul: So go ahead, doctor.

1194.512 - 1197.653  16790530 Zhongcong Xie: Dr. Paul, you can finish first.

1198.593 - 1201.653  16797698 David Paul: No, that's fine. Go ahead.

1201.833 - 1201.933  SPEAKER_04: OK.

1201.953 - 1222.8  16790530 Zhongcong Xie: Well, so thank you for your time, I want to say, because for the past many times, we hear a story from one side. But I'm glad today we have time and opportunity to hear a story from your side. So I have two questions for now. First, you said you are repeating some experiment with Dr. Stevens. And how did it go?

1224.14 - 1265.6  16807938 Allison Bialas: So I'm actually not repeating experiments with Dr. Stevens. She didn't want me to be involved in repeating any of the experiments. I have, you know, gotten emails from her and from a technician in her lab, Arno. who I had worked with previously. So he emailed me along the way to ask questions about, you know, how I did some of the experiments and to make sure he was trying to replicate my efforts. But I really haven't gotten any concrete notification from Beth in terms of what figures have repeated and which ones haven't. Yeah.

1267.069 - 1279.298  16790530 Zhongcong Xie: Good, thank you. So my second question is kind of like Dr. David post question. So for example, I'll give you my example. So fellow and show me their data

1274.895 - 1275.876  SPEAKER_04: where my post off

1280.119 - 1280.679  16807938 Allison Bialas: in the prism.

1281.82 - 1295.971  16790530 Zhongcong Xie: And I will also not to see the raw data in the prism, not in the not in the notebook. So I just wondering, you and Dr. Best even have any chance she can go over your pre graph prism data.

1297.42 - 1302.641  16807938 Allison Bialas: No, we never looked at prism graphs together either. We just looked at PowerPoints basically.

1304.921 - 1305.201  SPEAKER_04: Okay.


In [89]:
##  Get stats
total_n_blocks = len(result)
missing_blocks= []
missing_words= []
words= []
for i in result:
    words +=  i['text'].split()
    if i['speaker'] not in SPEAKERS:
        missing_blocks.append(i)
        missing_words += i['text'].split()
n_words = len(words)
n_missing_words = len(missing_words)
n_missing_blocks = len(missing_blocks)

LOG['n_missing_words'] = n_missing_words 
LOG['%_missing_words'] = n_missing_words/n_words
LOG['n_missing_blocks'] = total_n_blocks
LOG['%_missing_blocks'] = n_missing_blocks/total_n_blocks
LOG

{'n_total_words': 7322,
 'n_total_segments': 505,
 'n_mapped_words': 7078,
 'n_total_assigned_segments_round1': 483,
 '%_assigned_segments_round1': 0.9507874015748031,
 'n_total_assigned_segments_round2': 485,
 '%_assigned_segments_round2': 0.9547244094488189,
 'n_total_assigned_segments_round3': 485,
 '%_assigned_segments_round3': 0.9547244094488189,
 'n_total_assigned_segments_round4': 486,
 '%_assigned_segments_round4': 0.9566929133858267,
 'missing_segments': 22,
 'n_missing_words': 48,
 '%_missing_words': 0.0065555859054903035,
 'n_missing_blocks': 99,
 '%_missing_blocks': 0.21212121212121213}

In [163]:
output_fileName = os.path.join(f'reconstruction-aligned-{project_name}.txt')

with open( output_fileName, "w", encoding="utf-8-sig") as f:
                get_speaker_aware_transcript(result, f)

## Check speaker-assignment text

In [91]:
import difflib
import re

import pandas as pd
import time
def normalize_with_mapping(text):
    original_tokens = re.findall(r"\S+", text)
    normalized_tokens = [re.sub(r"[^\w]", "", tok).lower() for tok in original_tokens]
    return original_tokens, normalized_tokens


def extract_missing_segments(gt_text, pred_text, include_replacements_as_missing=True):

    gt_orig, gt_norm = normalize_with_mapping(gt_text)
    pred_orig, pred_norm = normalize_with_mapping(pred_text)

    matcher = difflib.SequenceMatcher(None, gt_norm, pred_norm)

    missing = []
    substitutions = []

    for tag, i1, i2, j1, j2 in matcher.get_opcodes():

        if tag == "delete":

            gt_text_seg = " ".join(gt_orig[i1:i2])

            missing.append({
                "text": gt_text_seg,
                "gt_start_idx": i1,
                "gt_end_idx": i2 - 1,
                "gt_token_indices": list(range(i1, i2)),
                "pred_alignment_idx": j1,  # 👈 alignment position in pred
                "op": "delete",
            })

        elif tag == "replace":

            gt_text_seg = " ".join(gt_orig[i1:i2])
            pred_text_seg = " ".join(pred_orig[j1:j2])

            substitutions.append({
                "gt_text": gt_text_seg,
                "pred_text": pred_text_seg,
                "gt_start_idx": i1,
                "gt_end_idx": i2 - 1,
                "pred_start_idx": j1,
                "pred_end_idx": j2 - 1,
                "op": "replace",
            })

            if include_replacements_as_missing and gt_text_seg.strip():
                missing.append({
                    "text": gt_text_seg,
                    "gt_start_idx": i1,
                    "gt_end_idx": i2 - 1,
                    "gt_token_indices": list(range(i1, i2)),
                    "pred_alignment_idx": j1,  # 👈 alignment anchor
                    "op": "replace",
                })

    return {"missing": missing, "substitutions": substitutions}


def find_text_pred(idx, speaker_metadata, missing_segment):
    selected_block= None
    
    if idx == speaker_metadata[-1]['end_token']:
        selected_block = speaker_metadata[-1]
    else:
        for block in speaker_metadata:
            if idx >=block['start_token'] and idx<block['end_token']:
                selected_block = block
                break
    if selected_block:       
        text= selected_block['text']
        index = idx - selected_block['start_token']  
        text = text.split()
        if index ==0:
            missing_segment = f'[{missing_segment} *** OAPS]' ## OR AFTER PREVIOUS SPEECH
        else:
            missing_segment = f'[{missing_segment}]'

        placeholder= '[*******]'

        edited_transcript = text.copy()
        edited_transcript.insert(index, f'{missing_segment}')
        text.insert(index, placeholder)
        start_time = time.strftime('%H:%M:%S', time.gmtime( selected_block['start']))
        end_time = time.strftime('%H:%M:%S', time.gmtime(selected_block['end']))
        dict_ = {'Transcript Text': ' '.join(text), 'Ref-Start Time': start_time, 'Ref-End Time': end_time, 'Edited Transcript': ' '.join(edited_transcript),'block_idx': selected_block['block_idx']}
        return dict_
    return {'Transcript Text': np.nan , 'Ref-Start Time': np.nan, 'Ref-End Time': np.nan, 'Edited Transcript': np.nan, 'block_idx': np.nan}

In [92]:
### GET THE TEXT OF EACH SPEAKER along with metadata

## add ID to each block:
for idx in range(0, len(result)):
    block = result[idx]
    block['block_idx'] = idx

TEXT_SPEAKERS={}
TEXT_SPEAKERS_metadata= {}
for block in result:
    speaker = block['speaker']
    if speaker not in TEXT_SPEAKERS:
        TEXT_SPEAKERS[speaker] = ''
        TEXT_SPEAKERS_metadata[speaker] =[{'start_token': 0, 'end_token':0, 'text': '','start': 0, 'end': 0}]
    text = f'{block['text'].replace('*', '').strip()}'
    TEXT_SPEAKERS[speaker] = f'{TEXT_SPEAKERS[speaker]} {text}'
    n_tokens = len(text.split())
    start_token = TEXT_SPEAKERS_metadata[speaker][-1]['end_token']
    running_token = len(TEXT_SPEAKERS[speaker].split())
    TEXT_SPEAKERS_metadata[speaker].append({'start_token': start_token, 'end_token': start_token+n_tokens, 'text': text, 'start': block['start'], 'end': block['end'], 'running_token': running_token , 'block_idx': block['block_idx']})

In [93]:
SPEAKERS

['16778242 Kristin Bittinge',
 '16781314 Marsha Moses',
 '16790530 Zhongcong Xie',
 '16797698 David Paul',
 '16806914 Rich Goldstein',
 '16807938 Allison Bialas']

In [94]:
## GET GT FROM INDIVIDUAL FILES
TEXT_SPEAKERS_GT = {}
for speaker in SPEAKERS:
    speaker_text=''
    speaker_segments = speaker_stt[speaker]['segments']
    for segment in speaker_segments:
        text = segment['text']
        speaker_text += f' {text}'
    TEXT_SPEAKERS_GT[speaker] = speaker_text

In [95]:
SPEAKERS

['16778242 Kristin Bittinge',
 '16781314 Marsha Moses',
 '16790530 Zhongcong Xie',
 '16797698 David Paul',
 '16806914 Rich Goldstein',
 '16807938 Allison Bialas']

In [96]:
## GET MISSING SEGMENTS BY SPEAKER WITHIN THE TRANSFCRIPT
missing_segments_speakers = {}
for speaker in SPEAKERS:
    print (f'@@@@@@@@@@@@@@@@@ SPEAKER: {speaker}')
    if  speaker not in TEXT_SPEAKERS:
        continue
    pred_text=TEXT_SPEAKERS[speaker]
    gt_text= TEXT_SPEAKERS_GT[speaker]

    ## GET MISSING SEGMENTS
    results = extract_missing_segments(gt_text, pred_text)
    print("MISSING:")
    for m in results["missing"]:
        if m['op'] =='delete':
            print(m["op"], m["gt_start_idx"], "->", m["gt_end_idx"], ":", m["text"])
    
    print("\nSUBSTITUTIONS:")
    for s in results["substitutions"]:
        print(f'{s["gt_text"]}  -->  {s["pred_text"]}')

    missing_segments_speakers[speaker] = results


## Get missing segments
master_operations= []
for speaker in  missing_segments_speakers.keys():
    speaker_operations= []
    results =missing_segments_speakers[speaker]
    for m in results['missing']:
        operation = m['op']
        if operation == 'delete':
            pred_idx = m["pred_alignment_idx"]
            m_data = find_text_pred(pred_idx, TEXT_SPEAKERS_metadata[speaker], m['text'])
            m_data['Missing Text'] = m['text'] 
            m_data['speaker'] = speaker
            m_data['n_words'] = len(m['text'].split())
            speaker_operations.append(m_data)
    master_operations.append(pd.DataFrame(speaker_operations))
master_operations = pd.concat(master_operations)

pd.set_option('display.max_colwidth', None)   # show full content
pd.set_option('display.width', 200)  
master_operations.sort_values('n_words', ascending=False, inplace=True)
# master_operations.to_csv('t.csv')

@@@@@@@@@@@@@@@@@ SPEAKER: 16778242 Kristin Bittinge
MISSING:
delete 177 -> 177 : Ciao.

SUBSTITUTIONS:
Foucher,  -->  Fouchier,
Talbot,  -->  Calvert,
Cerini,  -->  Cervini,
@@@@@@@@@@@@@@@@@ SPEAKER: 16781314 Marsha Moses
MISSING:
delete 49 -> 54 : Hello. So this is D'Andrea Wright.
delete 71 -> 72 : Thank you.
delete 177 -> 178 : you know,
delete 218 -> 218 : were
delete 220 -> 228 : Thank you. Bye. Go ahead, go ahead. Thank you.
delete 247 -> 248 : Silence. you.
delete 271 -> 275 : for you? You know. Thanks.
delete 314 -> 315 : Thank you.

SUBSTITUTIONS:
CARA  -->  Cata
easier  -->  these are your
were  -->  worked
says  -->  as
@@@@@@@@@@@@@@@@@ SPEAKER: 16790530 Zhongcong Xie
MISSING:
delete 0 -> 3 : Hi, I'm Dongdong Xie.
delete 17 -> 25 : Hi. you you you Thank you. you No, no,
delete 95 -> 99 : Oh. Okay. I see. Okay.
delete 124 -> 127 : when my post of
delete 134 -> 136 : in the freedom.
delete 263 -> 264 : the small
delete 340 -> 340 : OK.
delete 378 -> 380 : Thanks for watching!
delete 426 -> 426 : Okay.
delete 482 -> 482 : you
delete 515 -> 516 : But you
delete 533 -> 533 : prism
delete 558 -> 560 : I see. you
delete 592 -> 593 : a story
delete 613 -> 615 : Mm-hmm. Yeah. Sure.
delete 625 -> 626 : Thank you
delete 630 -> 632 : you Thank you.

SUBSTITUTIONS:
freedom,  -->  prism,
I'm  -->  I
pre-graph  -->  pre graph
OK. As a  -->  Other
Steven's  -->  Stephen's
authors,  -->  also
Oh. Oh, yeah. Parallel, sorry. So is there a Sorry.  -->  So
you  -->  you're
hard  -->  hot
p value  -->  p-value
Sometimes  -->  Sometime
analysis  -->  analyze
Or  -->  In the Prism raw.
@@@@@@@@@@@@@@@@@ SPEAKER: 16797698 David Paul
MISSING:
delete 0 -> 2 : Subs by www.zeoranger.co.uk
delete 20 -> 31 : Hello. Yeah. It's Okay. Okay. you Thank you. Thank you. Okay. Okay.
delete 76 -> 78 : I appreciate it.
delete 84 -> 85 : Thank you.

SUBSTITUTIONS:
Stephens,  -->  Stevens,
the Stevens  -->  Stephen's
@@@@@@@@@@@@@@@@@ SPEAKER: 16806914 Rich Goldstein
MISSING:
delete 0 -> 3 : Thank you for watching.

SUBSTITUTIONS:
@@@@@@@@@@@@@@@@@ SPEAKER: 16807938 Allison Bialas
MISSING:
delete 80 -> 80 : Uh,
delete 86 -> 86 : in,
delete 412 -> 415 : I had never been,
delete 698 -> 699 : you know,
delete 2999 -> 3000 : I don't
delete 3005 -> 3007 : Um, you know,
delete 3028 -> 3029 : you know,
delete 3044 -> 3044 : Um,
delete 3052 -> 3052 : like
delete 3095 -> 3095 : like
delete 3118 -> 3119 : you know,
delete 3161 -> 3161 : of
delete 3262 -> 3263 : Okay. Right.
delete 3280 -> 3281 : you know,
delete 3310 -> 3310 : like
delete 3478 -> 3479 : Yep. Yep.
delete 3833 -> 3834 : you know,
delete 3848 -> 3849 : you know,
delete 3875 -> 3876 : you know,
delete 4029 -> 4032 : the Carroll lab, there
delete 4037 -> 4038 : Carroll lab,
delete 4055 -> 4056 : you know,
delete 4231 -> 4231 : Yeah.
delete 4519 -> 4520 : is that
delete 4526 -> 4526 : Okay.
delete 4785 -> 4786 : you know,
delete 4914 -> 4914 : any
delete 4942 -> 4942 : um,
delete 4950 -> 4950 : um,
delete 4970 -> 4970 : um,
delete 4973 -> 4973 : uh,
delete 4976 -> 4976 : um,
delete 4980 -> 4980 : uh,
delete 4991 -> 4991 : Um,
delete 5035 -> 5036 : you know,
delete 5052 -> 5053 : You know,
delete 5063 -> 5064 : you know,
delete 5122 -> 5122 : Um,
delete 5130 -> 5130 : um,
delete 5149 -> 5149 : uh,
delete 5153 -> 5153 : and
delete 5160 -> 5160 : Um,
delete 5187 -> 5187 : um,
delete 5193 -> 5193 : uh,
delete 5349 -> 5349 : Yes.
delete 5375 -> 5375 : of
delete 5508 -> 5508 : Yes.
delete 5740 -> 5742 : Thank you. Okay.
delete 5761 -> 5761 : like
delete 5913 -> 5913 : it's
delete 5959 -> 5961 : Just want to
delete 6004 -> 6007 : So thank you. Okay.

SUBSTITUTIONS:
So I'm. OK,  -->  Okay,
areas  -->  errors
he  -->  you
Stevens  -->  Stephens
Stevens  -->  Stephens
Stephens  -->  Stevens
first-year  -->  first year
CARE  -->  Carroll
an excess.  -->  mix-ups.
Stephens  -->  Stevens
Invaluable  -->  and valuable
Stephens.  -->  Stevens.
we've  -->  we
asked  -->  ask
24-7,  -->  24 seven,
Carroll  -->  Carol
Jessie,  -->  Jesse,
And  -->  Um, and we,
result  -->  results
seq  -->  sequence.
was  -->  is
Dori Schaefer,  -->  Dory Shaper,
in the Prism Rock Excel? Yeah,  -->  Is that,
1B,  -->  figure one B

In [97]:
master_operations

,Transcript Text,Ref-Start Time,Ref-End Time,Edited Transcript,block_idx,Missing Text,speaker,n_words
1,"[*******] I'm curious to hear more about how you interacted with Dr. Stevens, whether it was common to have Dr. Stephens look at the raw data. What sort of procedures did you employ for the review of that kind of material?",00:18:13,00:18:35,"[Hello. Yeah. It's Okay. Okay. you Thank you. Thank you. Okay. Okay. *** OAPS] I'm curious to hear more about how you interacted with Dr. Stevens, whether it was common to have Dr. Stephens look at the raw data. What sort of procedures did you employ for the review of that kind of material?",12,Hello. Yeah. It's Okay. Okay. you Thank you. Thank you. Okay. Okay.,16797698 David Paul,12
1,"[*******] Dr. Paul, you can finish first.",00:19:54,00:19:57,"[Hi. you you you Thank you. you No, no, *** OAPS] Dr. Paul, you can finish first.",15,"Hi. you you you Thank you. you No, no,",16790530 Zhongcong Xie,9
4,"[*******] So Allison, can you just walk us through how you wrote the Nature Neuroscience paper?",00:33:06,00:33:10,"[Thank you. Bye. Go ahead, go ahead. Thank you. *** OAPS] So Allison, can you just walk us through how you wrote the Nature Neuroscience paper?",52,"Thank you. Bye. Go ahead, go ahead. Thank you.",16781314 Marsha Moses,9
0,[*******] You want to make make a statement and we're happy to hear that. So it's all yours.,00:02:18,00:02:22,[Hello. So this is D'Andrea Wright. *** OAPS] You want to make make a statement and we're happy to hear that. So it's all yours.,10,Hello. So this is D'Andrea Wright.,16781314 Marsha Moses,6
6,"[*******] David, do you have any more questions?",00:46:08,00:46:11,"[for you? You know. Thanks. *** OAPS] David, do you have any more questions?",82,for you? You know. Thanks.,16781314 Marsha Moses,5
...,...,...,...,...,...,...,...,...
39,"So there were a lot of people that gave me some help in terms of just reading the paper and giving feedback on whether it [*******] flowed well and seemed to be, you know, okay. For the Nature Neuroscience paper, I had actually, I don't remember everyone who read it, but I had quite a few. I remember, for example, that Beth told me to have Dr. Qinfei Chen read it, who was in our department and who was on my dissertation advisory committee. Larry Benowitz, who is also on my dissertation advisory committee, read it and gave me feedback. Obviously, Beth read it. Dory Shaper, who was a postdoc in the lab, read it. The other postdocs in the lab at the time, which I don't remember exactly how many there were, but I got feedback from quite a number of people on the paper. The 2017 Nature paper, Mike, you know, read it and would give me feedback or edits on what I had written. We had the other authors of the paper read it, but that was really it. And honestly, they didn't provide that much feedback. I think George Sokos, who's one of the authors, probably was one of the more helpful people in reviewing it, but I don't think anybody reviewed it in super careful detail.",00:40:03,00:41:38,"So there were a lot of people that gave me some help in terms of just reading the paper and giving feedback on whether it [uh,] flowed well and seemed to be, you know, okay. For the Nature Neuroscience paper, I had actually, I don't remember everyone who read it, but I had quite a few. I remember, for example, that Beth told me to have Dr. Qinfei Chen read it, who was in our department and who was on my dissertation advisory committee. Larry Benowitz, who is also on my dissertation advisory committee, read it and gave me feedback. Obviously, Beth read it. Dory Shaper, who was a postdoc in the lab, read it. The other postdocs in the lab at the time, which I don't remember exactly how many there were, but I got feedback from quite a number of people on the paper. The 2017 Nature paper, Mike, you know, read it and would give me feedback or edits on what I had written. We had the other authors of the paper read it, but that was really it. And honestly, they didn't provide that much feedback. I think George Sokos, who's one of the authors, probably was one of the more helpful people in reviewing it, but I don't think anybody reviewed it in super careful detail.",64,"uh,",16807938 Allison Bialas,1
40,"So there were a lot of people that gave me some help in terms of just reading the paper and giving feedback on whether it flowed well and [*******] seemed to be, you know, okay. For the Nature Neuroscience paper, I had actually, I don't remember everyone who read it, but I had quite a few. I remember, for example, that Beth told me to have Dr. Qinfei Chen read it, who was in our department and who was on my dissertation advisory committee. Larry Benowitz, who is also on my dissertation advisory committee, read it and gave me feedback. Obviously, Beth read it. Dory Shaper, who was a postdoc in the lab, read it. The other postdocs in the lab at the time, which I don't remember exactly how many there were, but I got feedback from quite a number of people on the paper. The 2017 Nature paper, Mike, you know, read it and would give me feedback or edits on what I had written. We had the other authors of the paper read it, but that was really it. And honestly, they didn't provide that much feedback. I think George Sokos, who's one of the authors, probably was one of the more helpful people in reviewing it, but I don't think anybody reviewed it in super careful detail.",00:40:03,00:41:38,"So there were a lot of people that gave me some help in terms of just reading the paper and giving feedback on whether it flowed well and [and] seemed to be, you know, okay. For the Nature Neuroscience paper, I had actually, I don't remember everyone who read it, but I had quite a few. I remember, for example, that Beth told me to have Dr. Qinfei Chen read it, who was in our department and who was on my dissertation advisory committee. Larry Benowitz, who is also on my dissertation advisory committee, read it and gave me feedback. Obviously, Beth read it. Dory Shaper, who was a postdoc in the lab, read it. The other postdocs in the lab at the time, which I don't remember exactly how many there were, but I got feedback from quite a number of people on the paper. The 2017 Nature paper, Mike, you know, read it and would give me feedback or edits on what I had written. We had the other authors of the paper read it, but that was really it. And honestly, they didn't provide that much feedback. I think George Sokos, who's one of the authors, probably was one of the more helpful people in reviewing it, but I don't think anybody reviewed it in super careful detail.",64,and,16807938 Allison Bialas,1
41,"So there were a lot of people that gave me some help in terms of just reading the paper and giving feedback on whether it flowed well and seemed to be, you know, okay. [*******] For the Nature Neuroscience paper, I had actually, I don't remember everyone who read it, but I had quite a few. I remember, for example, that Beth told me to have Dr. Qinfei Chen read it, who was in our department and who was on my dissertation advisory committee. Larry Benowitz, who is also on my dissertation advisory committee, read it and gave me feedback. Obviously, Beth read it. Dory Shaper, who was a postdoc in the lab, read it. The other postdocs in the lab at the time, which I don't remember exactly how many there were, but I got feedback from quite a number of people on the paper. The 2017 Nature paper, Mike, you know, read it and would give me feedback or edits on what I had written. We had the other authors of the paper read it, but that was really it. And honestly, they didn't provide that much feedback. I think George Sokos, who's one of the authors, probably was one of the more helpful people in reviewing it, but I don't think anybody reviewed it in super careful detail.",00:40:03,00:41:38,"So there were a lot of people that gave me some help in terms of just reading the paper and giving feedback on whether it flowed well and seemed to be, you know, okay. [Um,] For the Nature Neuroscience paper, I had actually, I don't remember everyone who read it, but I had quite a few. I remember, for example, that Beth told me to have Dr. Qinfei Chen read it, who was in our department and who was on my dissertation advisory committee. Larry Benowitz, who is also on my dissertation advisory committee, read it and gave me feedback. Obviously, Beth read it. Dory Shaper, who was a postdoc in the lab, read it. The other postdocs in the lab at the time, which I don't remember exactly how many there were, but I got feedback from quite a number of people on the paper. The 2017 Nature paper, Mike, you know, read it and would give me feedback or edits on what I had written. We had the other authors of the paper read it, but that was really it. And honestly, they didn't provide that much feedback. I think George Sokos, who's one of the authors, probably was one of the more helpful people in reviewing it, but I don't think anybody reviewed it in super careful detail.",64,"Um,",16807938 Allison Bialas,1
42,"So there were a lot of people that gave me some help in terms of just reading the paper and giving feedback on whether it flowed well and seemed to be, you know, okay. For the Nature Neuroscience paper, I had actually, I don't remember everyone who read it, but I had quite a few. I remember, for example, that [*******] Beth told me to have Dr. Qinfei Chen read it, who was in our department and who was on my dissertation advisory committee. Larry Benowitz, who is also on my dissertation advisory committee, read it and gave me feedback. Obviously, Beth read it. Dory Shaper, who was a postdoc in the lab, read it. The other postdocs in the lab at the time, which I don't remember exactly how many there were, but I got feedback from quite a number of people on the paper. The 2017 Nature paper, Mike, you know, read it and would give me feedback or edits on what I had written. We had the other authors of the paper read it, but that was really it. And honestly, they didn't provide that much feedback. I think George Sokos, who's one of the authors, probably was one of the more helpful people in reviewing it, but I don't think anybody reviewed it in super careful detail.",00:40:03,00:41:38,"So there were a lot of people that gave me some help in terms of just reading the paper and giving feedback on whether it flowed well and seemed to be, you know, okay. For the Nature Neuroscience paper, I had actually, I don't remember everyone who read it, but I had quite a few. I remember, for example, that [um,] Beth told me to have Dr. Qinfei Chen read it, who was in our department and who was on my dissertation advisory committee. Larry Benowitz, who is also on my dissertation advisory committee, read it and gave me feedback. Obviously, Beth read it. Dory Shaper, who was a postdoc in the lab, read it. The other postdocs in the lab at the time, which I don't remember exactly how many there were, but I got feedback from quite a number of people on the paper. The 2017 Nature paper, Mike, you know, read it and would give me feedback or edits on what I had written. We had the other authors of the paper read it, but that was really it. And honestly, they didn't provide that much feedback. I think George Sokos, who's one of the authors, probably was one of the more helpful people in reviewing it, but I don't think anybody reviewed it in super careful detail.",64,"um,",16807938 Allison Bialas,1
0,"[*******] Dr. Bayales, I'm going to ask if you and Mr. Goldstein, if I can put you back in the waiting room for just a couple minutes to let the panel debrief for a couple minutes. And then if they have any additional questions, I'll bring you back in. Either way, I'll bring you back in to let you know that we're all set. But it'll just be about five minutes.",00:48:29,00:48:48,"[Ciao. *** OAPS] Dr. Bayales, I'm going to ask if you and Mr. Goldstein, if I can put you back in the waiting room for just a couple minutes to let the panel debrief for a couple minutes. And then if they have any additional questions, I'll bring you back in. Either way, I'll bring you back in to let you know that we're all set. But it'll just be about five minutes.",96,Ciao.,16778242 Kristin Bittinge,1

In [98]:
master_operations.shape

(83, 8)

In [99]:
import sys
sys.path.insert(0, "/app/notebooks/ARI_temp/src/prod/src2")
import missingsegment_utils as missingsegments_helper

df_m = missingsegments_helper.get_missing_segments(pred_result = result, speaker_stt = speaker_stt,output_fileName_withMissing= 't-missing.txt')

@@@@@@@@@@@@@@@@@ SPEAKER: 16778242 Kristin Bittinge
MISSING:
delete 177 -> 177 : Ciao.

SUBSTITUTIONS:
Foucher,  -->  Fouchier,
Talbot,  -->  Calvert,
Cerini,  -->  Cervini,
@@@@@@@@@@@@@@@@@ SPEAKER: 16781314 Marsha Moses
MISSING:
delete 49 -> 54 : Hello. So this is D'Andrea Wright.
delete 71 -> 72 : Thank you.
delete 177 -> 178 : you know,
delete 218 -> 218 : were
delete 220 -> 228 : Thank you. Bye. Go ahead, go ahead. Thank you.
delete 247 -> 248 : Silence. you.
delete 271 -> 275 : for you? You know. Thanks.
delete 314 -> 315 : Thank you.

SUBSTITUTIONS:
CARA  -->  Cata
easier  -->  these are your
were  -->  worked
says  -->  as
@@@@@@@@@@@@@@@@@ SPEAKER: 16790530 Zhongcong Xie
MISSING:
delete 0 -> 3 : Hi, I'm Dongdong Xie.
delete 17 -> 25 : Hi. you you you Thank you. you No, no,
delete 95 -> 99 : Oh. Okay. I see. Okay.
delete 124 -> 127 : when my post of
delete 134 -> 136 : in the freedom.
delete 263 -> 264 : the small
delete 340 -> 340 : OK.
delete 378 -> 380 : Thanks for watching!
delete 426 -> 426 : Okay.
delete 482 -> 482 : you
delete 515 -> 516 : But you
delete 533 -> 533 : prism
delete 558 -> 560 : I see. you
delete 592 -> 593 : a story
delete 613 -> 615 : Mm-hmm. Yeah. Sure.
delete 625 -> 626 : Thank you
delete 630 -> 632 : you Thank you.

SUBSTITUTIONS:
freedom,  -->  prism,
I'm  -->  I
pre-graph  -->  pre graph
OK. As a  -->  Other
Steven's  -->  Stephen's
authors,  -->  also
Oh. Oh, yeah. Parallel, sorry. So is there a Sorry.  -->  So
you  -->  you're
hard  -->  hot
p value  -->  p-value
Sometimes  -->  Sometime
analysis  -->  analyze
Or  -->  In the Prism raw.
@@@@@@@@@@@@@@@@@ SPEAKER: 16797698 David Paul
MISSING:
delete 0 -> 2 : Subs by www.zeoranger.co.uk
delete 20 -> 31 : Hello. Yeah. It's Okay. Okay. you Thank you. Thank you. Okay. Okay.
delete 76 -> 78 : I appreciate it.
delete 84 -> 85 : Thank you.

SUBSTITUTIONS:
Stephens,  -->  Stevens,
the Stevens  -->  Stephen's
@@@@@@@@@@@@@@@@@ SPEAKER: 16806914 Rich Goldstein
MISSING:
delete 0 -> 3 : Thank you for watching.

SUBSTITUTIONS:
@@@@@@@@@@@@@@@@@ SPEAKER: 16807938 Allison Bialas
MISSING:
delete 80 -> 80 : Uh,
delete 86 -> 86 : in,
delete 412 -> 415 : I had never been,
delete 698 -> 699 : you know,
delete 2999 -> 3000 : I don't
delete 3005 -> 3007 : Um, you know,
delete 3028 -> 3029 : you know,
delete 3044 -> 3044 : Um,
delete 3052 -> 3052 : like
delete 3095 -> 3095 : like
delete 3118 -> 3119 : you know,
delete 3161 -> 3161 : of
delete 3262 -> 3263 : Okay. Right.
delete 3280 -> 3281 : you know,
delete 3310 -> 3310 : like
delete 3478 -> 3479 : Yep. Yep.
delete 3833 -> 3834 : you know,
delete 3848 -> 3849 : you know,
delete 3875 -> 3876 : you know,
delete 4029 -> 4032 : the Carroll lab, there
delete 4037 -> 4038 : Carroll lab,
delete 4055 -> 4056 : you know,
delete 4231 -> 4231 : Yeah.
delete 4519 -> 4520 : is that
delete 4526 -> 4526 : Okay.
delete 4785 -> 4786 : you know,
delete 4914 -> 4914 : any
delete 4942 -> 4942 : um,
delete 4950 -> 4950 : um,
delete 4970 -> 4970 : um,
delete 4973 -> 4973 : uh,
delete 4976 -> 4976 : um,
delete 4980 -> 4980 : uh,
delete 4991 -> 4991 : Um,
delete 5035 -> 5036 : you know,
delete 5052 -> 5053 : You know,
delete 5063 -> 5064 : you know,
delete 5122 -> 5122 : Um,
delete 5130 -> 5130 : um,
delete 5149 -> 5149 : uh,
delete 5153 -> 5153 : and
delete 5160 -> 5160 : Um,
delete 5187 -> 5187 : um,
delete 5193 -> 5193 : uh,
delete 5349 -> 5349 : Yes.
delete 5375 -> 5375 : of
delete 5508 -> 5508 : Yes.
delete 5740 -> 5742 : Thank you. Okay.
delete 5761 -> 5761 : like
delete 5913 -> 5913 : it's
delete 5959 -> 5961 : Just want to
delete 6004 -> 6007 : So thank you. Okay.

SUBSTITUTIONS:
So I'm. OK,  -->  Okay,
areas  -->  errors
he  -->  you
Stevens  -->  Stephens
Stevens  -->  Stephens
Stephens  -->  Stevens
first-year  -->  first year
CARE  -->  Carroll
an excess.  -->  mix-ups.
Stephens  -->  Stevens
Invaluable  -->  and valuable
Stephens.  -->  Stevens.
we've  -->  we
asked  -->  ask
24-7,  -->  24 seven,
Carroll  -->  Carol
Jessie,  -->  Jesse,
And  -->  Um, and we,
result  -->  results
seq  -->  sequence.
was  -->  is
Dori Schaefer,  -->  Dory Shaper,
in the Prism Rock Excel? Yeah,  -->  Is that,
1B,  -->  figure one B
Number of missing segments: 83

In [100]:
LOG['Total_n_missingSegments [from individual files]'] = df_m.shape[0]
for speaker in speaker_stt:
    LOG[f'Total_n_missingSegments_{speaker}'] = df_m[df_m['speaker']==speaker].shape[0]
LOG

{'n_total_words': 7322,
 'n_total_segments': 505,
 'n_mapped_words': 7078,
 'n_total_assigned_segments_round1': 483,
 '%_assigned_segments_round1': 0.9507874015748031,
 'n_total_assigned_segments_round2': 485,
 '%_assigned_segments_round2': 0.9547244094488189,
 'n_total_assigned_segments_round3': 485,
 '%_assigned_segments_round3': 0.9547244094488189,
 'n_total_assigned_segments_round4': 486,
 '%_assigned_segments_round4': 0.9566929133858267,
 'missing_segments': 22,
 'n_missing_words': 48,
 '%_missing_words': 0.0065555859054903035,
 'n_missing_blocks': 99,
 '%_missing_blocks': 0.21212121212121213,
 'Total_n_missingSegments [from individual files]': 83,
 'Total_n_missingSegments_16778242 Kristin Bittinge': 1,
 'Total_n_missingSegments_16781314 Marsha Moses': 8,
 'Total_n_missingSegments_16790530 Zhongcong Xie': 17,
 'Total_n_missingSegments_16797698 David Paul': 4,
 'Total_n_missingSegments_16806914 Rich Goldstein': 1,
 'Total_n_missingSegments_16807938 Allison Bialas': 52}

In [101]:
cols_keep = ['n_words', 'speaker', 'Missing Text',  'Ref-Start Time', 'Ref-End Time','Transcript Text']
master_operations[cols_keep]

,n_words,speaker,Missing Text,Ref-Start Time,Ref-End Time,Transcript Text
1,12,16797698 David Paul,Hello. Yeah. It's Okay. Okay. you Thank you. Thank you. Okay. Okay.,00:18:13,00:18:35,"[*******] I'm curious to hear more about how you interacted with Dr. Stevens, whether it was common to have Dr. Stephens look at the raw data. What sort of procedures did you employ for the review of that kind of material?"
1,9,16790530 Zhongcong Xie,"Hi. you you you Thank you. you No, no,",00:19:54,00:19:57,"[*******] Dr. Paul, you can finish first."
4,9,16781314 Marsha Moses,"Thank you. Bye. Go ahead, go ahead. Thank you.",00:33:06,00:33:10,"[*******] So Allison, can you just walk us through how you wrote the Nature Neuroscience paper?"
0,6,16781314 Marsha Moses,Hello. So this is D'Andrea Wright.,00:02:18,00:02:22,[*******] You want to make make a statement and we're happy to hear that. So it's all yours.
6,5,16781314 Marsha Moses,for you? You know. Thanks.,00:46:08,00:46:11,"[*******] David, do you have any more questions?"
...,...,...,...,...,...,...
39,1,16807938 Allison Bialas,"uh,",00:40:03,00:41:38,"So there were a lot of people that gave me some help in terms of just reading the paper and giving feedback on whether it [*******] flowed well and seemed to be, you know, okay. For the Nature Neuroscience paper, I had actually, I don't remember everyone who read it, but I had quite a few. I remember, for example, that Beth told me to have Dr. Qinfei Chen read it, who was in our department and who was on my dissertation advisory committee. Larry Benowitz, who is also on my dissertation advisory committee, read it and gave me feedback. Obviously, Beth read it. Dory Shaper, who was a postdoc in the lab, read it. The other postdocs in the lab at the time, which I don't remember exactly how many there were, but I got feedback from quite a number of people on the paper. The 2017 Nature paper, Mike, you know, read it and would give me feedback or edits on what I had written. We had the other authors of the paper read it, but that was really it. And honestly, they didn't provide that much feedback. I think George Sokos, who's one of the authors, probably was one of the more helpful people in reviewing it, but I don't think anybody reviewed it in super careful detail."
40,1,16807938 Allison Bialas,and,00:40:03,00:41:38,"So there were a lot of people that gave me some help in terms of just reading the paper and giving feedback on whether it flowed well and [*******] seemed to be, you know, okay. For the Nature Neuroscience paper, I had actually, I don't remember everyone who read it, but I had quite a few. I remember, for example, that Beth told me to have Dr. Qinfei Chen read it, who was in our department and who was on my dissertation advisory committee. Larry Benowitz, who is also on my dissertation advisory committee, read it and gave me feedback. Obviously, Beth read it. Dory Shaper, who was a postdoc in the lab, read it. The other postdocs in the lab at the time, which I don't remember exactly how many there were, but I got feedback from quite a number of people on the paper. The 2017 Nature paper, Mike, you know, read it and would give me feedback or edits on what I had written. We had the other authors of the paper read it, but that was really it. And honestly, they didn't provide that much feedback. I think George Sokos, who's one of the authors, probably was one of the more helpful people in reviewing it, but I don't think anybody reviewed it in super careful detail."
41,1,16807938 Allison Bialas,"Um,",00:40:03,00:41:38,"So there were a lot of people that gave me some help in terms of just reading the paper and giving feedback on whether it flowed well and seemed to be, you know, okay. [*******] For the Nature Neuroscience paper, I had actually, I don't remember everyone who read it, but I had quite a few. I remember, for example, that Beth told me to have Dr. Qinfei Chen read it, who was in our department and who was on my dissertation advisory committee. Larry Benowitz, who is also on my dissertation advisory committee, read it and gave me feedback. Obviously, Beth read it. Dory Shaper, who was a postdoc in the lab, read it. The other postdocs in the lab at the time, which I don't remember exactly how many there were, but I got feedback from quite a number of people on the paper. The 2017 Nature paper, Mike, you know, read it and would give me feedback or edits on what I had written. We had the other authors of the paper read it, but that was really it. And honestly, they didn't provide that much feedback. I think George Sokos, who's one of the authors, probably was one of the more helpful people in reviewing it, but I don't think anybody reviewed it in super careful detail."
42,1,16807938 Allison Bialas,"um,",00:40:03,00:41:38,"So there were a lot of people that gave me some help in terms of just reading the paper and giving feedback on whether it flowed well and seemed to be, you know, okay. For the Nature Neuroscience paper, I had actually, I don't remember everyone who read it, but I had quite a few. I remember, for example, that [*******] Beth told me to have Dr. Qinfei Chen read it, who was in our department and who was on my dissertation advisory committee. Larry Benowitz, who is also on my dissertation advisory committee, read it and gave me feedback. Obviously, Beth read it. Dory Shaper, who was a postdoc in the lab, read it. The other postdocs in the lab at the time, which I don't remember exactly how many there were, but I got feedback from quite a number of people on the paper. The 2017 Nature paper, Mike, you know, read it and would give me feedback or edits on what I had written. We had the other authors of the paper read it, but that was really it. And honestly, they didn't provide that much feedback. I think George Sokos, who's one of the authors, probably was one of the more helpful people in reviewing it, but I don't think anybody reviewed it in super careful detail."
0,1,16778242 Kristin Bittinge,Ciao.,00:48:29,00:48:48,"[*******] Dr. Bayales, I'm going to ask if you and Mr. Goldstein, if I can put you back in the waiting room for just a couple minutes to let the panel debrief for a couple minutes. And then if they have any additional questions, I'll bring you back in. Either way, I'll bring you back in to let you know that we're all set. But it'll just be about five minutes."

### Replace Blocks to Include Missing Texts

In [102]:
edited_transcript = copy.deepcopy(result)
for row_idx in range(len(master_operations)):
    block = master_operations.iloc[row_idx]
    new_transcript  = block['Edited Transcript']
    block_idx = int(block['block_idx'])
    assert block_idx == edited_transcript[block_idx]['block_idx']
    edited_transcript[block_idx]['text'] =new_transcript

    
output_fileName_withMissing = os.path.join(f'reconstruction-withMissing-{project_name}.txt')

with open(output_fileName_withMissing, "w", encoding="utf-8-sig") as f:
                get_speaker_aware_transcript(edited_transcript, f)

In [103]:
edited_transcript[0].keys()

dict_keys(['speaker', 'start', 'end', 'text', 'block_idx'])

## Create Word Documents

In [104]:
from docx import Document
from docx.shared import Inches, Pt
from docx.oxml.ns import qn
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

def df_to_docx_table(df, filepath, title=None, col_widths=None, fontsize=10):
    """
    Write a pandas DataFrame to a .docx file as a table.

    Args:
        df (pd.DataFrame): DataFrame to write.
        filepath (str): Path to save the .docx file (e.g. "out.docx").
        title (str or None): Optional title to add above the table.
        col_widths (list or None): Optional list of widths in inches for each column.
                                   If provided length must match number of columns.
                                   Example: [1.5, 2.0, 1.0]
        fontsize (int): Font size for table text (points).

    Returns:
        str: filepath saved.
    """
    # lazy import pandas type-check (optional)
    import pandas as pd
    if not hasattr(df, "columns"):
        raise ValueError("df must be a pandas DataFrame")

    # create document
    doc = Document()

    # optional title
    if title:
        p = doc.add_paragraph()
        run = p.add_run(title)
        run.bold = True
        run.font.size = Pt(fontsize + 2)
        p.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        doc.add_paragraph()  # blank line

    # create table (header row + data rows)
    rows = len(df) + 1
    cols = len(df.columns)
    table = doc.add_table(rows=rows, cols=cols)
    table.style = 'Table Grid'  # simple grid style; change if you have other styles

    # header row
    for ci, col_name in enumerate(df.columns):
        cell = table.rows[0].cells[ci]
        cell.text = str(col_name)
        # bold header text and set font size
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.font.bold = True
                run.font.size = Pt(fontsize)

    # fill data rows
    for r, (_, row) in enumerate(df.iterrows(), start=1):
        for c, col in enumerate(df.columns):
            value = row[col]
            # replace NaN/None with empty string
            if pd.isna(value):
                text = ""
            else:
                text = str(value)
            cell = table.rows[r].cells[c]
            cell.text = text
            # set font size for content
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(fontsize)

    # optional: set column widths (in inches)
    if col_widths is not None:
        if len(col_widths) != cols:
            raise ValueError("col_widths length must match number of DataFrame columns")
        for ci, width_in in enumerate(col_widths):
            for cell in table.columns[ci].cells:
                cell.width = Inches(width_in)
                # also set tcPr w to keep word from auto-wrapping too aggressively
                # (python-docx does not guarantee exact widths in many viewers, but helps)
    # save
    doc.save(filepath)
    return filepath

In [105]:
### Table of master operations
df_to_docx_table(df = master_operations, filepath = 'operational.docx', title=None, col_widths=None, fontsize=10)

'operational.docx'

# Generate Transcript [Word Document]

In [106]:
# !pip install docx
# !pip install exceptions
# !pip install python-docx
# !pip install docx2pdf
import docx

In [107]:
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

# Paths to files
# docx_path = os.path.join(output_dir,f'reconstruction-{project_name}.docx')
docx_path = os.path.join(f'reconstruction-{project_name}.docx')

# Create a new Word document

doc = Document()

# Read the file and remove all empty lines
# with open(output_fileName , "r", encoding="utf-8") as file:
#     for line in file:
#         stripped_line = line.strip()
#         if stripped_line:  # Ignore empty lines
#             doc.add_paragraph(stripped_line)

# ---------- ADD PAGE NUMBER FOOTER ----------
section = doc.sections[0]
footer = section.footer
footer_para = footer.paragraphs[0]
footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

run = footer_para.add_run()

fldChar_begin = OxmlElement('w:fldChar')
fldChar_begin.set(qn('w:fldCharType'), 'begin')

instrText = OxmlElement('w:instrText')
instrText.text = 'PAGE'

fldChar_end = OxmlElement('w:fldChar')
fldChar_end.set(qn('w:fldCharType'), 'end')

run._r.append(fldChar_begin)
run._r.append(instrText)
run._r.append(fldChar_end)
# -------------------------------------------
with open(output_fileName , "r", encoding="utf-8") as file:
    for line in file:
        stripped_line = line.strip()
        if not stripped_line:
            continue  # skip empty lines

        # Regex to extract timestamp, speaker, and text
        match = re.match(r"(\[.*?\])\s*(.*?):\s*(.*)", stripped_line)
        para = doc.add_paragraph()
        para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY  #  justify paragraph

        if match:
            timestamp, speaker, text = match.groups()

            # Add timestamp normally
            para.add_run(timestamp + " ")

            # Add speaker name in bold
            run_speaker = para.add_run(speaker + ": ")
            run_speaker.bold = True

            # Add the rest of the text normally
            para.add_run(text)
        else:
            # If line doesn't match the pattern, just add it normally
            para.add_run(stripped_line)

# Save the Word file
doc.save(docx_path)

In [108]:
from docx.shared import RGBColor

def colored_doc(output_fileName, docx_path):
    doc = Document()
    
    # ---------- ADD PAGE NUMBER FOOTER ----------
    section = doc.sections[0]
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    run = footer_para.add_run()
    
    fldChar_begin = OxmlElement('w:fldChar')
    fldChar_begin.set(qn('w:fldCharType'), 'begin')
    
    instrText = OxmlElement('w:instrText')
    instrText.text = 'PAGE'
    
    fldChar_end = OxmlElement('w:fldChar')
    fldChar_end.set(qn('w:fldCharType'), 'end')
    
    run._r.append(fldChar_begin)
    run._r.append(instrText)
    run._r.append(fldChar_end)
    # -------------------------------------------
    with open(output_fileName , "r", encoding="utf-8") as file:
        for line in file:
            stripped_line = line.strip()
            if not stripped_line:
                continue  # skip empty lines
    
            # Regex to extract timestamp, speaker, and text
            match = re.match(r"(\[.*?\])\s*(.*?):\s*(.*)", stripped_line)
            para = doc.add_paragraph()
            para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY  #  justify paragraph
    
            if match:
                timestamp, speaker, text = match.groups()
    
                # Add timestamp normally
                para.add_run(timestamp + " ")
    
                # Add speaker name in bold
                run_speaker = para.add_run(speaker + ": ")
                run_speaker.bold = True
    
                # Add the rest of the text normally
                # para.add_run(text)

                parts = re.split(r"(\*\*.*?\*\*|\*.*?\*)", text)
                
                for part in parts:
                    if part.startswith("**") and part.endswith("**"):
                        run = para.add_run(part[2:-2])
                        run.font.color.rgb = RGBColor(255, 0, 0)      # RED
                    elif part.startswith("*") and part.endswith("*"):
                        run = para.add_run(part[1:-1])
                        run.font.color.rgb =  RGBColor(0, 128, 0)     # ORANGE
                    else:
                        para.add_run(part)
            else:
                # If line doesn't match the pattern, just add it normally
                para.add_run(stripped_line)

    # Save the Word file
    doc.save(docx_path)

In [109]:
## reconstruction  
colored_doc(output_fileName, docx_path= 'colored-transcript.docx')
## reconstrucion with missing
colored_doc(output_fileName_withMissing, docx_path= 'colored-transcript_wMissing.docx')

# Save log

In [110]:
import json
json_path = os.path.join(output_dir, f'log_{project_name}.json')

with open(json_path, 'w', encoding='utf-8') as f:
  json.dump(LOG, f, ensure_ascii=False, indent=4)

In [111]:
LOG

{'n_total_words': 7322,
 'n_total_segments': 505,
 'n_mapped_words': 7078,
 'n_total_assigned_segments_round1': 483,
 '%_assigned_segments_round1': 0.9507874015748031,
 'n_total_assigned_segments_round2': 485,
 '%_assigned_segments_round2': 0.9547244094488189,
 'n_total_assigned_segments_round3': 485,
 '%_assigned_segments_round3': 0.9547244094488189,
 'n_total_assigned_segments_round4': 486,
 '%_assigned_segments_round4': 0.9566929133858267,
 'missing_segments': 22,
 'n_missing_words': 48,
 '%_missing_words': 0.0065555859054903035,
 'n_missing_blocks': 99,
 '%_missing_blocks': 0.21212121212121213,
 'Total_n_missingSegments [from individual files]': 83,
 'Total_n_missingSegments_16778242 Kristin Bittinge': 1,
 'Total_n_missingSegments_16781314 Marsha Moses': 8,
 'Total_n_missingSegments_16790530 Zhongcong Xie': 17,
 'Total_n_missingSegments_16797698 David Paul': 4,
 'Total_n_missingSegments_16806914 Rich Goldstein': 1,
 'Total_n_missingSegments_16807938 Allison Bialas': 52}

## New functions - Spelling

In [132]:
### remove time stamps

def get_speaker_aware_transcript(sentences_speaker_mapping, f, timestamp=True):
    previous_speaker = sentences_speaker_mapping[0]["speaker"]
    start_time = sentences_speaker_mapping[0]['start']
    start_time = time.strftime('%H:%M:%S', time.gmtime(start_time))

    end_time = sentences_speaker_mapping[0]['end']
    end_time = time.strftime('%H:%M:%S', time.gmtime(end_time))

    full_sentence = ""
    last_endTime = end_time

    for sentence_dict in sentences_speaker_mapping:
        # if 'speaker' not in sentence_dict:
        #     speaker = speaker
        #     sentence= sentence_dict['word']
            
        # else:
        speaker = sentence_dict["speaker"]
        sentence = sentence_dict["text"]
        end_time = sentence_dict['end']
        end_time = time.strftime('%H:%M:%S', time.gmtime(end_time))

        # If this speaker doesn't match the previous one, start a new paragraph
        if speaker != previous_speaker:
            if timestamp:
                f.write(f"\n\n[{start_time}-{last_endTime}] {previous_speaker}: {full_sentence}")
            else:
                f.write(f"\n\n{previous_speaker}: {full_sentence}")
            previous_speaker = speaker
            full_sentence = ""
            start_time = sentence_dict['start']
            start_time = time.strftime('%H:%M:%S', time.gmtime(start_time))

        # No matter what, write the current sentence
        #f.write(sentence + " ")
        full_sentence= full_sentence + sentence + " "
        last_endTime = end_time
    
    f.write(f"\n\n[{start_time}-{last_endTime}] {speaker}: {full_sentence}")

In [149]:
import re
from textblob import TextBlob

## grammar corrections

slang_map = {
        "wanna": "want to",
        "gonna": "going to",
        "gotta": "got to",
        "lemme": "let me",
        "kinda": "kind of",
        "sorta": "sort of",
        "outta": "out of",
        "ain't": "is not",
        "ya": "you",
        "cuz": "because",
        "cause": "because",
        "dunno": "do not know"
    }

def normalize_slang(text, slang_map):
    # Replace whole words only (case insensitive)
    for slang, formal in slang_map.items():
        pattern = r'\b' + re.escape(slang) + r'\b'
        text = re.sub(pattern, formal, text, flags=re.IGNORECASE)
    return text

def correct_spelling(text):
    blob = TextBlob(text)
    corrected_text = str(blob.correct())
    
    original_words = text.split()
    corrected_words = corrected_text.split()
    for orig, corr in zip(original_words, corrected_words):
        if orig != corr:
            print(f"{orig}  →  {corr}")
    return corrected_text

def capitalize_pronoun_i(text):
    """
    Capitalizes standalone 'i' pronoun.
    Does NOT affect words like 'in', 'is', etc.
    """
    return re.sub(r'\bi\b', 'I', text)

def capitalize_sentences(text):
    """
    Capitalizes the first letter after ., ?, or !
    and also capitalizes the first letter of the text.
    """

    # Capitalize first letter of entire text
    text = text.strip()
    if text:
        text = text[0].upper() + text[1:]

    # Capitalize letter after sentence-ending punctuation
    text = re.sub(
        r'([.!?]\s+)([a-z])',
        lambda m: m.group(1) + m.group(2).upper(),
        text
    )

    return text

In [158]:
def correct_text(original_text):
    
    ## remove slangs
    text = normalize_slang(original_text, slang_map)

    ### capitalize nouns (I)
    text = capitalize_pronoun_i(text)

    ### capitalize letter at the beginning of sentences
    text = capitalize_sentences(text)
    
    ### correct spelling 
    # text = correct_spelling(text)
    
    return text

In [159]:
def correct_text_block():
    for block in edited_transcript:
        block['text'] = correct_text(block['text'])

In [160]:
t = copy.deepcopy(edited_transcript)
for block in t:
        block['text']  = '''i dont wanna go. let's go to the theater. I dont know, i am not hungry ... eat better'''
        block['text'] = correct_text(block['text'])
        break

{'speaker': '16778242 Kristin Bittinge',
 'start': 3.48,
 'end': 79.707,
 'text': "I dont want to go. Let's go to the theater. I dont know, I am not hungry ... Eat better",
 'block_idx': 0}

In [161]:
import re
from docx import Document
from docx.shared import RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

def _add_colored_runs(para, text):
    # Split by **...** or *...*
    parts = re.split(r"(\*\*.*?\*\*|\*.*?\*)", text)
    for part in parts:
        if part.startswith("**") and part.endswith("**"):
            run = para.add_run(part[2:-2])
            run.font.color.rgb = RGBColor(255, 0, 0)   # red
        elif part.startswith("*") and part.endswith("*"):
            run = para.add_run(part[1:-1])
            run.font.color.rgb = RGBColor(0, 128, 0)   # green (your comment says ORANGE)
        else:
            para.add_run(part)

def create_word_document_transcriptColored_noTimeStamp(docx_path, output_fileName):
    doc = Document()

    # ---------- ADD PAGE NUMBER FOOTER ----------
    section = doc.sections[0]
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = footer_para.add_run()
    fldChar_begin = OxmlElement('w:fldChar')
    fldChar_begin.set(qn('w:fldCharType'), 'begin')

    instrText = OxmlElement('w:instrText')
    instrText.text = 'PAGE'

    fldChar_end = OxmlElement('w:fldChar')
    fldChar_end.set(qn('w:fldCharType'), 'end')

    run._r.append(fldChar_begin)
    run._r.append(instrText)
    run._r.append(fldChar_end)
    # -------------------------------------------

    # Timestamp is OPTIONAL now
    pattern = re.compile(r"^(?:\[(.*?)\]\s*)?([^:]+):\s*(.*)$")

    with open(output_fileName, "r", encoding="utf-8") as file:
        for line in file:
            stripped_line = line.strip()
            if not stripped_line:
                continue

            para = doc.add_paragraph()
            para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

            m = pattern.match(stripped_line)

            if m:
                timestamp, speaker, text = m.groups()

                # Add timestamp if present
                if timestamp:
                    para.add_run(f"[{timestamp}] ")

                # Speaker in bold
                run_speaker = para.add_run(speaker.strip() + ": ")
                run_speaker.bold = True

                # Color-marked text
                _add_colored_runs(para, text)

            else:
                # No speaker/timestamp format, but STILL color ** ** / * *
                _add_colored_runs(para, stripped_line)

    doc.save(docx_path)

In [165]:
create_word_document_transcriptColored('test.docx',output_fileName_withMissing)

In [177]:
import re


def remove_repeated_words(text, threshold=3):
    # word repeated with optional comma/space between
    pattern = re.compile(r'\b(\w+)(?:[,\s]+\1\b){' + str(threshold) + r',}', re.IGNORECASE)

    prev = None
    while prev != text:
        prev = text
        text = pattern.sub(r'\1', text)

    return text




text = """uh uh uh uh uh uh uh uh uh uh And we are doing our best"""
remove_repeated_words(x, threshold=4)

"SPEAKER_02: Sure. I mean, I don't think I have much to say. I mean, I've said pretty much what I said. I mean, I could say, but I don't want to emphasize that. I mean, I do understand. I mean, this raises concerns. And again, I mean, we take this very seriously. I mean, again, I am transparent that we have not been doing any data checks from or, I mean, concrete data checks from beginning, just because, I mean, that's how I have been trained for many years, and that's basic norm that, I mean, I kind of know from before, and that's also true from many of the collaborations with my other collaborators for the past years. I mean, that's how I learned it. But then, of course, I mean, to prevent this from happening again in the future, I mean, we are taking this very seriously, and we are implementing some major changes in the lab to really try to safeguard our data uh, And we are doing our best to try to address those comments. And again, for the previous slide, I cannot really, I mean, make a decision for those, I mean, publications, but for the one at least that I'm the sole corresponding author, I'll do my best to try to do whatever we can to address that. Yeah, but I mean, I think that's what I wanted to say. And again, I mean, we have been working so hard, I mean, to establish the lab, and we're essentially one of the best labs in biofabrication. And again, having all this, I mean, questionable papers is going to, I mean, damage our reputation, not having them. So we don't have any reason to really, I mean, falsify the data to, I mean, just for that purpose. I mean, we're doing really well right now. And there's no, absolutely no reason for us to do anything like that in the lab."